Talend/data-prep

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetLocation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetLocationMapping.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/json/DataSetLocationModule.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/json/DefaultLocationMappingConfiguration.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/locator/DataSetLocator.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/locator/DataSetLocatorService.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/locator/HdfsDataSetLocator.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/locator/HttpDataSetLocator.java
Because the current implement uses @JsonSubTypes on the DataSetLocation interface where all implementations are explicitely listed, it not possible to provide a custom implementation of DataSetLocation whereas DataPrep offers a pluggeable way to define DataSetLocators and DataSetContentStores.
The idea here was to replace the JsonSubTypes by a Jackson module that lists declared DataSetLocation implementations (declaration is made using an instance of DataSetLocationMapping).
I made DataSetLocator extend DataSetLocationMapping so that it's the Locator responsability to define the Location it works with.
> Accept other DataSetLocation implementations

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
* Limit node: takes a Runnable iso. Consumer<Void>
* Writer node: only emits written rows to subsequent nodes.
> TDP-1788: Misc changes

- dataprep-webapp/src/app/components/datagrid/index-header/datagrid-index-header-component.spec.js
- dataprep-webapp/src/app/components/datagrid/index-header/datagrid-index-header.html
- dataprep-webapp/src/app/components/transformation/menu/transformation-menu.html
- dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu-directive.spec.js
- dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html
- dataprep-webapp/src/app/css/utils/_menu_list.scss
The <a> tag is useless, so I replaced it with a "span" tag
> replaced <a> tag by <span> in the grid header menus

- dataprep-backend-common/src/main/resources/org/talend/dataprep/error_messages.properties
- when a TDP exception is thrown during authentication process it is now used to build the error message
- when the TAC is not reachable, there is an error message that clearly states it
> TDP-2469: authentication errors are now handled

- dataprep-webapp/src/app/components/playground/playground-controller.js
- dataprep-webapp/src/app/services/statistics/statistics-service.js
- dataprep-webapp/src/app/services/statistics/statistics-service.spec.js
**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
1. Import a BIG dataset. Wait for the playground to open
2. The playground is still trying to fetch the stats. Add a filter.
3. Close the playground
4. Open the dataset again (before the stats are fully computed)
We have an error in console during filtered statistics computation (no stats yet).
The previous filters are not set du to the error.
We don't compute filtered stats when we dont have stats
**Does this PR introduce a breaking change?**
> TDP-2670: do not compute filtered stats when we dont have stats

- dataprep-webapp/package.json
[TDP-2784](https://jira.talendforge.org/browse/TDP-2784)
Bootstrap-theme version that we pull was 0.x.x but in 0.7, there is a provided font packaged with it and our build system do not package it --> problem when it try to get the font.
`This is a quick fix to unblock the build !`
We pull a version 0.6.x instead, but a new PR will come to package the font and remove the font definition defined in data-prep
> TDP-2784: fix bootstrap theme to version 0.6.x as quick fix

- dataprep-backend-common/src/main/java/org/talend/dataprep/configuration/BaseContent.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/preparation/PreparationTest.java
- dataprep-backend-common/src/test/resources/org/talend/dataprep/preparation/preparationDetailsSteps.json
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationController.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
- dataprep-preparation/src/test/resources/org/talend/dataprep/preparation/service/preparation_1234.json
- dataprep-preparation/src/test/resources/org/talend/dataprep/preparation/service/preparation_beer.json
As the PreparationActions id generation changed, the root has its id forced to the 1.3 one to keep compatibility.
> TDP-2754: made the root step PreparationActions ID constant to the value generated by the old code

- dataprep-webapp/src/app/components/lookup/grid/header/_lookup-datagrid-header.scss
None
- [] The code coverage on new code is > 75 % for backend and > 95% for frontend
After bootstrap integration, the font size changed and introduced some regression. The `add to dataset` label in lookup panel is a regression that has not been fixed.
> fix(lookup): add-to-dataset font size

- dataprep-backend/pom.xml
https://jira.talendforge.org/browse/TDP-2924
**What is the current behavior?**
We were using Spring Boot 1.4.1.
We are now using Spring Boot 1.4.2 (see https://github.com/spring-projects/spring-boot/milestone/73?closed=1 for full change description). Nothing exiting for DP in 1.4.2 release but helps us following Spring release train and make hopefully next upgrades easier.
> TDP-2924: Upgrade Spring Boot version (1.4.1 -> 1.4.2).

- dataprep-webapp/config/webpack.config.js
In production mode, the react lib was the one from development mode, just minified. That includes a great loss of performance compared to the react production mode.
Webpack set the NODE_ENV to enable production mode in react.
> chore: set NODE_ENV in webpack to enable production mode on react

- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITestClient.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/api/preparation/json/PreparationDetailsJsonSerializer.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
No Jira
**What is the current behavior?**
The added row metadata information in a preparation wasn't serialized to JSON, leaving the feeling this information would be sent to clients.
Row metadata is correctly included in JSON response.
> (fix) Fix missing row metadata in serialized preparation details.

- dataprep-webapp/config/sass.conf.js
- dataprep-webapp/config/webpack.config.js
- dataprep-webapp/karma.conf.js
With react-talend-components 0.15.1, the bootstrap theme vars need to be exposed.
Register bootstrap theme vars in sass loader config
> feat: update webpack sass loader config

- dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetLocation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/location/LocalStoreLocation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/jsonschema/ComponentProperties.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
- dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
- dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
- dataprep-backend/pom.xml
- dataprep-dataset/src/main/java/org/talend/dataprep/api/dataset/location/HdfsLocation.java
- dataprep-dataset/src/main/java/org/talend/dataprep/api/dataset/location/HttpLocation.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/api/Import.java
- dataprep-webapp/package.json
- dataprep-webapp/src/app/components/import/import-controller.js
- dataprep-webapp/src/app/components/import/import-controller.spec.js
- dataprep-webapp/src/app/components/import/import.html
- dataprep-webapp/src/app/components/import/import.scss
- dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
- dataprep-webapp/src/app/components/widgets/button-dropdown/button-dropdown.html
- dataprep-webapp/src/app/components/widgets/button-dropdown/widget-button-dropdown-directive.js
- dataprep-webapp/src/app/components/widgets/button-dropdown/widget-button-dropdown-directive.spec.js
- dataprep-webapp/src/app/components/widgets/modal/_modal.scss
- dataprep-webapp/src/app/css/vendors/libs/base/_forms.scss
- dataprep-webapp/src/app/services/import/import-rest-service.spec.js
- dataprep-webapp/src/i18n/en.json
https://jira.talendforge.org/browse/TDP-2048
* TDP-2965: add wiring for tcomp properties fetching
- wire API to dataset for tcomp properties on /api/datasets/imports/{import}/jsonschemaparameters
- wire Dataset to TComp to fetch json-schema params through DatasetLocation.getParametersAsSchema()
- adds basic TComp exceptions and datamodel deserializers to adapt when TComp is usable
linked to TDP-2048
* TDP-2048 TDP-2965: add react-talend-forms dependency
* TDP-2048 TDP-2965: add react-talend-forms ngReact directive
* TDP-2048 TDP-2965: fix too large modal display
* TDP-2048 TDP-2965: Fix some form style
* TDP-2048 TDP-2965: …
> feat(TDP-2048): display datastore form

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/Concat.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ExtractStringTokens.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/SelectParameter.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/parameters/SelectParameterTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/FailedAction.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/TransformationBaseTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/api/action/metadata/TestI18nKeysForActionsTest.java
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/actions_messages.properties
https://jira.talendforge.org/browse/TDP-2987
* Clearer separation between LocalizedItem and TextItem
* i18n operations for LocalizedItem now throw exceptions in case of missing translation.
* ActionsBundle now looks in fallback resource bundle in case of missing translation.
> fix(TDP-2987/backend) Fixes i18n support in select items

- dataprep-webapp/src/app/services/folder/folder-service.js
- dataprep-webapp/src/app/services/folder/folder-service.spec.js
The preparation owner display was based on `author` property from backend.
The preparation owner display was based on `owner.displayName` property from backend.
> fix(TDP-2802): base preparation owner on owner display name

- dataprep-webapp/src/app/components/recipe/recipe-component.spec.js
- dataprep-webapp/src/app/components/recipe/recipe.html
https://jira.talendforge.org/browse/TDP-2936
The group similar modal was always displayed du to wrong ng-if condition.
The group similar modal disappears when not clicked.
> fix(TDP-2936): fixed the show modal condition

- dataprep-webapp/src/app/components/home/home-component.spec.js
- dataprep-webapp/src/app/components/home/home.html
- dataprep-webapp/src/app/components/home/react-home-component.js
- dataprep-webapp/src/app/components/home/react-home-component.spec.js
No way to inject things in the home page root
Allow to inject components to be available in the home page
> feat(TDP-2802): add home global insertion point

- dataprep-webapp/package.json
- dataprep-webapp/src/app/components/widgets-containers/preparation-list/preparation-list-container.js
- dataprep-webapp/src/app/components/widgets-containers/preparation-list/preparation-list-container.scss
- dataprep-webapp/src/app/components/widgets-containers/preparation-list/preparation-list-controller.js
- dataprep-webapp/src/app/services/folder/folder-service.js
- dataprep-webapp/src/app/services/folder/folder-service.spec.js
- dataprep-webapp/src/assets/config/app-settings.json
- dataprep-webapp/src/mocks/Settings.mock.js
- dataprep-webapp/yarn.lock
Only black folder/preparation icons
Add colors and folders specificity : 
* orange folder on classical folders
* blue icon for preparation
> feat(TDP-2802):  folder icons

- dataprep-webapp/package.json
- dataprep-webapp/src/app/components/home/dataset/react-home-dataset-container.js
- dataprep-webapp/src/app/components/home/preparation/react-home-preparation-container.js
- dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
- dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
- dataprep-webapp/src/app/components/widgets-containers/layout/layout-container.js
- dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-container.js
- dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
- dataprep-webapp/yarn.lock
https://jira.talendforge.org/browse/TDP-2459
Add ids on new home page elements. This will generate the ids described in https://jira.talendforge.org/browse/TDP-2459
Waiting for https://github.com/Talend/react-talend-components/pull/164 to upgrade RTC
> feat: add ids on new home page elements

- dataprep-webapp/src/app/components/widgets-containers/breadcrumb/breadcrumb-container.js
- dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
- dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-container.js
NgReact watch depth is `value` by default.
It compares the references
> fix(TDP-2802): configure ngReact watch depth

- dataprep-webapp/src/app/components/about/about-component.spec.js
- dataprep-webapp/src/app/components/about/about.html
e.g. https://jira.talendforge.org/browse/TDP-2833
There is a glitch when toggle button is clicked
Used 1 button instead of 2
> feat(TDP-2933): use 1 button to avoid glitch

- dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview-controller.js
- dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview-controller.spec.js
- dataprep-webapp/src/app/components/playground/playground-controller.spec.js
- dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-container.spec.js
- dataprep-webapp/src/app/index-module.js
- dataprep-webapp/src/app/index-route.js
- dataprep-webapp/src/app/services/onboarding/onboarding-service.js
- dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
- dataprep-webapp/src/app/services/preparation/preparation-service.js
- dataprep-webapp/src/app/services/preparation/preparation-service.spec.js
- dataprep-webapp/src/app/services/state/route/route-state-service.js
- dataprep-webapp/src/app/services/state/route/route-state-service.spec.js
- dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
- dataprep-webapp/src/app/settings/actions/menu-actions-service.js
- dataprep-webapp/src/app/settings/actions/menu-actions-service.spec.js
- dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
- dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
- dataprep-webapp/src/assets/config/app-settings.json
- dataprep-webapp/src/mocks/Settings.mock.js
- dataprep-webapp/yarn.lock
1. go to a folder (not home)
2. go to datasets
3. go back to preparations -- We end up to home folder
We are now back to the previous folder
> fix(TDP-2802): keep prep folder in navigation

- dataprep-webapp/src/app/services/onboarding/onboarding-preparations-constants.js
- dataprep-webapp/src/app/services/onboarding/onboarding-service.js
- dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
The onboarding is still plugged on the old home page
Onboarding now targets new home page
> feat(TDP-2802): adapt onboarding to new home page

- dataprep-webapp/src/app/components/home/react-home-component.js
- dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
- dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js
- dataprep-webapp/src/assets/config/app-settings.json
- dataprep-webapp/src/mocks/Settings.mock.js
https://jira.talendforge.org/browse/TDP-3134
On draft (xls multi-sheet) datasets, when user click to open, there is no modal to choose the sheet to use.
The dataset xls preview modal appears
> fix(TDP-2802 TDP-3134): open xls preview on draft dataset

- dataprep-backend-service/pom.xml
- dataprep-backend-service/src/main/java/org/talend/dataprep/info/ManifestInfo.java
Named 'git.properties' to 'dataprep-git.properties'
https://jira.talendforge.org/browse/TDP-3160
> feat TDP-3160: give a dataprep-specific name to git properties file

- dataprep-webapp/src/app/components/playground/playground-controller.js
- dataprep-webapp/src/app/components/playground/playground-controller.spec.js
- dataprep-webapp/src/app/index-route.js
https://jira.talendforge.org/browse/TDP-2816
> feat(TDP-2816): no playground reload on export back

- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
e.g. https://jira.talendforge.org/browse/TDP-2786
Please, have a look at the jira.
Please, have a look at the jira.
> bugfix(TDP-2786) tDataprepRun [DI] - Shared preparation chose is locked

- dataprep-webapp/src/app/components/transformation/form/_transformation-form.scss
https://jira.talendforge.org/browse/TDP-3236
Due to #420 there are extra padding in checkboxes that cause the bad display.
The padding is now not applied to the checkboxes
> fix(TDP-3236): fix checkboxes in generated forms

- dataprep-webapp/src/index.html
https://jira.talendforge.org/browse/TDP-3287
https://github.com/h5bp/html5-boilerplate/blob/5.3.0/dist/doc/html.md#x-ua-compatible
> fix(TDP-3287): Disable compatibility mode in internet explorer

- dataprep-webapp/src/app/components/widgets/slidable/_slidable.scss
https://jira.talendforge.org/browse/TDP-2681
https://github.com/DrummerHead/safari-flex-basis-animation-bug
> TDP-2681: Add max-width for Safari 10

- dataprep-webapp/src/app/components/datagrid/datagrid-directive.js
- dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
- dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.spec.js
- dataprep-webapp/src/app/components/datagrid/services/datagrid-style-service.js
- dataprep-webapp/src/app/components/datagrid/services/datagrid-style-service.spec.js
There is no classname on the selected column header
The `selected`classname is added to the header container.
> feat(Grid): add "selected" class name on selected column header

- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/RemoveFolder.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
add response body to RemoveFolder API (to get the err…or message back to the user)
e.g. https://jira.talendforge.org/browse/TDP-3409
> bugfix TDP-3409

- dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
https://jira.talendforge.org/browse/TDP-2839
(don't pay attention to the branch name, I picked the wrong jira number)
This PR only fix the susequent bug of TDP-2839, where the TAB is not switched on prep/dataset open + first click on index cell.
The error is du to a bug in sunchoke. The Tab component manage an internal state, but it can be changed by changing the `selected-tab` input.
But in TDP, we remove and instanciate it again using `ng-if`, this `selected-tab` input is not taken into account at component instanciation. So the selected tab is the first (by default) and don't …
> fix(TDP-2839): ng-show on functions tab to avoid a selected tab sync bug

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractActionMetadata.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/InternalActionDefinition.java
- dataprep-actions/src/test/java/org/talend/dataprep/i18n/ActionsBundleTest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionDefinition.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json
https://jira.talendforge.org/browse/TDP-2956
> fix(TDP-2956): doc url is now back in the functions definition

- dataprep-webapp/.babelrc
- dataprep-webapp/config/webpack.config.js
- dataprep-webapp/package.json
- dataprep-webapp/yarn.lock
Use ES2015 preset, which will transpile every ES2015 feature.
Use babel-preset-env to specify which browsers to support and transpile only what is necessary.
| Chunk | Old size | New size |
|---|---|---|
| App | 1.05MB | 1MB |
| Vendor | 1.51MB | 1.51MB |
| All | 3.91MB | 3.86MB |
> chore: babel-preset-env

- dataprep-actions/src/main/java/org/talend/dataprep/PreparationParser.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValue.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ReplaceOnValue.java
- dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValueTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/ReplaceOnValueTest.java
- dataprep-backend-common/src/test/resources/org/talend/dataprep/i18n/actions_messages.properties
- dataprep-backend-common/src/test/resources/org/talend/dataprep/transformation/api/action/parameters/selectParameter.json
- dataprep-webapp/src/app/services/playground/playground-service.js
- dataprep-webapp/src/app/services/playground/playground-service.spec.js
* split implementation of ReplaceOnValue : ReplaceOnValue to replace value on a column & ReplaceCellValue for a single cell replacement
* update ActionParser to remove the ReplaceOnValue special treatment
* update the front end to send the correct action name
* move actions_messages.properties to the actions module
e.g. https://jira.talendforge.org/browse/TDP-3303
> feat(TDP-3303) : split implementation of replace value

- dataprep-backend-service/src/main/java/org/talend/dataprep/encrypt/AESEncryption.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/encrypt/PropertiesEncryption.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/encrypt/AESEncryptionTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/encrypt/PropertiesEncryptionTest.java
- dataprep-backend/pom.xml
https://jira.talendforge.org/browse/TDP-3502
- add encryption capabilities for passwords in URIs
- enable password encryption in mongodb.uri
- use mongodb.uri property instead of port,user,...
> feat(TDP-3502): allow to specify mongodb.uri as a whole instead of specifics parts

- dataprep-webapp/src/app/components/playground/header/playground-header.html
TDP-2916 - No tooltip for search icon
https://jira.talendforge.org/browse/TDP-2916
> fix(TDP-2916): No tooltip for search icon

- dataprep-webapp/src/app/services/folder/folder-service.spec.js
The expected object is generated before a set of tests. It is used only on 1 test and this test can be executed a few minutes after the generation. So the dates generated by momentJS can be desynchonized.
Generate expected object just at the beginning of the test instead
> test : try to fix test with momentJs

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValue.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Async.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/ExportFormatConversions.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/PreparationRepositoryConfiguration.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/file/FileSystemPreparationRepository.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/processor/BeanConversionServiceWrapper.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/processor/Wrapper.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/processor/WrapperProcessor.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/processor/WrapperProcessorTest.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/configuration/DataSetConversions.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java
No Jira
**What is the current behavior?**
Each BeanConversionService usage were using custom BeanPostProcessors that were very similar. In addition finding all classes that register new conversions was hard to find (no common super class for that).
A simplified BeanPostProcessor interface was introduced (Wrapper) and an abstract class of this Wrapper interface helps finding all the BeanConversionService registrations.
**Other information**:
Commit message
* Removes duplicated code in all DP's bean processors.
* All BeanConversionService configuration now inherit from a common class to ease finding them.
[Misc]
* Improve file …
> [chores] Simplify basic bean post processors

- dataprep-webapp/src/lib/slick.autocolumnsize.js
e.g. https://jira.talendforge.org/browse/TDP-111
All columns are autoresized to min width
All columns are autoresized to their largest value **or their header label**
Linked to #541
> fix(TDP-111): autoresize with largest value

- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/CommonErrorCodes.java
- dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
SCIM client used to fetch users and groups through SCIM API for sharing
now catch SCIM Exceptions and wrap them in TDPException with a relevant
message.
https://jira.talendforge.org/browse/TDP-3414
> feat(TDP-3414): handle SCIM exceptions in client

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValue.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValueTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/api/action/ActionTestWorkbench.java
https://jira.talendforge.org/browse/TDP-3594
* Add missing VALUES_COLUMN Behavior in ReplaceCell action -> if action doesn't indicate it modifies values in input, no invalid value detection is performed (and this is expected).
> fix(TDP-3594) Missing behavior in ReplaceCell action

- dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
e.g. https://jira.talendforge.org/browse/TDP-3709
A double scrollbar appears on actions part. 
Only one scrollbar appears after setting the right height.
> fix(TDP-3709): set header column details height to 48px

- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/PreparationRepositoryConfiguration.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparation.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/api/preparation/PreparationUtilsTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/preparation/FixedIdStep.java
Remove the list of steps id from the PersistentStep object and browse the steps tree from mongodb every time a preparation is read
e.g. https://jira.talendforge.org/browse/TDP-3332
> feat(TDP-3332) : fix number of steps displayed for version

- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/OrphanStepsFinder.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationCleaner.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationOrphanStepsFinder.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/task/PreparationOrphanStepsFinderTest.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/test/PreparationClientTest.java
* AppendStep now have the previous step id (when available)
* replaceHistory method is overriden in EEPreparationService to update versions steps id.
e.g. https://jira.talendforge.org/browse/TDP-3718
> bugfix(TDP-3718) : preparation versioning deal with deleted steps

- dataprep-webapp/src/app/services/preparation/preparation-service.js
- dataprep-webapp/src/app/services/preparation/preparation-service.spec.js
- dataprep-webapp/src/app/services/utils/storage/storage-service.js
- dataprep-webapp/src/app/services/utils/storage/storage-service.spec.js
e.g. https://jira.talendforge.org/browse/TDP-1761
Formerly backend used to edit the preparation ID after a PUT request, so had to deal with the new ID in the Frontend side. This adaptation was causing the bug.
Deleted useless frontend code
> fix(TDP-1761): save aggregation after renaming a preparation

- dataprep-webapp/src/app/components/playground/playground-controller.js
- dataprep-webapp/src/app/components/playground/playground-controller.spec.js
e.g. https://jira.talendforge.org/browse/TDP-3715
> Fix/tdp 3715 Preparation is created although close the dataset without saving preparation

- dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
- dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
- use name instead of id in export list
- make mandatory the S3 format parameter
- change name of S3 export format
- correct S3 region parameter label
- add S3 export format title
https://jira.talendforge.org/browse/TDP-3881
> bugfix(TDP-3881): correct export labels

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportStrategy.java
https://jira.talendforge.org/browse/TDP-3801
* Add way to retrieve preparation at given step (overload of getPreparation(...)).
> fix(TDP-3801): Support code for versioned preparations

- dataprep-backend/pom.xml
https://jira.talendforge.org/browse/TDP-3553 (aka. https://jira.talendforge.org/browse/TDQ-13467) UK Postcode falsely marked as invalid
new DQ libs also contains fixes for the following jiras:
https://jira.talendforge.org/browse/TDQ-13297 Adding an invalid regex breaks Dataprep and TDS. 
https://jira.talendforge.org/browse/TDQ-13046 provide serializable object to hold regexes
> fix(TDP-3553) update DQ libs to include latest bug fixes

- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
- dataprep-api/src/test/resources/org/talend/dataprep/api/service/dataset/bug_TDP-3927_import-col-not-deleted_truncated.csv
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/RowMetadata.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/RowMetadataTest.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
- add cool tests methods in testClient
- add integration test in PreparationAPITest
- make RowMetadata.nextId field serializable by jackson
- add TU to RowMetadata
- small refacto in OptimizedExportStrategy
The bug came from the OptimizedExportStrategy that base its transformation on
cached data. when applying the transformation, RowMetadata had its nextId
field reset and new column ids where not the same as without optimization.
Correction makes nextId serialized in cache.
https://jira.talendforge.org/browse/TDP-3927
- [ x Tests for the changes have been added (for bug fixes / features)
- [ x Docs have been added / updated (for bug fixes / features)
> fix(TDP-3927): serialize nextId in RowMetadata

- dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/conversions/BeanConversionServiceTest.java
- bean conversion with "on the fly" apply registered conversions beforehand
- add tests in integration suite
- extract interface for bean conversion modules
https://jira.talendforge.org/browse/TDP-3964
> fix(TDP-3964): fix preparations versions import

- dataprep-api/src/main/java/org/talend/dataprep/api/service/api/EnrichedPreparation.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
* Modify EnrichedPreparation to add the class name to metadata during serialization
* Add a unitary test
> feat(TDP-3965):  TDataprepRun cannot run a preparation with steps

- dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
When monorepo version will be >= 0.86.0, icons will be shown in front of the dropdown items.
Dropdown items icons are hidden in prevision of monorepo update.
> fix: dropdown items should not have icons

- dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
```
Warning: Failed prop type: Invalid prop `items[0].icon` of type `boolean` supplied to `ActionSplitDropdown`, expected `string`.
```
No errors.
> fix: dont set icon in dropdown when not necessary

- dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
In production mode, we don't have any propTypes defined.  
If ngReact cannot read them then it will not dealing with them
I just duplicate all used props in order to pass values.
Linked to https://github.com/ngReact/ngReact/issues/193
> fix: Declare all used Forms props

- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsService.java
https://jira.talendforge.org/browse/TDP-4033
- [] Chrome, Firefox, Safari, Edge, IE11
-There are 2 configurers (OS and EE) that are applied for the same action. It does not generate the same configurations based on the order of execution.
-Only one is applied based on the version OS or EE
> fix(TDP-4033): resolve appsettings configurer conflict

- dataprep-webapp/src/app/components/recipe/recipe-controller.js
- dataprep-webapp/src/app/components/recipe/recipe-controller.spec.js
- dataprep-webapp/src/app/components/recipe/recipe.html
An error can be thrown if the `reorderedSteps` property is not defined.
No error is thrown if the `reorderedSteps` property is not defined.
> fix: better check for the no steps message

- dataprep-api/src/main/java/org/talend/dataprep/api/service/SearchAPI.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/APIErrorCodes.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
- dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
- dataprep-dataset/src/test/java/org/talend/dataprep/dataset/DataSetImportTest.java
* feat(TDP-4253): escaping data set name parameter in regex search
* feat(TDP-4253): factorize search endpoints
(cherry picked from commit 0388e5e)
* Add check to protect against names with quotes
https://jira.talendforge.org/browse/TDP-4256
> hmdebenque/fix/tdp 4253 dataset filter on name (#741)

- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationCleaner.java
https://jira.talendforge.org/browse/TDP-4198
* Scheduled orphan step cleaner still handle all available tenants.
* Delete preparation only remove orphan step for current tenant.
> fix(TDP-4198): Add remove orphan step for current tenant only.

- dataprep-webapp/.gitignore
- dataprep-webapp/pom.xml
**What is the problem this PR is trying to solve?**
According to @rmannibucau's suggestion in #718, we can use `frontend-maven-plugin` instead of waiting a node installation.
**What is the chosen solution to this problem?**
Add `frontend-maven-plugin` support and use yarn docker image to be consistent.
> chore: frontend-maven-plugin support

- dataprep-backend/pom.xml
- dataprep-dataset/pom.xml
https://jira.talendforge.org/browse/TDP-2780
> fix(TDP-2780): remove deprecated commons-httpclient 3.1

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/SimpleFilterService.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/api/filter/SimpleFilterServiceTest.java
- When creating filter without supplying metadata, handle the edge case of
filtering on no column
- also simplified a tableau writer stream statement
https://jira.talendforge.org/browse/TDP-4291
> fix(TDP-4291): handle edge case in filter deserialization

- dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetMetadata.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/TransformationErrorCodes.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-webapp/src/app/services/playground/playground-service.js
- dataprep-webapp/src/app/services/playground/playground-service.spec.js
- dataprep-webapp/src/app/services/preparation/preparation-service.js
- dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.js
- dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.spec.js
https://jira.talendforge.org/browse/TDP-4362
* Add new REST service to retrieve preparation metadata
> feat(TDP-4362): Add access to preparation metadata

- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
(cherry picked from commit 11ebd11)
https://jira.talendforge.org/browse/TDP-4391
> fix(TDP-4391): NullPointerException in migration from PE2.1 to 2.2

- dataprep-api/src/main/java/org/talend/dataprep/api/service/VersionServiceAPI.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/api/service/info/VersionService.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Versions.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/info/ClassPathManifestInfoProvider.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/info/ManifestInfo.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/info/ManifestInfoProvider.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/api/service/info/VersionServiceTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/info/ClassPathManifestInfoProviderTest.java
- dataprep-backend-service/src/test/resources/git.properties
https://jira.talendforge.org/browse/TDP-XXXX (no jira)
* Extensible mechanism to read versions (ManifestInfoProvider).
* Add to EE build (generates new version file).
> chore: provide mechanism for OS / EE service version

- dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/LimitNode.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParameters.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/configuration/Configuration.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/configuration/PreviewConfiguration.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/cache/CacheKeyGenerator.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/cache/TransformationCacheKey.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/event/PreparationCacheListener.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/BaseSampleExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/cache/TransformationCacheKeyTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/CachedExportStrategyTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategyTest.java
* improve TDP-4330 used to so that the get dataset command gets all the dataset content in case of a sampling
* remove ExportParameters.filterOut that was never used
* add filter in ContentCacheKey
https://jira.talendforge.org/browse/TDP-4443
> bugfix (TDP-4443): Export current sample make export full data

- dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param.html
- dataprep-webapp/src/app/services/utils/converter/converter-service.js
- dataprep-webapp/src/i18n/en.json
* change the generic (and mostly wrong) error message to the only one possible
https://jira.talendforge.org/browse/TDP-4446
> bugfix (TDP-4446): Correct the prompt message

- dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationList.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/SortAndOrderSerializationAdvice.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/ErrorCodeDto.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/FolderRepository.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationController.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationSearchCriterion.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
https://jira.talendforge.org/browse/TDP-4270
- add preparation filter by path to be able to retrieve a specific preparation using name and path filter
- add testing for folder embedded in preparation when retrieving one preparation
> feat TDP-4270 dynamically select prep in di

- dataprep-api/pom.xml
- dataprep-dataset/pom.xml
**What is the problem this Pull Request is trying to solve?**
When trying to run TDP in command line (`mvn` or `java -jar`), it fails with a NoClassDefFound `fill.this.value.in.service.module`.
**What is the chosen solution to this problem?**
It reads the pom to get the start class, there were 2 missing properties
> chore: add missing start class property in pom

- dataprep-backend-service/src/main/java/org/talend/dataprep/help/DocumentationLinksManager.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java
- dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/i18n/DataprepLocaleContextResolverIntegrationTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/i18n/DataprepLocaleContextResolverTest.java
* Spring MVC locale resolver is able to add for every request the
locale defined in configuration and appropriate fallbacks
* TDP-4498: use conf locale in DocumentationLinksManager
* change locale configuration property name
https://jira.talendforge.org/browse/TDP-TDP-3601
> feat(TDP-3601): add the locale resolver

- dataprep-backend-service/src/main/java/org/talend/dataprep/io/CloseableResourceWatch.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/io/CloseableInputStreamComponent.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/io/CloseableResourceWatchTest.java
When using org.talend.daikon.content.DeletableResource that are used to
read/write in cache and store uploaded dataset the streams will be
monitored just the same as other streams.
https://jira.talendforge.org/browse/TDP-4568
> fix(TDP-4568): add watcher for Resource

- dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
* Wrong use of File.list() instead of File.walk().
https://jira.talendforge.org/browse/TDP-4584
> fix(TDP-4584): Unable to delete a folder that once wasn't empty

- dataprep-backend-service/pom.xml
- dataprep-backend/pom.xml
* Revert TQL change from 6.3.1 -> 0.18.3 (change in version number during TDS to Daikon).
https://jira.talendforge.org/browse/TDP-4600
> chore: Fix TQL dependency version

- dataprep-webapp/pom.xml
https://jira.talendforge.org/browse/TDP-4399
> chore(TDP-4399): use m2 profile dev by default

- dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationCleaner.java
* PreparationCleaner dependes on 'preparation.store.orphan.cleanup' property. Default is true.
* disable PreparationCleaner in cloud.
https://jira.talendforge.org/browse/TDP-4689
> feat(TDP-4689) Add ability to disable orphan step cleaner

- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
- dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
* Fix the updateRawDataSet when we want to create a new dataSet, but without name
* Add unit tests
https://jira.talendforge.org/browse/TDP-2902
> fix(TDP-2902) Dataset API allows dataset with empty name

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalid.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalidTest.java
* action is no longer displayed in "invalid menu"
* action is not present in the list for not dictionary columns
https://jira.talendforge.org/browse/TDP-3936
> fix(TDP-3936): make standardize value only available in suggestion

- dataprep-webapp/package.json
- dataprep-webapp/yarn.lock
***What is the problem this PR is trying to solve?**<br><br>Framework/libs/tools are out of date, compared to Talend/ui [version.js](https://github.com/Talend/ui/blob/master/version.js).<br><br>This is an automatic PR, which goal is to align all Framework/libs/tools versions accross all apps.<br><br>**What is the chosen solution to this problem?**<br><br>Run version.js on the webapp.<br><br>Please check Talend/ui [breaking changes log](https://github.com/Talend/ui/blob/master/BREAKING_CHANGES_LOG.md)<br><br>**Please check if the PR fulfills these requirements**
> chore: update versions in data-prep

- dataprep-actions/src/test/java/org/talend/dataprep/i18n/ActionsBundleTest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java
https://jira.talendforge.org/browse/TDP-4755
* Fix fallback for i18n keys is always JVM's default
* Add unit test from TDP-4755's description.
> fix(TDP-4755): Fix fallback for i18n keys is always JVM's default

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/ChangeNumberFormat.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Padding.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Split.java
- dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
- dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
- dataprep-actions/src/test/java/org/talend/dataprep/i18n/ActionsBundleTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedCharsTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/SplitTest.java
- dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/text/splitAction.json
- dataprep-api/src/test/resources/org/talend/dataprep/api/service/export/split.json
- dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_actions.json
- dataprep-api/src/test/resources/org/talend/dataprep/api/service/transformation/split_compare_numbers.json
- dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/Item.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/SelectParameter.java
- dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
- dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_fr.properties
- dataprep-test-api/src/test/resources/features/SmokeTest.feature
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions_string.json
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
- dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json
- dataprep-webapp/src/i18n/fr.json
Multiple fixes on labels
* fix(TDP-4767): Position values not localized in action "Ajouter des caractères supplémentaires"
* fix(TDP-4768): Value "other (region)" not localized in action "Formater le numéro de téléphone"
* fix(TDP-4769): Values not localized in the action "Scinder le texte en parties..."
* fix(TDP-4771): Bad traduction for action "Formater les nombres numbers"
* fix(TDP-4772): "custom" value not localized in the action ""Formater les nombres numbers"
* fix(TDP-4780): Typo in preview after adding 3 steps
* Change and internationalize Streams authentication parameters label
Main JIRA
https://jira.talendforge.org/browse/TDP-2663
Sub-tasks
https://jira.talendforge.org/browse/TDP-4767
https://jira.talendforge.org/browse/TDP-4768 …
> feat(TDP-2663): multiple fixes on labels

- dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/Parameterizable.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Localization.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/format/export/ExportFormat.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVFormat.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/JsonFormat.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsFormat.java
https://jira.talendforge.org/browse/TDP-2663
* Hook default locale setup during bean scan so it gets set *before* bean initialization.
> fix(TDP-2663): Hook default locale set higher in startup sequence.

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractActionMetadata.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalid.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/delete/AbstractFilteringAction.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalidTest.java
removing all scope from StandardizeInvalid make it available in action
list to be used even if the column is not detected as dict based on the
sample and still in suggestions for sample dict-detected columns
https://jira.talendforge.org/browse/TDP-3936
> feat(TDP-3936): remove StandardizeInvalid scope

- dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
when there is no handling defined for a remote service error, dataprep
tries to deserialize it as TDPException. When it cannot we have a strange
stacktrace that mask the real error message.
This read the error content as-is to create the error message
> chore: handle remote error from non dataprep services

- dataprep-webapp/package.json
- dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
- dataprep-webapp/yarn.lock
https://jira.talendforge.org/browse/TDP-4471
> fix(TDP-4471): filter autocompletion is missing for last deleted filter

- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java
remove usage of ? " and * characters in paths because saw as invalid when launched on windows
https://jira.talendforge.org/browse/TDP-4988
> fix(TDP-4988): InvalidPathException in PreparationServiceTest

- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreviewAbstract.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
- dataprep-api/src/test/resources/org/talend/dataprep/api/service/preview/best_sad_songs_of_all_time.csv
- dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineDiffTransformer.java
https://jira.talendforge.org/browse/TDP-5057
> fix(TDP-5057): wrong preview of "calculate time until" step after trim step

- dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
- dataprep-upgrade-common/src/test/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommonTest.java
https://jira.talendforge.org/browse/TDP-5225
* Don't modify root step's actions.
* Add unit test to reproduce issue.
> fix(TDP-5225): Handle cases when preparation action id changes during migration

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
- dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionFormatPhoneNumber.java
- dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/FormatPhoneNumberAction.java
cherry-pick of ad9832c + remove legacy management of old FormatPhoneNumber parameters
https://jira.talendforge.org/browse/TDP-5256
> fix(TDP-5256) format phone number migration task

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
* remove usage of instance variables in singleton action
💡 This fix is really complete with those brought by [TDP-4926](https://jira.talendforge.org/browse/TDP-4926) (cf. PR #1095).
https://jira.talendforge.org/browse/TDP-3988
> fix(TDP-3988): Fix cannot chain multiple convert date actions

- dataprep-api/src/test/java/org/talend/dataprep/api/service/VersionServiceAPITest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/api/service/info/VersionService.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Versions.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/api/service/info/VersionServiceTest.java
- use @Order annotation to order version List
- remove setter used only for testing
- move version order test in API integration test
> chore: remove ops version from OS code

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcherTest.java
* fix(TDP-5378): Limit use of memory in lookup cache
* Filter dataset row to only include column used in Lookup action.
* * unit test for cache test.
https://jira.talendforge.org/browse/TDP-5378
> fix(TDP-5378): Limit memory used in lookup cache (#1181)

- dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTestService.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/i18n/DataprepLocaleContextResolverTest.java
https://jira.talendforge.org/browse/TDP-4172
> fix(TDP-4712): Add Accept-Language forward to Hystrix commands.

- dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java
* Add Accept-Language header value for locale  resolution diagnostics.
> fix(TDP-4712): More log

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Trim.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/ActionMetadataTestUtils.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ChangeDatePatternTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSinceTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/ExtractNumberTest.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/TrimTest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/ColumnMetadata.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Quantiles.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Statistics.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformer.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/StatisticsNodesBuilder.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/StepNode.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/UpdatedStepVisitor.java
This reverts commit 264902c
dataprep-api and dataprep-test-api skipped due to conflicts
https://jira.talendforge.org/browse/TDP-5530
> Revert "fix(TDP-4926): bug change date format statistics (#1095)"

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datablending/LookupTest.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/RowMetadata.java
- dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/RowMetadataTest.java
* fix(TDP-5538): Fix breaking change in column ids.
* Fix breaking change in column ids (column names are still reversed but ids stay as previously).
* Introduce RowMetadata::moveAfter to move columns around in row metadata.
* Add Junit test for moveAfter()
* (review).
(cherry picked from commit 43f59be)
https://jira.talendforge.org/browse/TDP-5538
> fix(TDP-5538): Fix breaking change in column ids. (#1270)

- dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
- dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
**DataSetServiceTest.java**
Type CITY has been removed. Semantic types count goes from 7 to 6.
**SchemaAnalysisTest.java**
As seen with the DQ team, 6.0.0-SNAPSHOT has been republished. The way the library attributes the score based on the metadata has evolved. This result is totally consistent ; our test has to be fixed.
**TransformationServiceTest.java**
Type CITY has been removed. Semantic types count goes from 7 to 6.
> fix: dq tests

- dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/UpgradeService.java
- dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/model/UpgradeTask.java
* create a new POST_STARTUP upgrade task target.
* UpgradeService will run all POST_STARTUP upgrade tasks when application will be ready to service requests.
https://jira.talendforge.org/browse/TDP-4926
> fix(TDP-4926): compute new SRMD should be done when application is ready

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
-  revert edea36043b204af6b287c4877f8393e9097ecb53
- cannot use ActionsUtils.createNewColumn because rowMetadata insertion is always on context column id (instead of last column id in ActionUtils)
https://jira.talendforge.org/browse/TDP-5254
https://jira.talendforge.org/browse/TPS-2360
> fix(TDP-5254): revert the reverse of additional columns list

- dataprep-backend/pom.xml
Revert "feat(TDP-5167): Update Data Quality libraries to 4.0.4-SNAPSHOT (#1129)"
This reverts commit 8980b04
https://jira.talendforge.org/browse/TDP-5167
> feat(TDP-5167): Revert Version Update of Data Quality libraries

- dataprep-async-api/src/main/java/org/talend/dataprep/async/AsyncExecution.java
- dataprep-async-runtime/src/main/java/org/talend/dataprep/async/SimpleManagedTaskExecutor.java
https://jira.talendforge.org/browse/TDP-5687
>  fix(TDP-5687): Preparation suddenly inaccessible and dataset row count back to 0

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java
- dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
- dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java
* empty cells don't generate hash
* add TI
* rename action to "Hash data"
https://jira.talendforge.org/browse/TDP-5726
> fix(TDP-5726): fix hash action

- dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
- dataprep-backend/pom.xml
* SpringSleuthSettersConfiguration from daikon need sleuth 1.2.5.RELEASE (provided in spring cloud Dalston SR4)
https://github.com/spring-projects/spring-cloud/wiki/Spring-Cloud-Dalston-Release-Notes#dalstonsr4
https://jira.talendforge.org/browse/TDP-5771
> fix(5771): Update spring cloud version to Dalston.SR4

- dataprep-webapp/src/app/services/playground/playground-service.js
https://jira.talendforge.org/browse/TDP-5790
> fix(TDP-5790): content is loaded twice when loading a preparation

- dataprep-webapp/src/app/services/playground/playground-service.js
https://jira.talendforge.org/browse/TDP-5795
> fix(TDP-5795): details are loaded twice when loading a preparation

- dataprep-api/src/main/resources/application.properties
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
- dataprep-dataset/src/main/resources/application.properties
- dataprep-preparation/src/main/resources/application.properties
- dataprep-preparation/src/test/resources/application.properties
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
- dataprep-transformation/src/main/resources/application.properties
> chore: protect our connection pools by autoclosing DataSet

- dataprep-backend/pom.xml
* previous upgrade of spring-cloud-dependencies to Edgware.SR3 cause two versions of many spring-cloud-xxx libraries which cause issues with onPrem bundle.
prerequisite : https://github.com/Talend/daikon/pull/384
https://jira.talendforge.org/browse/TDP-4665
> fix(TDP-4665): downgrade spring cloud version to Dalston.SR5

- dataprep-backend-service-parent/pom.xml
- dataprep-backend-service/pom.xml
- dataprep-backend/pom.xml
* override the provided version from spring-cloud-dependencies (1.2.6.RELEASE) with a spring-cloud-sleuth-dependencies BOM (should be declared before spring-cloud-dependencies)
* we can't upgrade the spring-cloud dependencies due to spring-cloud-stream that should be Chelsea.SR2
https://jira.talendforge.org/browse/TDP-4665
> fix(TDP-4665): set spring-cloud-sleuth-dependencies to 1.3.0.RELEASE

- dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
* A new column filled with a sequence have Integer as type
https://jira.talendforge.org/browse/TDP-5595
> chore(TDP-5595) Set Type as Integer for new column when the mode is Sequence

- dataprep-webapp/src/app/services/filter/manager/filter-manager-service.js
https://jira.talendforge.org/browse/TDP-5865
> fix(TDP-5865): content is loaded twice when removing all filters after a fetch more

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
* Pipeline transformer now creates a span with constant name (prep id and argument in tags).
(no jira)
> chore(perf): Improve pipeline zipkin span names

- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformer.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/StepNode.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/UpdatedStepVisitor.java
* Use parent step output metadata iso. step's input metadata.
* Remove unused method in step node to avoid confusion.
(cherry picked from commit e3a4dbf3fbba8e4c5f7111c9a372829ee8934bcd)
https://jira.talendforge.org/browse/TDP-5864
> fix(TDP-5864): Fix missing call to parent's step metadata

- dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
Avoid useless (and costly) usage of `IOUtils.toString` before Jackson object mapping.
note: `Defaults#convertResponse(ObjectMapper mapper,
TypeReference<T> typeReference, Function<Exception, T> errorHandler` already use InputStream as parameter of `ObjectMapper#readValue` method
> chore: Default#convertResponse avoid toString before read JSON value

- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
* apply the same strategy than TDP-5873/75 - publish event after unlock the initial lock because publish event will create a new lock with the technical user
https://jira.talendforge.org/browse/TDP-5891
> fix(TDP-5891): publish DatasetUpdateEvent after unlock

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationDetailsDTO.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java
* Re-add missing row metadata in preparation details for Spark jobs.
https://jira.talendforge.org/browse/TDP-5888
> fix(TDP-5888): Add missing metadata in preparation details

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
* Use the executeSampleStrategy any time, to cache when we send a HTTP 202 to StreamingResponseBody otherwise.
* Fix the accept of OptimizedExportStrategy
* Fix the ApplyPreparationToContentStrategy
https://jira.talendforge.org/browse/TDP-5898
> fix(TDP-5898) Previous preparation results are no longer used

- dataprep-backend-common/src/main/java/org/talend/dataprep/dataset/adapter/Dataset.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/conversion/DataSetMetadataBeanConversion.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/BackgroundAnalysis.java
Manage records number in legacy dataset properties.
Since TDP-5822 (dc04617), we can't fetch the dataset content to analyse and set the dataset records number.
> LocalStoreLocation and JobLocation stores Dataset content and Location in Dataset properties 
(Dataset Catalog) as JSON.
https://jira.talendforge.org/browse/TDP-5891
> fix(TDP-5891): Provide dataset rows value when listing TCOMP datasets

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
This reverts commit f3c624c77118163c3bacb96fbf4b5313f9e660c9.
> Revert "fix(TDP-5898) Previous preparation results are no longer used (#1486)"

- dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/Injections.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
* Add OS implementation in DefaultOwnerInjection
[refactoring]
* OwnerInjection is now an interface to allow OS / EE differences.
* Expose an internal method of ACL service to ease role set.
[misc]
* Removes unused owner injection at API level.
https://jira.talendforge.org/browse/TDP-5895
> fix(TDP-5895): Fix wrong owner in shared preparations

- pom.xml
This issue occurred in the CI https://issues.apache.org/jira/browse/SUREFIRE-1479 (fixed in the 2.22.0 version)
NO JIRA
> chore: update maven surefire and failsafe plugin version to 2.22.0

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/Type.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
* in order to check the joined column from a lookup, we have to update the dataset schema with all previous lookup columns.
[misc]
* Use Lookup Parameters enumeration instead of String to avoid duplication
* Import preparation returns 406 NOT ACCEPTABLE (instead of 404 NOT FOUND) if the dataset format is not the expected one
* revamp some log messages
https://jira.talendforge.org/browse/TDP-5954
> fix(TDP-5954): Update the dataSet schema during preparation import

- dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
* Remove use of Flux to prevent non traced requests.
https://jira.talendforge.org/browse/TDP-5977
> fix(TDP-5977): Fix missing Zipkin spans for preparation list operation

- dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
- dataprep-api/src/test/java/org/talend/dataprep/helper/VerboseMode.java
- dataprep-test-api/README.md
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
This PR goal is to refine the mecanism which allows to choose what to log about HTTP requests / responses during Integration Tests execution.
The CI jobs may be impacted.
No Jira linked.
> chore(Integration Tests): refine requests logging

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Preparation.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationDTO.java
- dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationListItemDTO.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparation.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/util/SortAndOrderHelperTest.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationEventUtilTest.java
[POJO changes]
* Add dataSetName in Preparation POJO.
* Deprecate dataSetId.
* Adapt DTOs to include dataset name.
[Data set name update]
* If dataset name misses in list operation, performs a look up to dataset service.
* Create a preparation also add linked dataset name.
* Add dataset name update operation in preparation listener for kafka event.
https://jira.talendforge.org/browse/TDP-5968
> fix(TDP-5968): Migrate to dataset name in preparation

- dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/executor/MaintenanceScheduler.java
- dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MaintenanceSchedulerTest.java
* use a TaskExecutor in order to run asynchronously the first maintenance tasks iteration
https://jira.talendforge.org/browse/TDP-5734
> fix(TDP-5734): first execution of maintenance tasks should be async

- dataprep-webapp/package.json
- dataprep-webapp/yarn.lock
0.202.0 seems to break the build. 
> fix: downgrade cmf plugin to save the build

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationListItemDTO.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparation.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/preparation/store/PersistentPreparationTest.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
[fix]
* Correctly copy dataset name from preparation during merge with previous preparation.
* Update unit test to follow change.
[misc]
* Remove unused top level data set name in PreparationListItemDTO.
https://jira.talendforge.org/browse/TDP-5968
> fix(TDP-5968): Fix missing dataset name after preparation update

- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetReader.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingWorkbookReader.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetTest.java
* use ReadOnlySharedStringsTable (lighter memory print when you want to only read a XLSX file) instead of SharedStringsTable (for read/write operation)
https://jira.talendforge.org/browse/TDP-5908
> fix(TDP-5908): fix out of memory in xlsx loading

- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetReader.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingWorkbookReader.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/schema/xls/streaming/StreamingSheetTest.java
* use ReadOnlySharedStringsTable (lighter memory print when you want to only read a XLSX file) instead of SharedStringsTable (for read/write operation)
https://jira.talendforge.org/browse/TDP-5908
> fix(TDP-5908): fix out of memory in xlsx loading, backport on summer 18

- dataprep-async-runtime/src/main/java/org/talend/dataprep/async/conditional/PreparationExportCondition.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/CachedExportStrategyTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategyTest.java
* fix(TDP-5961): fix fetch more
* fix incorrect Integration Test for TDP-5733
* base the fetch more on the correct sample, a filtered dataset generated by the FilterSamplingPipeline
* apply the correct export strategy, that is PreparationSampleExportStrategy
* fix(TDP-5961): flush OutputStream (otherwise leads to issues on Windows)
* fix(TDP-5961): restore previous behavior when from == FILTER
* re-enable use of CachedExportStrategy
* enable asynchronism even if from == FILTER
* clean code
* fix(TDP-5961): add and fix unit tests
* Add comment (FetchMore.feature, CacheExportStrategy.java)
* Remove attribute declare in parent class (ApplyPreparationToContentStrategy.java)
* Remove unnecessary call to exportParametersUtil.populateFromPreparationExportParameter (TransformationService.java) …
> fix(TDP-5961): fix fetch more (#1532)

- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
Fix regression on export, introduced by a commit on 2018-08-24.
> fix(export): do not close dataset stream too early

- dataprep-api/src/main/java/org/talend/dataprep/api/service/AppSettingsAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/VersionServiceAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsService.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/ImportTypesConfigurer.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActionsProvider.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/DatasetViewsProvider.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/version/DatasetVersionSupplier.java
- dataprep-api/src/main/java/org/talend/dataprep/configuration/DatasetProxyConfiguration.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DatasetConfiguration.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
- dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java
* Add onePerRequest filter which load properties from config service regarding the current tenant
* Add Prototype scope for bean which use @Value on dataset.service.* properties
* Add config service properties in catalog properties file
https://jira.talendforge.org/browse/TDP-5791
> feat(TDP-5791): add spring property source bind on config service

- dataprep-backend-common/src/test/java/org/talend/dataprep/dataset/adapter/DatasetTest.java
- dataprep-backend-common/src/test/resources/org/talend/dataprep/dataset/adapter/dataset-catalog-sample.json
- dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
Data Catalog has implemented the certification state for a dataset and values are not in uppercase as expected so we have to be insensitive for mapping.
* fix deserialize issue of `org.talend.dataprep.dataset.adapter.Dataset$CertificationState` from String "none" -> declared Enum values: [NONE, CERTIFIED, PENDING]
https://jira.talendforge.org/browse/TDP-5791
> fix(TDP-5791): accept case insensitive enums for jackson mapping

- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
- dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
- dataprep-test-api/src/test/resources/features/CreateNewColumnActionTest.feature
- dataprep-test-api/src/test/resources/features/DatasetCache.feature
- dataprep-test-api/src/test/resources/features/DeleteAllEmptyColumnsAction.feature
- dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
- dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
- dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
- dataprep-test-api/src/test/resources/features/Filter.feature
- dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
- dataprep-test-api/src/test/resources/features/SmokeTest.feature
- dataprep-test-api/src/test/resources/features/SplitActionTest.feature
- dataprep-test-api/src/test/resources/features/TrimActionTest.feature
Remove datasetName from the parameters of the export in integration tests.
> Export parameters should contains the preparation id or the dataset id (https://github.com/Talend/data-prep/blob/master/dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParameters.java#L40)
fix the `DatasetCache.feature` (recently updated with the TDP-5926 in order to check the update of the dataset for a preparation).
> chore: export preparation parameters ti

- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
* Improve dataset name robustness when a preparation is missing or not accessible.
(no jira)
> chore(cloud): Improve dataset name robustness

- dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
https://jira.talendforge.org/browse/TDP-6198
> feat(TDP-6198) : Delete dataset step doesn't remove it from the context

- dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/commands/DataSetGetSchema.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversionTest.java
- dataprep-backend-service/src/test/resources/org/talend/dataprep/dataset/adapter/dataset_payload_example.json
* remove useless DataSetGetShema onError instruction
* Add fields in Dataset / Datastore catalog entity
* Update Dataset Bean conversions
https://jira.talendforge.org/browse/TDP-6353
> fix(TDP-6353): update dataset / DatasetDTO conversion

- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
* Adding lookup_ds_id parameter in lookup action step
https://jira.talendforge.org/browse/TDP-6349
> fix(TDP-6349) : TI fails in CI

- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/XlsUtils.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/schema/xls/streaming/StreamingWorkbookReader.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/schema/xls/XlsUtilsTest.java
* Disable DTD validation for XMLEventReader and XMLEventStreamer
* Disable external entities for XMLEventReader and XMLEventStreamer
(Backport from master)
https://jira.talendforge.org/browse/TDP-6725
> fix(TDP-6725): prevent XXE on XLSX dataset parsing

- dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/CreateChildFolder.java
- dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/CreateRootFolder.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/ApiServiceTestBase.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
- dataprep-api/src/test/java/org/talend/dataprep/api/service/SearchAPITest.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/FolderRepository.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
- dataprep-backend-service/src/test/java/org/talend/dataprep/folder/store/AbstractFolderTest.java
- dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/BasePreparationTest.java
- dataprep-preparation/src/test/java/org/talend/dataprep/preparation/test/PreparationClientTest.java
- dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceBaseTest.java
- dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_1_2_0_PE/AddAllPreparationsTaskToHome.java
- dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_1_2_0_PE/AddAllPreparationsToHomeTest.java
https://jira.talendforge.org/browse/TDP-6717
https://jira.talendforge.org/browse/TDP-6290
https://jira.talendforge.org/browse/TDP-3422
> fix(TDP-6717): User can access to some preparations without permissions (on the same tenant)

- dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
* update the logging level from info to warn when the head step of a preparation is inconsistent.
* inline appendStepToHead method in order to avoid to call this method outside replace history method.
* Add null check when we are trying to get a PreparationAction by it's id (like in master)
https://jira.talendforge.org/browse/TDP-6822
> fix(TDP-6822): ensure preparation consistency before rewrite history.

- dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/Type.java
- dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
- dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
(cherry picked from commit be4d0780ae5137b40ce40333158bb902bfb7ae1b)
https://jira.talendforge.org/browse/TDP-5954
> fix(TDP-7086): Update the dataSet schema during preparation import 
