dataprep-backend-common/pom.xml
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/HeadersContentHandler.java
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/HtmlFormatGuesser.java
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/HtmlSchemaParser.java
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/HtmlSerializer.java
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/ValuesContentHandler.java
dataprep-backend-common/src/test/java/org/talend/dataprep/schema/html/HtmlFormatTest.java
dataprep-backend/pom.xml

Changing html parser (finally use Tika) improve Html parsing performance.

TDP-1520 salesforce import performance improvement

---

dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_actions.json
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/metadata/math/ExtractNumber.java
dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/metadata/math/ExtractNumberTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions_string.json

using common BigDecimalParser from daikon

TDP-490 extract numbers with big decimal parser

---

dataprep-backend-common/src/main/java/org/talend/dataprep/schema/html/SimpleValuesContentHandler.java

Signed-off-by: olivier lamy <olamy@apache.org>

TDP-1792 improve rendering (simply trim as jira export add plenty of spaces CR LF)

---

dataprep-webapp/package.json

Fix build Gulp task according to that [comment](https://github.com/miickel/gulp-angular-templatecache/issues/124#issuecomment-226740212)

Update package.json in order to fix build

---

.editorconfig

Introduce #188 by providing an .editorconfig file for JS

[WIP] .editorconfig

---

dataprep-webapp/config/webpack.config.js
dataprep-webapp/package.json
dataprep-webapp/pom.xml

Lint step must be a warn rather than an error
Frontend version should fit to Backend ones
Docker image was updated

TDP-2312: Webpack

---

dataprep-webapp/src/app/components/dataset/list/_dataset-list.scss
dataprep-webapp/src/app/components/home/_home.scss

Revert "TDP-2294: Fix loading spinner icon display for edge and others"

---

dataprep-webapp/src/app/components/suggestions-stats/column-profile/column-profile-controller.spec.js
dataprep-webapp/src/app/components/transformation/form/date/transformation-date-param-controller.js
dataprep-webapp/src/app/components/transformation/form/date/transformation-date-param-directive.js
dataprep-webapp/src/app/components/transformation/form/date/transformation-date-param.html
dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param-directive.js
dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param.html
dataprep-webapp/src/app/components/validation/is-datetime-validation-directive.js
dataprep-webapp/src/app/components/validation/is-datetime-validation-directive.spec.js
dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider-controller.js
dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider-controller.spec.js
dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider-directive.spec.js
dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider.html
dataprep-webapp/src/app/components/widgets/datetimepicker/widget-datetimepicker-directive.js
dataprep-webapp/src/app/components/widgets/datetimepicker/widget-datetimepicker-directive.spec.js
dataprep-webapp/src/app/services/filter/filter-service.js
dataprep-webapp/src/i18n/en.json

Use common datetime pattern "YYYY-MM-DD HH:mm" to be displayed and selected by datetimepicker widget

TDP-2470: Use common datetime pattern

---

dataprep-webapp/src/app/components/recipe/_recipe.scss
dataprep-webapp/src/app/components/recipe/knot/recipe-knot-component.js
dataprep-webapp/src/app/components/recipe/recipe-component.spec.js
dataprep-webapp/src/app/components/recipe/recipe-controller.js
dataprep-webapp/src/app/components/recipe/recipe-module.js
dataprep-webapp/src/app/components/recipe/recipe.html
dataprep-webapp/src/app/components/widgets/list-item-handler/_list-item-handler.scss
dataprep-webapp/src/app/components/widgets/list-item-handler/list-item-handler-component.js
dataprep-webapp/src/app/components/widgets/list-item-handler/list-item-handler-component.spec.js
dataprep-webapp/src/app/components/widgets/list-item-handler/list-item-handler.html
dataprep-webapp/src/app/components/widgets/widget-module.js
dataprep-webapp/src/app/css/base/_typography.scss
dataprep-webapp/src/app/css/components/_button.scss
dataprep-webapp/src/app/index.scss
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js
dataprep-webapp/src/app/services/preparation/preparation-service.js
dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.js
dataprep-webapp/src/app/services/preparation/rest/preparation-rest-service.spec.js
dataprep-webapp/src/i18n/en.json

I increased the button click area size because buttons are too small.

feature/TDP-2485 Reorder only with arrows

---

dataprep-webapp/src/app/components/lookup/grid/header/_lookup-datagrid-header.scss

TDP-2538: Increase font-size for `add to lookup`checkbox

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/_actions-list.scss

TDP-2539: Increase click area for simple action trigger

---

dataprep-webapp/src/app/components/recipe/_recipe.scss

TDP-2482: Remove steps borders

---

dataprep-webapp/src/app/components/widgets/quality-bar/_quality-bar.scss
dataprep-webapp/src/app/components/widgets/quality-bar/quality-bar.html
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-controller.js
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-controller.spec.js
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-directive.spec.js

TDP-2557: Fix width for quality bar items with width less than 10%

---

dataprep-webapp/src/app/components/recipe/_recipe.scss
dataprep-webapp/src/app/components/widgets/list-item-handler/_list-item-handler.scss

TDP-685 Revert borders, change cursor and drag&drop placeholder style

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java

* Include original data set metadata in empty preparation to prevent multiple cycles in UI.

TDP-2614: Fix too many preparation call (especially in big datasets)

---

dataprep-api/src/test/resources/org/talend/dataprep/api/service/export/export_type.json
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/csv/CSVSchemaParser.java
dataprep-backend-common/src/main/java/org/talend/dataprep/schema/csv/SeparatorAnalyzer.java
dataprep-backend-common/src/main/resources/org/talend/dataprep/messages.properties
dataprep-backend-common/src/test/java/org/talend/dataprep/schema/csv/CSVSchemaParserTest.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVFormat.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/csv.json
dataprep-webapp/src/app/services/state/parameters/parameters-state-service.js
dataprep-webapp/src/app/services/state/parameters/parameters-state-service.spec.js

* Add | as separator for import and export.
* Unit test updates.

TDP-2661: Add | as separator for import and export.

---

dataprep-webapp/src/app/components/recipe/_recipe.scss

TDP-2629: Fix IE11 diplay for recipe bullets

---

dataprep-webapp/src/app/components/widgets/quality-bar/_quality-bar.scss

**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
The height of the dropdown trigger is 0px in Safari
The placement has been changed.
**Does this PR introduce a breaking change?**

TDP-2680: change quality bar elements placement

---

dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend-common/src/test/resources/application.properties
dataprep-backend/pom.xml
dataprep-dataset/src/main/resources/application.properties
dataprep-dataset/src/main/resources/application_docker.properties
dataprep-dataset/src/test/resources/application.properties

**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
- DQ lib version is 1.5.3
- DQ indexes are extracted in ${java.io.tmpdir}/org.talend.dataquality.semantic
- DQ lib version is 1.5.4-SNAPSHOT
- New config parameters *dataquality.indexes.file.location* is used, default is still ${java.io.tmpdir}/org.talend.dataquality.semantic
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:

Update DQ lib to 1.5.4-SNAPSHOT

---

dataprep-webapp/.babelrc
dataprep-webapp/package.json
dataprep-webapp/src/app/components/datagrid/header/_datagrid-header.scss

https://jira.talendforge.org/browse/TDP-2497
Dropdowns have overflow hidden and submenu are not shown
Dropdowns submenu are shown

TDP-2497: fix hidden bootstrap overflow

---

dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.js
dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.spec.js
dataprep-webapp/src/app/components/widgets/search/widget-search-input-directive.js

https://jira.talendforge.org/browse/TDP-2679
Sorry for this diff, I changed the indentation of the touched files... You might want to see a proper diff using your favorite IDE

TDP-2679: escape keydown uniformation in all modals

---

dataprep-webapp/src/app/components/widgets/editable-text/_editable-text.scss
dataprep-webapp/src/app/components/widgets/editable-text/editable-text.html

https://jira.talendforge.org/browse/TDP-2461

TDP-2461: fix buttons style

---

dataprep-webapp/package.json

https://jira.talendforge.org/browse/TDP-2844
It is a known issue at the version 1.3.7 of ng-sortable : https://github.com/a5hik/ng-sortable/issues/347

TDP-2844: use only the version 1.3.6 of ng-sortable

---

dataprep-webapp/package.json

https://jira.talendforge.org/browse/TDP-2908

TDP-2908: remove phantomjs-polyfill-object-assign

---

dataprep-webapp/package.json

Chore: Update react components and icons

---

dataprep-webapp/src/app/components/export/export.html

https://jira.talendforge.org/browse/TDP-2935

TDP-2935: fix button semantic and submit button value

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/TypeUtils.java
dataprep-backend-common/src/main/java/org/talend/dataprep/dataset/StatisticsAdapter.java
dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend/pom.xml
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/Application.java

https://jira.talendforge.org/browse/TDP-2454
- update DQ dependency version
- use CategoryRegistryManager instead of enum where possible
- correct empty domain handling
- make docker command on one line for MAC compatibility

TDP-2454: adapt to DQ 1.5.5 with DQCategory

---

dataprep-webapp/src/assets/config/app-settings.json

feat(TDP-2802): change prep list field names

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-container.js
dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-controller.js
dataprep-webapp/src/assets/config/app-settings.json

None
Upgrade libs and update icons names

feat: Upgrade react-talend-bootstrap, react-talend-components, talend-icons

---

dataprep-webapp/src/app/components/widgets-containers/layout/layout-container.js
dataprep-webapp/src/app/components/widgets-containers/layout/layout.scss

No scroll
Vertical scroll when height is lower than list
Horizontal scroll when content is lower than 1330px

fix(TDP-2802): enable scroll on prep page

---

dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-controller.js
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-controller.spec.js
dataprep-webapp/src/app/services/transformation/transformation-utils-service.js
dataprep-webapp/src/app/services/transformation/transformation-utils-service.spec.js

https://jira.talendforge.org/browse/TDP-2863

fix(TDP-2938 TDP-2863): suggestion --> suggestions

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITestClient.java
dataprep-backend-service/src/main/java/org/talend/dataprep/api/preparation/json/PreparationDetailsJsonSerializer.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
dataprep-preparation/src/test/resources/org/talend/dataprep/preparation/service/actions/append_make_line_header.json
dataprep-preparation/src/test/resources/org/talend/dataprep/preparation/service/preparation_1234.json

https://jira.talendforge.org/browse/TDP-2796
* Adds a "allowDistributedRun" in preparation details (if "false", at least one step can't run in distributed environments).
* Preparation -> function conversion skips non-distributable actions.
* Adds unit tests.

feat(TDP-2796): Add flag for distributable preparations

---

dataprep-webapp/package.json

fix(package): react-talend-components version to a stable one

---

dataprep-webapp/config/sass.conf.js
dataprep-webapp/config/webpack.config.js
dataprep-webapp/karma.conf.js

Reverts Talend/data-prep#341 since it blocks Webpack

Revert "feat: update webpack sass loader config"

---

dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-controller.js
dataprep-webapp/src/assets/config/app-settings.json
dataprep-webapp/src/mocks/Settings.mock.js

https://jira.talendforge.org/browse/TDP-2704
The app settings for side panel are not aligned with the others on the actions list.
The actions list are now only action ids 

fix(TDP-2704): change side panel settings to fit the actions settings

---

dataprep-webapp/package.json

fix(TDP-2048 TDP-2965) : Fix react-talend-forms version

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/Concat.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractCompareAction.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/CompareDates.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ModifyDate.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/AbstractFillWith.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/AbstractMathOneParameterAction.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/ChangeNumberFormat.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/NumericOperations.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Substring.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/CompareDatesTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/SubstringTest.java

https://jira.talendforge.org/browse/TDP-2943

fix(TDP-2943/backend) Fix additional missing i18n labels.

---

dataprep-webapp/src/app/components/import/import-controller.js
dataprep-webapp/src/app/components/import/import-controller.spec.js
dataprep-webapp/src/app/components/import/import.html
dataprep-webapp/src/app/components/import/import.scss
dataprep-webapp/src/app/services/import/import-rest-service.js
dataprep-webapp/src/app/services/import/import-rest-service.spec.js
dataprep-webapp/src/app/services/import/import-service.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.spec.js

https://jira.talendforge.org/browse/TDP-2966

feature(TDP-2048/TDP-2966): tcomp form triggers

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Action.java

https://jira.talendforge.org/browse/TDP-2964

fix(TDP-2964/backend) Allow write operation on DataSetRowAction

---

dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type.json

https://jira.talendforge.org/browse/TDP-3074

fix(TDP-3074/backend): Take DQ category as is (no try to change case).

---

dataprep-webapp/src/assets/config/app-settings.json
dataprep-webapp/src/mocks/Settings.mock.js

Icon: talend-cluster
Icon: talend-datastore

feat: change dataset menu icon

---

dataprep-webapp/src/app/components/widgets-containers/preparation-list/preparation-list-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/preparation-list/preparation-list-controller.js
dataprep-webapp/src/app/services/folder/folder-service.js
dataprep-webapp/src/app/services/folder/folder-service.spec.js
dataprep-webapp/src/app/services/state/inventory/inventory-state-service.js
dataprep-webapp/src/app/services/state/inventory/inventory-state-service.spec.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
dataprep-webapp/src/assets/config/app-settings.json
dataprep-webapp/src/mocks/Settings.mock.js

refactor(TDP-2802): merge folder and prep actions

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/DefaultLookupRowMatcher.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datablending/LookupTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/actions/PrototypeScope.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/actions/Providers.java
dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/actions/ProvidersTest.java

e.g. https://jira.talendforge.org/browse/TDP-3078

fix(TDP-3078/actions): allow creation of non singleton LookupRowMatcher

---

dataprep-webapp/package.json

Angular 1.6.0 has been resolved by NPM
Angular 1.5.9 has been resolved by NPM since I fixed the version to avoid err
https://github.com/angular/angular.js/blob/master/CHANGELOG.md

fix angular version

---

dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/Item.java
dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/SelectParameter.java
dataprep-backend-common/src/main/java/org/talend/dataprep/parameters/TextItem.java
dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/api/action/parameters/SelectParameterTest.java

https://jira.talendforge.org/browse/TDP-3008
* Adds missing support for item with a value but no label translation.
* Use this in job location list.
* Unit test fix (on non translated items).

fix(TDP-3008/backend): Fix support for non translated item list

---

dataprep-webapp/src/app/components/dataset/list/dataset-list.html
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list-component.spec.js
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list-controller.js
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list-controller.spec.js
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list.html
dataprep-webapp/src/app/services/state/lookup/lookup-state-service.js
dataprep-webapp/src/app/services/state/lookup/lookup-state-service.spec.js
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-3087

fix(TDP-3087): fix dataset management in lookup

---

dataprep-webapp/src/app/components/recipe/recipe-component.spec.js

https://jira.talendforge.org/browse/TDP-2936
Fix keyword in order to compile without errs

fix(TDP-2936) fix compilation err

---

dataprep-webapp/src/app/components/dataset/list/dataset-list-controller.js
dataprep-webapp/src/app/components/home/dataset/react-home-dataset-container.js
dataprep-webapp/src/app/components/home/dataset/react-home-dataset-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
dataprep-webapp/src/app/services/dataset/dataset-service.js
dataprep-webapp/src/app/services/dataset/dataset-service.spec.js
dataprep-webapp/src/app/services/dataset/list/dataset-list-service.js
dataprep-webapp/src/app/services/dataset/list/dataset-list-service.spec.js
dataprep-webapp/src/app/services/folder/folder-service.js
dataprep-webapp/src/app/services/folder/folder-service.spec.js
dataprep-webapp/src/app/services/state/inventory/inventory-state-service.js
dataprep-webapp/src/app/services/state/inventory/inventory-state-service.spec.js
dataprep-webapp/src/app/services/state/state-service.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js
dataprep-webapp/src/app/settings/actions/inventory-actions-service.js
dataprep-webapp/src/app/settings/actions/inventory-actions-service.spec.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js
dataprep-webapp/src/assets/config/app-settings.json
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/mocks/Settings.mock.js

TDP-2802: add dataset list edit action

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/SimpleFilterService.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/filter/SimpleFilterServiceTest.java

e.g. https://jira.talendforge.org/browse/TDP-2819

fix(TDP-2819): createValidPredicate now exclude empty values

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
dataprep-webapp/src/app/services/dataset/dataset-service.js
dataprep-webapp/src/app/services/dataset/list/dataset-list-service.js
dataprep-webapp/src/app/services/dataset/list/dataset-list-service.spec.js
dataprep-webapp/yarn.lock

Datasets icons management in new homepage

feat(TDP-2802): dataset icons

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGet.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationController.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceBaseTests.java

https://jira.talendforge.org/browse/TDP-2816

feat(TDP-2816): export history

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/dataset/progress/_dataset-progress.scss
dataprep-webapp/src/app/components/dataset/progress/dataset-progress-component.js
dataprep-webapp/src/app/components/dataset/progress/dataset-progress-component.spec.js
dataprep-webapp/src/app/components/dataset/progress/dataset-progress-module.js
dataprep-webapp/src/app/components/home/home-module.js
dataprep-webapp/src/app/components/home/react-home-component.spec.js
dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
dataprep-webapp/src/app/index.scss
dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-3137

TDP-2802: add dataset uploading progress bar

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

fix(TDP-2802): update versions

---

dataprep-webapp/src/app/components/widgets-containers/layout/layout.scss

https://jira.talendforge.org/browse/TDP-3148

fix(TDP-3148): list scroll on FF and Edge

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/api/ActionSettings.java
dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-controller.js

https://jira.talendforge.org/browse/TDP-2816

feat(TDP-2816): pass link property in collapsible panel action definition

---

dataprep-webapp/src/app/components/home/react-home-component.js
dataprep-webapp/src/app/components/home/react-home-controller.spec.js
dataprep-webapp/src/app/css/utils/onboarding.scss
dataprep-webapp/src/app/services/onboarding/onboarding-preparations-constants.js

https://jira.talendforge.org/browse/TDP-3142
On react route, the onboarding does not appear automatically.
If the right conditions are fulfilled, the onboarding now appears automatically.
As you can see, I changed the opacity of the onboarding selector, in order to avoid white on grey.

fix(TDP-3142): automatic onboarding on react route

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-controller.js
dataprep-webapp/yarn.lock

…unt some collapsiblePanel features
https://jira.talendforge.org/browse/TDP-2816

fix(TDP-2816): update versions

---

dataprep-webapp/src/app/components/dataset/parameters/_dataset-parameters.scss
dataprep-webapp/src/app/components/transformation/form/_transformation-form.scss

https://jira.talendforge.org/browse/TDP-3210

fix(TDP-3210): added padding and margin

---

dataprep-webapp/src/app/services/statistics/pattern-occurence.worker.js
dataprep-webapp/src/app/services/utils/text-format/text-format-service.js
dataprep-webapp/src/app/services/utils/text-format/text-format-service.spec.js

https://jira.talendforge.org/browse/TDP-3206

fix(TDP-3206): added manually special java date pattern to support dataset database date format

---

dataprep-webapp/src/app/components/recipe/_recipe.scss
dataprep-webapp/src/app/components/recipe/knot/_recipe-knot.scss

e.g. https://jira.talendforge.org/browse/TDP-3201

fix(TDP-3201): recipe glitch

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/StepDiffDelegate.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsWriter.java

https://jira.talendforge.org/browse/TDP-3229

fix(TDP-3229): put back the column ordering in CSV writing

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

https://jira.talendforge.org/browse/TDP-3246
Removed non used style

fix(TDP-3246): certify icon visibility

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

https://jira.talendforge.org/browse/TDP-3246
Removed non used style

fix(TDP-3246): remove unused style

---

dataprep-webapp/src/app/services/recipe/recipe-service.js
dataprep-webapp/src/app/services/recipe/recipe-service.spec.js
dataprep-webapp/src/app/services/state/playground/playground-state-service.js
dataprep-webapp/src/app/services/state/recipe/recipe-state-service.js
dataprep-webapp/src/app/services/state/recipe/recipe-state-service.spec.js
dataprep-webapp/src/app/services/state/state-service.js
dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-2798

feat(TDP-2798): warn user when distributed run if skipped steps

---

dataprep-webapp/docker/Dockerfile

https://jira.talendforge.org/browse/TDP-3165

fixe(TDP-3165): update dataprep-webapp Dockerfile

---

dataprep-webapp/src/app/components/home/home-component.js
dataprep-webapp/src/app/components/home/home-controller.js
dataprep-webapp/src/app/components/home/home-controller.spec.js
dataprep-webapp/src/app/components/home/home-module.js
dataprep-webapp/src/app/services/state/home/home-state-service.js
dataprep-webapp/src/app/services/state/state-service.js
dataprep-webapp/src/app/services/utils/storage/storage-service.js
dataprep-webapp/src/app/services/utils/storage/storage-service.spec.js
dataprep-webapp/src/app/settings/actions/sidepanel-actions-service.js
dataprep-webapp/src/app/settings/actions/sidepanel-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-3207

feat(TDP-3207): panel dock save

---

dataprep-webapp/src/app/components/transformation/form/transformation-form-controller.js
dataprep-webapp/src/app/services/onboarding/onboarding-module.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
dataprep-webapp/src/app/services/utils/storage/storage-service.js
dataprep-webapp/src/app/services/utils/storage/storage-service.spec.js

https://jira.talendforge.org/browse/TDP-727

feat(TDP-727): move localStorage to StorageService

---

dataprep-webapp/src/app/services/filter/filter-service.js
dataprep-webapp/src/app/services/filter/filter-service.spec.js

https://jira.talendforge.org/browse/TDP-3317

fix(TDP-3317): date filter match

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java

fix(icon): dataset/preparation create icon is now aligned with streams create icon

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViews.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-webapp/src/app/components/transformation/form/transformation-form-controller.js
dataprep-webapp/src/app/services/dataset-workflow/upload-workflow-service.js
dataprep-webapp/src/app/services/dataset-workflow/upload-workflow-service.spec.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js
dataprep-webapp/src/app/settings/actions/menu-actions-service.js
dataprep-webapp/src/app/settings/actions/menu-actions-service.spec.js
dataprep-webapp/src/app/settings/settings-actions-service.js
dataprep-webapp/src/app/settings/settings-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-3141

TDP-3141: add ctrl+click management on inventory list

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ModifyDate.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/TimestampToDate.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Absolute.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/AbstractRound.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/ChangeNumberFormat.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/DeleteNegativeValues.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/ExtractNumber.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/NumericOperations.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/SimpleFilterService.java
dataprep-backend-common/src/main/java/org/talend/dataprep/util/NumericHelper.java
dataprep-backend-common/src/test/java/org/talend/dataprep/util/NumericHelperTest.java

https://jira.talendforge.org/browse/TDP-3006

bugfix(TDP-3006/backend): Use non-exception based check for numeric values.

---

dataprep-webapp/src/app/components/filter/bar/_filter-bar.scss
dataprep-webapp/src/app/components/filter/bar/filter-bar-directive.spec.js
dataprep-webapp/src/app/components/filter/bar/filter-bar.html
dataprep-webapp/src/app/components/filter/monitor/_filter-monitor.scss
dataprep-webapp/src/app/components/filter/monitor/filter-monitor-directive.spec.js
dataprep-webapp/src/app/components/filter/monitor/filter-monitor.html
dataprep-webapp/src/app/components/filter/search/_filter-search.scss

https://jira.talendforge.org/browse/TDP-3323

feat(TDP-3323): brought contains filter back to the left

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/suggestions-stats/actions-list/_actions-list.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
dataprep-webapp/src/i18n/en.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-2804
A contribution was brout to https://github.com/Talend/sunchoke

feat(2804): actions new style

---

dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java

https://jira.talendforge.org/browse/TDP-3027

TDP-3027: Execution user name

---

dataprep-backend/pom.xml
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java

e.g. https://jira.talendforge.org/browse/TDP-3308

prefix mongo collections with tdp

---

dataprep-webapp/src/app/components/datagrid/_datagrid.scss
dataprep-webapp/src/app/components/datagrid/editor/talend-editor.js
dataprep-webapp/src/app/components/datagrid/header/_datagrid-header.scss
dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
dataprep-webapp/src/app/components/datagrid/index-header/_datagrid-index-header.scss
dataprep-webapp/src/app/components/datagrid/index-header/datagrid-index-header.html
dataprep-webapp/src/app/components/lookup/grid/_lookup-datagrid.scss
dataprep-webapp/src/app/components/lookup/grid/header/_lookup-datagrid-header.scss
dataprep-webapp/src/app/components/lookup/grid/lookup-datagrid.html
dataprep-webapp/src/app/components/lookup/grid/services/lookup-datagrid-column-service.js
dataprep-webapp/src/app/components/lookup/grid/services/lookup-datagrid-column-service.spec.js
dataprep-webapp/src/app/components/widgets/quality-bar/_quality-bar.scss
dataprep-webapp/src/app/css/utils/_colors.scss

https://jira.talendforge.org/browse/TDP-2803

feat(TDP-2803): grid style

---

dataprep-webapp/docker/init_docker.sh

https://jira.talendforge.org/browse/DEVOPS-1801

Update webapp container to be able to reach API container in HTTPS

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
dataprep-webapp/src/app/index.scss

https://jira.talendforge.org/browse/TDP-3130

feat(TDP-3130): manage column size in case of long text

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetMetadata.java
dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
dataprep-backend-service/src/test/java/org/talend/dataprep/util/SortAndOrderHelperTest.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

https://jira.talendforge.org/browse/TDP-3441
https://jira.talendforge.org/browse/TDP-3442

Bugfix/tdp 3441/3442 sort on name

---

dataprep-webapp/config/webpack.config.js

Include
* Dedupe plugin to avoid duplicated code in bundle
* OccurenceOrder plugin to optimise module id depending on module use
|File|Old size|New size|
|---|---|---|
|app.js|1055301|1039305|
|vendor.js|1488474|1486120|

chore: dedupe and occurrenceOrder plugins

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

https://jira.talendforge.org/browse/TDP-3437
Because of https://github.com/Talend/data-prep/pull/461

TDP-3437: Be more precise for table style to avoid style conflicts

---

dataprep-webapp/src/app/services/state/suggestions/suggestions-state-service.js
dataprep-webapp/src/app/services/state/suggestions/suggestions-state-service.spec.js

https://jira.talendforge.org/browse/TDP-2839
Because of #462

TDP-2839: align tab index to suggestion one

---

dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-3339

TDP-3339: Rename Actions to Functions

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/home/dataset/home-dataset.html
dataprep-webapp/src/app/components/home/preparation/home-preparation-container.js
dataprep-webapp/src/app/components/home/preparation/home-preparation.scss
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
dataprep-webapp/src/app/components/widgets-containers/layout/layout-container.js
dataprep-webapp/src/app/components/widgets-containers/layout/layout.scss
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-3280

feat(List): content only scroll

---

dataprep-webapp/config/webpack.config.dev.js
dataprep-webapp/config/webpack.config.js
dataprep-webapp/config/webpack.config.prod.js
dataprep-webapp/config/webpack.config.test.js
dataprep-webapp/karma.conf.js
dataprep-webapp/src/app/components/recipe/recipe-module.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-3425
No sourcemap on test run anymore

chore(TDP-3425): karma-webpack config is now merged with other configs

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java

Better handling closed streams

---

dataprep-webapp/src/app/components/datagrid/plugins/single-column-resize-plugin.js
dataprep-webapp/src/app/components/datagrid/plugins/single-column-resize-plugin.spec.js
dataprep-webapp/src/app/components/datagrid/services/datagrid-grid-service.js

https://jira.talendforge.org/browse/TDP-2909

fix(TDP-2909): single column resize

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Preparation.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

https://jira.talendforge.org/browse/TDP-3379

fix(TDP-3379): fix preparation copy + format

---

dataprep-backend-service/src/main/java/org/talend/dataprep/cache/ContentCache.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/file/FileSystemContentCache.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/file/FileSystemContentCacheJanitor.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/file/FileSystemVisitor.java
dataprep-backend-service/src/main/java/org/talend/dataprep/io/ReleasableOutputStream.java
dataprep-backend-service/src/test/java/org/talend/dataprep/cache/file/FileSystemContentCacheTest.java

https://jira.talendforge.org/browse/TDP-3190
[Monitoring]
* Allow monitor of In/OutputStream when used as return of methods.
[Cache]
* Add timing and volume monitoring to cache service operations.

feat(TDP-3390): Add usage monitoring to cache

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationList.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationSummary.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationController.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-3076
[Fix]
* Implements solution #2 in TDP-3076's proposed fixes (new Preparation format).
* Unit test for new format.
[Misc]
* Minor code format.
* Better time measure for callable operations (async).

bugfix(TDP-3076/backend): Implement performance fix for studio

---

dataprep-backend/pom.xml

No known security vulnerability in 2.5
e.g. https://jira.talendforge.org/browse/TDP-2769
No specific unit tests were added for this PR since there's already a good overall code coverage.

feature (TDP-2769) : update commons-io version to 2.5

---

dataprep-webapp/pom.xml

https://jira.talendforge.org/browse/TDP-3376

add new property inside webapp-pe pom.xml

---

dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/store/content/StrictlyBoundedInputStream.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/store/content/StrictlyBoundedInputStreamTest.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-dataset/src/main/resources/application.properties
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-dataset/src/test/resources/application.properties

* Add Unitary test
* Add a new parameter in the datasets application.properties file

feat(TDP-3114/backend): limit the size of locally uploaded dataset

---

dataprep-webapp/src/app/components/suggestions-stats/suggestions-stats-directive.js

https://jira.talendforge.org/browse/TDP-3333

feat(TDP-3333): add missing nginject

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
dataprep-api/src/main/resources/application.properties
dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java

https://jira.talendforge.org/browse/TDP-3456

bugfix(TDP-3456): correct bug that limit preparation listing to 32

---

dataprep-actions/src/test/java/org/talend/dataprep/i18n/ActionsBundleTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/delete/DeleteTest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/all_line_scope_actions.json
dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_actions.json
dataprep-backend-common/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategyTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions_string.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_line_scope_actions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-3061

fix(TDP-3061): put actions label in sentence case

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/FuzzyMatching.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/MatchesPattern.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/ConcatTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSinceTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
dataprep-backend-common/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-3062
- [x The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)

fix(TDP-3062): translate missing label

---

dataprep-webapp/package.json

chore: fix extract-text-webpack-plugin version

---

dataprep-actions/pom.xml
dataprep-backend/pom.xml
dataprep-webapp/package.json
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [master]

---

dataprep-backend/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/1.1]

---

dataprep-backend/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/1.2.0]

---

dataprep-backend/pom.xml
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [maintenance/1.0]

---

dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.spec.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
dataprep-webapp/src/app/components/widgets/quality-bar/quality-bar.html
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-directive.js
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-directive.spec.js

https://jira.talendforge.org/browse/TDP-3333
WorkItem:
-add pointer cursor when mouse is over the quality bar of readonly preparation
-generalize quality bar directive

feat(TDP-3333): generalize quality bar directive

---

dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

e.g. https://jira.talendforge.org/browse/TDP-3510

fix(TDP-3510): show recipe panel

---

dataprep-api/pom.xml
dataprep-backend-service-parent/pom.xml
dataprep-backend/pom.xml
dataprep-dataset/pom.xml
dataprep-preparation/pom.xml
dataprep-transformation/pom.xml
dataprep-webapp/pom.xml
pom.xml

New profile should be used for docker build on Jenkins

Add docker-ci profile to maven build

---

dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-3192

feat(TDP-3492): remove useless request (DatasetService.getMetadata)

---

dataprep-actions/pom.xml
dataprep-backend/pom.xml
dataprep-webapp/package.json
pom.xml

DEVOPS-1729 Nexus migration: Update URLs [patch/TPS-1802]

---

dataprep-webapp/src/app/services/lookup/lookup-service.js
dataprep-webapp/src/app/services/lookup/lookup-service.spec.js

https://jira.talendforge.org/browse/TDP-3475

fix(TDP-3475): fetch dataset list when editing a lookup step

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets/typeahead/_typeahead.scss
dataprep-webapp/src/app/css/components/_app-header-bar.scss
dataprep-webapp/yarn.lock

Old version : 0.60.7
New version: 0.63.1
**Issues with this version**
* The icons in app header bar are not vertically centered, this should be fixed in the theme. I think this was introduced with the 38px header.
* The list scroll has a double scroll when we hit the bottom. This is visible in talend.surge.sh on the layout component.

feat: upgrade talend libs

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar.scss
dataprep-webapp/src/app/css/components/_app-header-bar.scss
dataprep-webapp/yarn.lock

The icons were not aligned anymore du to `react-talend-components`/`bootstrap-talend-theme`.
The header bar on the playground is still an angular component. The `<icon>`tag is not removed, we have to adapt `<icon>` line height.
Upgraded common libs
Fixed playground header icons line height to fix alignment

fix: header bar icons alignment

---

dataprep-webapp/src/app/components/export/_export.scss
dataprep-webapp/src/app/components/export/export.html
dataprep-webapp/src/app/components/playground/_playground.scss
dataprep-webapp/src/app/components/playground/header/_playground-header.scss
dataprep-webapp/src/app/components/playground/header/playground-header-component.js
dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
dataprep-webapp/src/app/components/playground/header/playground-header.html
dataprep-webapp/src/app/components/playground/playground-directive.spec.js
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/index-module.js
dataprep-webapp/src/app/index-module.spec.js
dataprep-webapp/src/app/index-route.js
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-3453

feat(TDP-3453): preparation dataset sub header

---

dataprep-webapp/src/app/components/recipe/recipe.html

e.g. https://jira.talendforge.org/browse/TDP-2876

fix(TDP-2876): drag&drop triggered only from title

---

dataprep-webapp/src/app/components/export/export.html

e.g. https://jira.talendforge.org/browse/TDP-3070

fix(TDP-3070): Click on Cancel Export modal will export the dataset though

---

dataprep-webapp/src/app/components/history-control/history-control.html
dataprep-webapp/src/app/components/playground/_playground.scss
dataprep-webapp/src/app/components/playground/header/_playground-header.scss
dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
dataprep-webapp/src/app/components/playground/header/playground-header.html

e.g. https://jira.talendforge.org/browse/TDP-3537

feat(TDP-3537): update subheader styles

---

dataprep-webapp/src/app/services/folder/folder-service.spec.js

Needs to be backported to `maintenance/2.0`

fix: use moment instead of hard coded message

---

dataprep-api/src/main/resources/application_docker.properties
dataprep-preparation/src/main/resources/application_docker.properties

https://jira.talendforge.org/browse/DEVOPS-2132

TDP-3114 Update api and preparation docker properties files

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/home/dataset/home-dataset-container.js
dataprep-webapp/src/app/components/home/dataset/home-dataset.html
dataprep-webapp/src/app/components/home/dataset/home-dataset.scss
dataprep-webapp/src/app/components/inventory/item/inventory-item.html
dataprep-webapp/src/i18n/en.json

e.g. https://jira.talendforge.org/browse/TDP-3329

feat(TDP-3329): SalesForce self-service connector - input - module selection

---

dataprep-webapp/src/app/components/playground/_playground.scss
dataprep-webapp/src/app/components/transformation/form/simple/_transformation-simple-param.scss
dataprep-webapp/src/app/components/transformation/form/simple/transformation-simple-param.html

e.g. https://jira.talendforge.org/browse/TDP-3563

fix(TDP-3563): fix safari bug

---

dataprep-webapp/src/app/components/dataset/parameters/dataset-parameters.html
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/components/transformation/form/column/transformation-column-param.html
dataprep-webapp/src/app/components/transformation/form/date/transformation-date-param.html
dataprep-webapp/src/app/components/transformation/form/regex/transformation-regex-param.html

https://jira.talendforge.org/browse/TDP-3591

TDP-3591: replace div by label for semantic reasons

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/datagrid/services/datagrid-grid-service.js
dataprep-webapp/src/app/components/datagrid/services/datagrid-grid-service.spec.js
dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview-controller.js
dataprep-webapp/src/app/components/lookup/grid/services/lookup-datagrid-grid-service.js
dataprep-webapp/src/app/components/lookup/grid/services/lookup-datagrid-grid-service.spec.js
dataprep-webapp/src/lib/slick.autocolumnsize.js
dataprep-webapp/src/mocks/SlickGrid.mock.js
dataprep-webapp/src/vendor.js

e.g. https://jira.talendforge.org/browse/TDP-111
Use [naresh-n/slickgrid-column-data-autosize](https://github.com/naresh-n/slickgrid-column-data-autosize) plugin

feat(TDP-111): Autoresize columns with double click

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/CommonActionsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/MenuActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form-controller.js
dataprep-webapp/src/app/services/preparation/preparation-service.js
dataprep-webapp/src/app/services/preparation/preparation-service.spec.js
dataprep-webapp/src/mocks/Settings.mock.js

e.g. https://jira.talendforge.org/browse/TDP-3466

fix(TDP-3466): add action in appSettings for "Create new preparation"

---

dataprep-backend-service/src/test/resources/application.properties
dataprep-dataset/src/main/resources/application.properties
dataprep-dataset/src/main/resources/application_docker.properties
dataprep-dataset/src/test/resources/application.properties

https://jira.talendforge.org/browse/TDP-3469

TDP-3469: change default folder for DQ indexes

---

dataprep-backend-service/src/test/resources/application.properties
dataprep-dataset/src/main/resources/application.properties
dataprep-dataset/src/main/resources/application_docker.properties
dataprep-dataset/src/test/resources/application.properties

Revert "TDP-3469: change default folder for DQ indexes"

---

dataprep-webapp/src/app/components/widgets/navigation-list/widget-navigation-list-directive.js

style: fix indentation

---

dataprep-webapp/src/app/index-route.js
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js
dataprep-webapp/src/app/services/utils/title/title-service.js
dataprep-webapp/src/app/services/utils/title/title-service.spec.js
dataprep-webapp/src/app/services/utils/utils-module.js

e.g. https://jira.talendforge.org/browse/TDP-3593 

fix(TDP-3593): tab title

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/DistanceConverter.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DistanceConverterTest.java

- [x ] Tests for the changes have been added (for bug fixes / features)

TDQ-13271 Convert distances : bug fix

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java

* change action name to "Switch calendar"
* add calendar names in description
* change action category to "dates"
https://jira.talendforge.org/browse/TDP-2990

feat(TDP-2990): update convert date

---

dataprep-webapp/config/webpack.config.js
dataprep-webapp/package.json
dataprep-webapp/yarn.lock

`npm test  68,08s user 2,54s system 107% cpu 1:05,97 total`
`npm test  54,69s user 1,91s system 104% cpu 54,117 total`

chore: add null-loader for tests

---

dataprep-webapp/src/app/services/search/documentation/rest/search-documentation-rest-service.js

https://jira.talendforge.org/browse/TDP-3626

fix(TDP-3626): search bar not working anymore

---

dataprep-backend/pom.xml

No Jira
Follow Spring Boot releases (Upgrade from 1.5.1 -> 1.5.2).

chores: Upgrade to Spring Boot 1.5.2

---

dataprep-webapp/package.json

chore: fix talend-ui dependencies versions (upgrade to 0.70.1)

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-3599
* Upgrade from DQ consumer lib (1.0.3 -> 1.1.0).

fix(TDP-3599) Upgrade DQ consumer lib

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsConfigurer.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsService.java

e.g. https://jira.talendforge.org/browse/TDP-3460

feat(TDP-3460/backend): add dq ui access rights management

---

dataprep-backend/pom.xml

chores : upgrade DQ dependencies

---

dataprep-webapp/src/app/components/widgets/modal/_modal.scss

fix: Talend job form btn display

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/DeleteColumn.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/DeleteColumnTest.java

e.g. https://jira.talendforge.org/browse/TDP-2540

TDP-2540 delete multi column

---

dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js
dataprep-webapp/src/app/services/search/inventory/search-inventory-service.js

chore: fix lint issues

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

* Use regex for dataSet and preparation search
e.g. https://jira.talendforge.org/browse/TDP-2728

fix(TDP-2728/backend): search is case sensitive

---

dataprep-webapp/src/app/components/widgets/datetimepicker/widget-datetimepicker-directive.js

e.g. https://jira.talendforge.org/browse/TDP-3595

fix(TDP-3595):  fix datetimepicker bug

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets/typeahead/_typeahead.scss
dataprep-webapp/src/app/components/widgets/typeahead/typeahead-directive.js
dataprep-webapp/src/app/components/widgets/typeahead/typeahead-directive.spec.js
dataprep-webapp/src/app/components/widgets/typeahead/typeahead.html

Typeahead style has been updated according to Bootstrap theme

chore(webapp): upgrade monorepo dependencies

---

dataprep-webapp/src/app/components/datagrid/_datagrid.scss

https://jira.talendforge.org/browse/TDP-3552

fix(TDP-3552): bold charson identical values

---

dataprep-webapp/src/app/components/inventory/item/inventory-item.html

https://jira.talendforge.org/browse/TDP-3330

feat(TDP-3330): use Amazon S3 icon

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedChars.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedCharsTest.java

* Remove duplicate test method which are same with API
* Support any data type, not only String

feat(TDQ-13578) improve the removal of repeated char

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
dataprep-backend-service/src/main/java/org/talend/dataprep/processor/WrapperProcessor.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/AuthorizationHeaderRelaySecurity.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurity.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java

https://jira.talendforge.org/browse/TDP-3543
* Changes to OS code for support of TDP-3543.

feat(TDP-3543): Provide standalone FullRun service

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/DurationConverter.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DurationConverterTest.java
dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-3675

TDP-3675: add precision parameter for durationConversion action

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java

https://jira.talendforge.org/browse/TDP-3671

fix(TDO-3671): Fix missing HTTP header for content download.

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationCleaner.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/task/PreparationCleanerTest.java

e.g. https://jira.talendforge.org/browse/TDP-2724

feat(TDP-2724) Back - Fixed commit error

---

dataprep-backend/pom.xml

* Move to daikon 0.17.0-SNAPSHOT to get latest changes.

chore: Move to daikon-spring-security

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java

e.g. https://jira.talendforge.org/browse/TDP-3804

TDP-3804 typo switch calendar action

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

e.g. https://jira.talendforge.org/browse/TDP-3614

fix(TDP-3614): min-height and flexbox are causing pbm on IE

---

dataprep-webapp/src/app/components/filter/bar/_filter-bar.scss

https://jira.talendforge.org/browse/TDP-3509

fix(TDP-3509): [IE11] Filter bar and filter search overlap

---

dataprep-webapp/src/app/components/filter/item/_filter-item.scss
dataprep-webapp/src/app/components/playground/_playground.scss
dataprep-webapp/src/app/components/recipe/recipe-component.spec.js
dataprep-webapp/src/app/components/recipe/step-description/_step-description.scss
dataprep-webapp/src/app/components/recipe/step-description/step-description-component.spec.js
dataprep-webapp/src/app/components/recipe/step-description/step-description-controller.js
dataprep-webapp/src/app/components/recipe/step-description/step-description-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-header/_actions-header.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-header/actions-header-component.js

https://jira.talendforge.org/browse/TDP-3900

fix(TDP-3900): set to original case everywhere

---

dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/PreparationErrorCodes.java
dataprep-backend-service/src/main/java/org/talend/dataprep/json/StreamModule.java
dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
dataprep-backend-service/src/test/java/org/talend/dataprep/json/StreamModuleTest.java

* Type fixes: ALL_READY -> ALREADY.
* Code resiliency improvements for empty preparation names.
* Code resiliency improvements for stream serialization and null values (+ unit test).
https://jira.talendforge.org/browse/TDP-2724

TDP-2724: Import a preparation (review)

---

dataprep-webapp/src/app/services/dataset/dataset-service.js
dataprep-webapp/src/app/services/dataset/dataset-service.spec.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js

URL encode the parameters
https://jira.talendforge.org/browse/TDP-3654

fix(TDP-3654): [IE11] Cannot search datasets with multi-byte characters

---

dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Documentation.java

https://jira.talendforge.org/browse/TDP-3545

TDP-3545 Expose a remote service for writing executions

---

dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status.html
dataprep-webapp/src/app/services/state/dataset/dataset-state-service.js

https://jira.talendforge.org/browse/TDP-3582

fix(TDP-3582): progress bar when creating a preparation is messed up

---

dataprep-webapp/src/app/components/datagrid/header/_datagrid-header.scss
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html

https://jira.talendforge.org/browse/TDP-3931

fix(TDP-3931): wrong alignement when renaming a column

---

dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html
dataprep-webapp/src/app/services/statistics/statistics-service.js
dataprep-webapp/src/app/services/statistics/statistics-service.spec.js

https://jira.talendforge.org/browse/TDP-3651

fix(TDP-3651): whitespaces are trimmed in the pattern list

---

dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/_column-profile-options.scss

https://jira.talendforge.org/browse/TDP-3900

fix(TDP-3900): Display all the column names with the original case instead of forcing uppercase

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-api/src/test/java/org/talend/dataprep/api/service/ExportAPITest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/row/RowMetadataUtils.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/WriterRegistrationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategies.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/BaseSampleExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/BaseStandardExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/SampleExportStrategy.java

https://jira.talendforge.org/browse/TDP-3845

TDP-3845 write s3 on tcomp

---

dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/store/content/DataSetContentStore.java
dataprep-webapp/package.json
dataprep-webapp/src/app/components/dataset/import/tcomp/_dataset-import-tcomp.scss
dataprep-webapp/src/app/components/dataset/import/tcomp/dataset-import-tcomp.controller.js
dataprep-webapp/src/app/components/dataset/import/tcomp/dataset-import-tcomp.controller.spec.js
dataprep-webapp/src/app/components/dataset/import/tcomp/dataset-import-tcomp.html
dataprep-webapp/src/app/components/widgets/modal/_modal.scss
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-3460

fix(TDP-3680): be able to refresh forms

---

dataprep-webapp/src/app/components/step-progress/_step-progress.scss

fix: step progress modal aligment issue after dependencies upgrade

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java

https://jira.talendforge.org/browse/TDP-3577
https://jira.talendforge.org/browse/TDQ-13499

feat(TDP-3577 TDQ-13499) convert Julian day to calendar.

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/RowMetadata.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/RowMetadataTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategyTest.java

* Add RwoMetadata.nextId to Json, add unit test
* Fix a unit Test
https://jira.talendforge.org/browse/TDP-3682

fix(TDP-3682): Last columns deletion occurs bad preview

---

dataprep-webapp/src/app/services/utils/config/utils-documentation-search-version-service.js
dataprep-webapp/src/app/services/utils/config/utils-documentation-search-version-service.spec.js
dataprep-webapp/src/assets/config/config.json

https://jira.talendforge.org/browse/TDP-3708

feat(TDP-3708): search on documentation version 2.1 instead of 2.0

---

dataprep-webapp/src/app/components/widgets/modal/_modal.scss

https://jira.talendforge.org/browse/TDP-3995

fix(TDP-3995): deal with overflow for IE11

---

dataprep-webapp/src/app/services/search/documentation/search-documentation-service.js

https://jira.talendforge.org/browse/TDP-4002

fix(TDP-4002): convert special html characters in doc search to readable

---

dataprep-webapp/src/app/components/home/home-controller.js
dataprep-webapp/src/app/components/home/home-controller.spec.js
dataprep-webapp/src/app/services/folder/folder-module.js
dataprep-webapp/src/app/services/folder/folder-service.js
dataprep-webapp/src/app/services/folder/folder-service.spec.js
dataprep-webapp/src/app/services/onboarding/onboarding-preparations-constants.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.js
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-3642

fix(TDP-3642): playground onboarding display

---

dataprep-api/src/main/resources/application.properties
dataprep-dataset/src/main/resources/application.properties
dataprep-transformation/src/main/resources/application.properties

https://jira.talendforge.org/browse/TDP-4014
https://jira.talendforge.org/browse/TDP-4008

fix(TDP-4014): set async tasks timeout to 5min

---

dataprep-webapp/src/app/components/home/home-controller.js

https://jira.talendforge.org/browse/TDP-3642
-import dataset modal is not showed when importing a dataset
-display import dataset modal

fix: regression - display import dataset modal

---

dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformerTest.java

* re-add the step node that was not added anymore
https://jira.talendforge.org/browse/TDP-3514

bugfix(TDP-3514) properly deal with semantic categories deletion

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/HistogramTest.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummaryTest.java
dataprep-backend-common/src/test/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformerTest.java

- fix migration of step rowMetadata
https://jira.talendforge.org/browse/TDP-4042

fix(TDP-4042) migration of step failed

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/HistogramTest.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummaryTest.java

* fix(TDP-4042) migration of step failed
- fix migration of step rowMetadata
* bugfix(TDP-3514) properly deal with semantic categories deletion (#680)
* re-add the step node that was not added anymore
https://jira.talendforge.org/browse/TDP-4042

fix(TDP-4042) migration of step failed (#679)

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js
dataprep-webapp/src/app/components/widgets-containers/breadcrumb/breadcrumb-container.spec.js
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-3306

feat(TDP-3306): polish search bar

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/uris/provider/Uris.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/uris/provider/UrisProvider.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/settings/UrisProviderTest.java
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.spec.js
dataprep-webapp/src/mocks/Settings.mock.js

- change servlet path to /gateway
- add url for dataset upload (POST and PUT)

fix(TDP-4043) Performance issue import CSV

---

dataprep-backend-service/src/main/java/org/talend/dataprep/io/CloseableResourceWatch.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java

https://jira.talendforge.org/browse/TDP-4045

bugfix(TDP-4045) fix connection leaks / file leaks and improve debugging

---

dataprep-webapp/src/app/components/playground/_playground.scss
dataprep-webapp/src/app/components/recipe/_recipe.scss

https://jira.talendforge.org/browse/TDP-3711
I removed accordion transition glitch and increased background size while hovering step
It will fix
- https://jira.talendforge.org/browse/TDP-3387
- https://jira.talendforge.org/browse/TDP-3947

feat(TDP-3711): recipe knots style

---

dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js

Searchbar is not longer cleared when searching for the same text two times

fix: prevent searchbar to be cleared when searching same thing two times

---

dataprep-webapp/src/app/components/filter/item/value/_filter-value.scss
dataprep-webapp/src/app/components/filter/item/value/filter-value-controller.js
dataprep-webapp/src/app/components/filter/item/value/filter-value-controller.spec.js
dataprep-webapp/src/app/components/filter/item/value/filter-value-module.js
dataprep-webapp/src/app/components/filter/item/value/filter-value.html

https://jira.talendforge.org/browse/TDP-3651
It's not managed in filters.
It's managed in filters.

fix(TDP-3651): leading and trailing whitespaces are trimmed

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/uris/provider/Uris.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/uris/provider/UrisProvider.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/settings/UrisProviderTest.java
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.js
dataprep-webapp/src/app/services/utils/config/utils-rest-urls-service.spec.js
dataprep-webapp/src/mocks/Settings.mock.js

Revert "fix(TDP-4043) Performance issue import CSV"

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-api/src/main/java/org/talend/dataprep/configuration/APIPreparationConversions.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/ExportFormatConversions.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/PreparationRepositoryConfiguration.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/BeanConversionService.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/Registration.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/RegistrationBuilder.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/RegistrationImpl.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/ExceptionsConfiguration.java
dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/UserDataRepository.java
dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/inmemory/InMemoryUserDataRepository.java
dataprep-backend-service/src/test/java/org/talend/dataprep/conversions/BeanConversionServiceTest.java
dataprep-backend/pom.xml
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/configuration/DataSetConversions.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java

https://jira.talendforge.org/browse/TDP-3858

fix tdp 3858 dictionnaries not sent to streams

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java

fix(TDP-4126 TDQ-13936): Change Minguo Locale to Locale.TRADITIONAL_CHINESE

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

chores: upgrade dependencies

---

dataprep-webapp/src/app/components/feedback/_feedback.scss
dataprep-webapp/src/app/components/feedback/feedback.html

https://jira.talendforge.org/browse/TDP-4161

fix(TDP-4161): fix send feedback modal style

---

dataprep-webapp/package.json

https://jira.talendforge.org/browse/TDP-4173

feat(TDP-4173): bump UI version

---

dataprep-webapp/src/app/components/export/_export.scss
dataprep-webapp/src/app/components/export/export-controller.js
dataprep-webapp/src/app/components/export/export.html
dataprep-webapp/src/app/components/folder/selection/folder-tree-node/_folder-tree-node.scss
dataprep-webapp/src/app/components/folder/selection/folder-tree-node/folder-tree-node.html
dataprep-webapp/src/mocks/Settings.mock.js

https://jira.talendforge.org/browse/TDP-4142

fix(TDP-4142): PE - fix ui glitches 

---

dataprep-webapp/src/app/components/step-progress/_step-progress.scss
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4156

fix(TDP-4156): dataset upload modal not centered

---

dataprep-webapp/package.json

chore: specify protocol to use for non npm deps

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4200

fix(TDP-4200): datalist onblur triggering

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js
dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.spec.js

fix(TDP-4132): 401 should not trigger error msg

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties

https://jira.talendforge.org/browse/TDP-3815

fix(TDP-3815): pluzialize remove consecutive character

---

dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java

https://jira.talendforge.org/browse/TDP-4160
https://jira.talendforge.org/browse/TDP-4159

fix(TDP-4160) datasets migration to 2.1

---

dataprep-backend-service/src/main/java/org/talend/dataprep/util/SortAndOrderHelper.java

https://jira.talendforge.org/browse/TDP-3523

fix(TDP-3523): sort on author returns empty

---

dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-4146

fix(TDP-4146): reset name edit mode

---

dataprep-webapp/src/app/components/playground/_playground.scss

fix: no more scrollbar in dataset parameters

---

dataprep-webapp/src/app/components/home/home.html

https://jira.talendforge.org/browse/TDP-4236

fix(TDP-4236): bad title for add dataset

---

dataprep-webapp/src/app/components/dataset/import/tcomp/dataset-import-tcomp.controller.js
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-4209

fix(TDP-4209): no feedback when opening a prep

---

dataprep-webapp/src/app/css/components/_intro.scss
dataprep-webapp/src/app/services/onboarding/onboarding-playground-constants.js
dataprep-webapp/src/app/services/onboarding/onboarding-preparations-constants.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.js

https://jira.talendforge.org/browse/TDP-2245

fix(TDP-2245): delete onboarding steps numbers

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportUtils.java

https://jira.talendforge.org/browse/TDP-4194

fix(TDP-4194): spaces are badly encoded in file name

---

dataprep-backend/pom.xml

(bump to 0.18.0-SNAPSHOT to manage percentage as numeric value)
https://jira.talendforge.org/browse/TDP-2726
https://jira.talendforge.org/browse/TDQ-13103

chore(TDP-2726) upgrade daikon version

---

dataprep-webapp/config/webpack.config.js

chore: remove config.mine.json usage

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java

chores add Content-Type application/json to GET /api/datasets/{id}

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AggregationAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/ExportAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/SearchAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
dataprep-api/src/test/resources/org/talend/dataprep/api/service/dataset/expected_dataset_with_metadata_regex_test.json
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java

- add a test of data set creation with a regex breaking name
- remove an unused parameter for data set creation (not present in API)

chores: add a test and some clean-up

---

dataprep-webapp/src/app/components/preparation/creator/form/_preparation-creator-form.scss
dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form-component.spec.js
dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form.html
dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-2493

fix(TDP-2493): message if no dataset in add preparation dialog

---

dataprep-webapp/package.json

https://jira.talendforge.org/browse/TDP-4261

fix(TDP-4261): fix list toolbar color problem

---

dataprep-webapp/src/app/components/datagrid/header/_datagrid-header.scss

https://jira.talendforge.org/browse/TDP-2734

fix(TDP-2734): no lowercase on type

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java

https://jira.talendforge.org/browse/TDP-4027

fix (TDP-4027) fix integer overflow in NumberHistogram stream

---

dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.spec.js

https://jira.talendforge.org/browse/TDP-2734

fix(TDP-2734): use semantic label in preview

---

dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationCleaner.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/task/PreparationCleanerTest.java

https://jira.talendforge.org/browse/TDP-3600

TDP-3600 fix on maintenance 2.0

---

dataprep-webapp/config/sass.conf.js
dataprep-webapp/config/webpack.config.js
dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/breadcrumb/breadcrumb-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/layout/layout-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js
dataprep-webapp/src/app/index.scss
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4094

feat(TDP-4094): prefix dependencies by talend npm org

---

dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

https://jira.talendforge.org/browse/TDP-3451
https://jira.talendforge.org/browse/TDP-4296

fix(TDP-3451/TDP-4296): recipe visibility management

---

dataprep-webapp/src/app/components/recipe/_recipe.scss
dataprep-webapp/src/app/components/recipe/recipe-controller.js
dataprep-webapp/src/app/components/recipe/recipe-controller.spec.js
dataprep-webapp/src/app/components/recipe/recipe.html

https://jira.talendforge.org/browse/TDP-2603

fix(TDP-2603): delete recipe step

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4004

fix(TDP-4004): salesforce module scrollbar issue

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/_actions-list.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-directive.js

https://jira.talendforge.org/browse/TDP-4226

fix(TDP-4226): functions panel scroll issue

---

dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/FolderRepository.java
dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
dataprep-backend-service/src/test/java/org/talend/dataprep/folder/store/AbstractFolderTest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-4198

TDP-4198 Use streams for folder

---

dataprep-backend-service/src/main/java/org/talend/dataprep/security/ForAll.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpForAll.java
dataprep-backend-service/src/test/java/org/talend/dataprep/security/NoOpForAllTest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/task/PreparationCleaner.java

No Jira
* Add a predicate that allows selective run of the ForAll's runnable.
* Generalize use of conditions for repository-based ForAll usages.
* Add missing unit test for NoOpForAll implementation.

chore: Add predicate for ForAll

---

dataprep-webapp/src/app/components/filter/item/_filter-item.scss
dataprep-webapp/src/app/components/filter/item/value/_filter-value.scss
dataprep-webapp/src/app/components/filter/item/value/filter-value.html
dataprep-webapp/src/app/components/widgets/resizable-input/resizable-input-directive.js
dataprep-webapp/src/app/components/widgets/resizable-input/resizable-input-directive.spec.js

https://jira.talendforge.org/browse/TDP-3538

fix(TDP-3538): dont truncate in filters

---

dataprep-webapp/config/webpack.config.js

https://jira.talendforge.org/browse/TDP-4094

fix(TDP-4094): @talend migration -windows

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/GenerateSequence.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateSequenceTest.java

https://jira.talendforge.org/browse/TDP-946

Feature/tdq 13268/generate sequence

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/filter/item/_filter-item.scss

https://jira.talendforge.org/browse/TDP-4262

feat(TDP-4262): change invalid color

---

dataprep-api/src/main/resources/application.properties
dataprep-dataset/src/main/resources/application.properties
dataprep-preparation/src/main/resources/application.properties
dataprep-transformation/src/main/resources/application.properties

* Enable GZIP compression for REST responses (text/plain and application/json).
https://jira.talendforge.org/browse/TDP-3913

feat(TDP-3913): Enable cache for REST responses

---

dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParameters.java

https://jira.talendforge.org/browse/TDP-4370
* Missing javadoc on SourceType.

fix(TDP-4370) Missing javadoc for export source types

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/ExportAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/FolderAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java

* add a few LOG.info here and there
https://jira.talendforge.org/browse/TDP-4137

feat (TDP-4137) log interesting moments for "marketing purposes"

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4355

feat(TDP-4355) : remove snapshot dependancies

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategyTest.java

https://jira.talendforge.org/browse/TDP-4330

fix(TDP-4330) : change value to get the full content of the Dataset

---

dataprep-backend-service/pom.xml
dataprep-backend/pom.xml

* update apache tika to 1.16
* update bean commons-beanutils to 1.9.3
* set explicit dependency to xerces to be compatible with apache tika 1.16
* update commons-compress to be compatible with apache tika 1.16

bugfix (TDP-4279): Update dependencies to prevent CVE

---

dataprep-webapp/src/app/components/recipe/_recipe.scss

https://jira.talendforge.org/browse/TDP-4360

fix(TDP-4360): fix drag and drop style

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4392
* Bump version for Daikon (0.18.0 -> 0.18.1).

chore(TDP-4392) Upgrade daikon libraries

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_actions.json
dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions_string.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json

https://jira.talendforge.org/browse/TDP-4244

fix(TDP-4244): rename replace the cells that match

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js

fix(TDP-4132): avoid error message while login

---

dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceBaseTest.java

https://jira.talendforge.org/browse/TDP-4050

fix(TDP-4050) reorder steps before a "Fetch More" break the preparation

---

dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceBaseTest.java

https://jira.talendforge.org/browse/TDP-4050

fix(TDP-4050): reorder steps before a "Fetch More" break the preparation

---

dataprep-api/src/test/java/org/talend/dataprep/helper/DataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/bean/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/config/GlobalStep.java

- Integration test for TAC
https://jira.talendforge.org/browse/TDP-3336
Use to test on dev-ee
mvn clean test \
-Dbackend.user.login=integration@talend.com \
-Dbackend.user.password=integration \
-Dbackend.login.api.url=http://dev.data-prep-ee.talend.lan:9999 \
-Dbackend.global.api.url=http://dev.data-prep-ee.talend.lan:9999/gateway \
-Dbackend.upload.api.url=http://dev.data-prep-ee.talend.lan:9999/gateway/upload \
-Dbackend.export.api.url=http://dev.data-prep-ee.talend.lan:9999/gateway \
-Dcucumber.options="classpath:features/onprem/TACLiveDataSet.feature"
Use to test on locale (with public.ip set to your ip)
mvn clean test \ …

feat(TDP-3336) "Live datasets" in the Cloud release

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4424

TDP-4424 (work item) update dataquality libs

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/RemoveNonAlphaNumChars.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveNonAlphaNumCharsTest.java

https://jira.talendforge.org/browse/TDP-4407

TDP-4407: First test done

---

dataprep-backend-service/src/main/java/org/talend/dataprep/cache/ContentCache.java

https://jira.talendforge.org/browse/TDP-4476

fix(TDP-4476): small update in cache TTL enum

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
dataprep-backend-service/src/test/java/org/talend/dataprep/folder/store/AbstractFolderTest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

* Essentially close streams on filesystem elements

chore(windows10): fix unit tests that fail under Windows10

---

dataprep-webapp/src/app/components/folder/selection/_folder-selection.scss
dataprep-webapp/src/app/components/folder/selection/folder-selection.html
dataprep-webapp/src/app/components/loader/_loader.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
dataprep-webapp/src/app/components/suggestions-stats/column-profile/_column-profile.scss
dataprep-webapp/src/app/index.scss

https://jira.talendforge.org/browse/TDP-3984

fix(TDP-3984): no feedback in share dialog

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-4508

fix(TDP-4508) : fix bug on steps of a copied preparation

---

dataprep-backend/pom.xml

* update dataprep core version to : 2.2.1-SNAPSHOT
Just to prevent errors like https://ci-tdp.datapwn.com/view/data-prep-ee/job/data-prep-ee_unit-test_master/614/console
no jira

chore(update version)

---

dataprep-backend/pom.xml
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
dataprep-dataset/src/test/resources/org/talend/dataprep/dataset/semantic_type_threshold.csv

https://jira.talendforge.org/browse/TDP-4578

feat(TDP-4578): Update DataQuality Core librairies

---

dataprep-webapp/src/app/services/playground/playground-service.js

When i run `npm run serve`, compile is failed because of eslint.

chore(webapp): fix eslint about brace-style

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/TQLFilterService.java

TDP-4346: fix master breaking change

---

dataprep-webapp/pom.xml
dataprep-webapp/src/app/services/statistics/statistics-service.spec.js

https://jira.talendforge.org/browse/TDP-4399

fix(TDP-4399): use mvn plugin everywhere

---

dataprep-api/src/main/resources/application.properties

https://jira.talendforge.org/browse/TDP-4538

feat(TDP-4538): Change parameter in links pointing to specific doc pages

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4600

chore: Fix wrong TQL dependency version on cloud version.

---

dataprep-webapp/pom.xml
dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.spec.js
dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.spec.js

chore(ci): frontend build

---

dataprep-webapp/pom.xml
dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.spec.js
dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.spec.js

chore(cloud): ci

---

dataprep-backend-service/src/main/java/org/talend/dataprep/exception/ErrorCodeDto.java

skermabon/chore/add toString on class ErrorCodeDto

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/duplication/Deduplicate.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/duplication/DeduplicateTest.java

https://jira.talendforge.org/browse/TDP-2195

fix(TDP-2195): fix issue with deleted rows on dedup

---

dataprep-webapp/src/app/components/widgets/charts/boxplot-chart/boxplot-chart-directive.js

https://jira.talendforge.org/browse/TDP-4635

fix(TDP-4635): quartile is truncated

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties

https://jira.talendforge.org/browse/TDP-4390

chore(fix) : wrong label (TDP-4390)

---

dataprep-webapp/pom.xml

https://jira.talendforge.org/browse/TDP-4672

fix(TDP-4672): date picker is broken

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/actions/date/DateParser.java

https://jira.talendforge.org/browse/TDP-4572
Please review this commit. thanks .

bug(TDP-4572/TDQ-14421) get DateTimeFormatter from DQ lib

---

dataprep-webapp/pom.xml

https://jira.talendforge.org/browse/TDP-4672

fix(TDP-4672): datetimepicker is broken

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

https://jira.talendforge.org/browse/TDP-4508

fix(TDP-4508) change the old way to copy steps

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/FillEmptyFromAbove.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/FillEmptyFromAboveTest.java

https://jira.talendforge.org/browse/TDP-1489

fix(tdp-1489): fill empty from above no longer take deleted rows

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/GenerateSequence.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateSequenceTest.java

https://jira.talendforge.org/browse/TDP-4593

fix(TDP-4593) : generate sequence avoid nullpointer

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

https://jira.talendforge.org/browse/TDP-4508

feat(TDP-4508) : backport fix on maintenance cloud

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

https://jira.talendforge.org/browse/TDP-4508

fix(TDP-4508) : fix bug and change the way to copy steps between prep

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/actions/date/DateParser.java
dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4572

feat(TDQ-14421 TDP-4572 ) get DateTimeFormatter from DQ lib

---

dataprep-backend-service/src/main/java/org/talend/dataprep/exception/TDPException.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/CommonErrorCodes.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/DataSetErrorCodes.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysis.java

https://jira.talendforge.org/browse/TDP-1943

TDP-1943 improve management error in live dataset

---

dataprep-test-api/README.md
dataprep-test-api/src/test/resources/features/SmokeTest.feature

https://jira.talendforge.org/browse/TDP-4692

feat(TDP-4692): Refreshing EE README.md documentation.

---

dataprep-backend-service/src/main/java/org/talend/dataprep/lock/DistributedLockWatcher.java
dataprep-backend-service/src/test/java/org/talend/dataprep/lock/DistributedLockWatcherTest.java

https://jira.talendforge.org/browse/TDP-4678
* Add removal from watched list when a lock is successfully released.
* Amend unit test to ensure release.

fix(TDP-4678): Fix missing unregister of lock on successful release.

---

dataprep-backend-common/src/main/java/org/talend/dataprep/util/NumericHelper.java
dataprep-backend-common/src/test/java/org/talend/dataprep/util/NumericHelperTest.java

fix: should not be empty after trim

---

dataprep-backend-common/src/main/java/org/talend/dataprep/util/NumericHelper.java
dataprep-backend-common/src/test/java/org/talend/dataprep/util/NumericHelperTest.java

(cherry picked from commit c026e39)
https://jira.talendforge.org/browse/TDP-4699

fix: should not be empty after trim (#903)

---

dataprep-test-api/src/test/resources/data/10L3C_processed.csv
dataprep-test-api/src/test/resources/data/6L3C_default_export_parameters.csv
dataprep-test-api/src/test/resources/data/6L3C_processed_custom_escape_char.csv
dataprep-test-api/src/test/resources/features/ExportPreparation.feature
dataprep-test-api/src/test/resources/features/SmokeTest.feature
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVWriterCustom.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/CSVWriterTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/ObjectBufferTest.java

https://jira.talendforge.org/browse/TDP-4087
https://jira.talendforge.org/browse/TDP-4088
https://jira.talendforge.org/browse/TDP-4090

feat(TDP-4087/TDP-4389/TDP4390) : correct CSV export

---

dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Localization.java
dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java

fix(TDP-2663): Fix wrong configuration property

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/BasePreparationTest.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/FolderServiceTest.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java

https://jira.talendforge.org/browse/TDP-4270

TDP-4270 : fix to be not sensible on path parameter

---

dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider-directive.js
dataprep-webapp/src/app/components/widgets/charts/range-slider/range-slider.html
dataprep-webapp/src/app/components/widgets/datetimepicker/widget-datetimepicker-directive.js
dataprep-webapp/src/app/components/widgets/datetimepicker/widget-datetimepicker-directive.spec.js

https://jira.talendforge.org/browse/TDP-4700

fix(TDP-4700): datetimepicker dynamic position

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionForm.java

https://jira.talendforge.org/browse/TDP-2663

feat(TDP-2663): make ActionForm serializable

---

dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/CommonErrorCodes.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/error_messages.properties

https://jira.talendforge.org/browse/TDP-4612
- [c] Docs have been added / updated (for bug fixes / features)

fix(TDP-4612) Use immutable id from listTask and triggerTask TAC api when using Live datasets

---

dataprep-webapp/src/app/components/playground/playground-controller.spec.js
dataprep-webapp/src/app/components/playground/playground-directive.spec.js
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/components/preparation/picker/preparation-picker-controller.js

https://jira.talendforge.org/browse/TDP-4447

fix(TDP-4447): preparation picker

---

dataprep-webapp/src/app/index-module.js

https://jira.talendforge.org/browse/TDP-4725

fix(TDP-4725): force locale initialization for MomentJS

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/CSVFormat.java
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4389

fix(TDP-4389) : fix minor bugs

---

dataprep-webapp/src/app/components/inventory/tile/inventory-tile-directive.spec.js
dataprep-webapp/src/app/components/inventory/tile/inventory-tile.html
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4447

fix(TDP-4447): fix rows number display in the preparation picker

---

dataprep-webapp/src/app/components/export/export-controller.js
dataprep-webapp/src/app/components/export/export-controller.spec.js

https://jira.talendforge.org/browse/TDP-4738

fix(TDP-4738): allow empty csv parameters on pe

---

dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java

https://jira.talendforge.org/browse/TDQ-14484

TDQ-14484 broadcast dictionary to cluster

---

dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html

https://jira.talendforge.org/browse/TDP-4726

fix(TDP-4726): actions layout

---

dataprep-webapp/src/app/components/inventory/tile/inventory-tile-directive.spec.js
dataprep-webapp/src/app/components/inventory/tile/inventory-tile.html
dataprep-webapp/src/app/components/playground/playground-controller.spec.js
dataprep-webapp/src/app/components/playground/playground-directive.spec.js
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/components/preparation/picker/preparation-picker-controller.js
dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-4447

fix(TDP-4447): fix preparation picker

---

dataprep-actions/pom.xml
dataprep-backend-common/pom.xml
dataprep-backend-service-parent/pom.xml
dataprep-backend/pom.xml
pom.xml

* effort in diminishing the quantity of duplicated pom configuration
for the <plugins> section
https://jira.talendforge.org/browse/TDP-4739

feat(TDP-4739): partly remove plugins duplication

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/NumericOperations.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/NumericOperationsTest.java

https://jira.talendforge.org/browse/TDP-4537

fix(tdp-4537): remove round in math ops

---

dataprep-actions/src/test/java/org/talend/dataprep/i18n/ActionsBundleTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions_messages_en_US.properties
dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java

there was a problem with caching in action bundle. This commit solves this
by minimize the cache impact on code structure.
This cache is based on guava's implementation.

chore: correct a bug in ActionBundle implementation

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/delete/DeleteAllEmpty.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/delete/DeleteAllEmptyTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/duplication/DeduplicateTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/ReplaceCellValueTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/delete/deleteAllEmptyAction.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_dataset_scope_actions.json

https://jira.talendforge.org/browse/TDP-2188

feat(tdp-2188): delete all empty rows action

---

dataprep-backend/pom.xml
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java

* update libs (daikon -> 0.19.0, dataquality-libraries -> 4.0.1-SNAPSHOT, dataquality-semantic-consumer -> 2.0.1-SNAPSHOT, daikon-ee -> 0.8.0, iam version 1.0.0-20171205153406-g1852b42)
https://jira.talendforge.org/browse/TDP-4763

workItem(TDP-4763) Update all Talend libs for 6.5

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/CreateNewColumnTest.java

https://jira.talendforge.org/browse/TDP-1208

feat(TDP-1208): add name param in create new column

---

dataprep-actions/pom.xml
dataprep-backend-common/pom.xml
dataprep-backend/pom.xml

chore(): release action for tds

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportUtils.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/CachedExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/CSVFormatTest.java

https://jira.talendforge.org/browse/TDP-4805

fix(TDP-4805): CSV export format now includes encoding in Content-Type

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.spec.js
dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
dataprep-webapp/src/app/components/widgets-containers/layout/layout.scss
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4314

feat(TDP-4314): switch virtualized list

---

dataprep-webapp/config/webpack.config.js

chore: fonts and webpackdevserver

---

dataprep-backend/pom.xml

fix(): update swagger version

---

dataprep-webapp/src/app/components/about/about.html
dataprep-webapp/src/app/components/easter-eggs/easter-eggs.html
dataprep-webapp/src/app/components/feedback/feedback.html
dataprep-webapp/src/app/components/folder/creator/folder-creator-container.js
dataprep-webapp/src/app/components/home/dataset/home-dataset.html
dataprep-webapp/src/app/components/home/name-modal/name-modal.html
dataprep-webapp/src/app/components/lookup/lookup.html
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move-container.js
dataprep-webapp/src/app/components/preparation/creator/preparation-creator-container.js
dataprep-webapp/src/app/components/step-progress/step-progress.html
dataprep-webapp/src/app/components/widgets/confirm/confirm.html
dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-directive.js
dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-service.js
dataprep-webapp/src/app/components/widgets/confirm/widget-confirm-service.spec.js
dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.js
dataprep-webapp/src/app/components/widgets/modal/widget-modal-directive.spec.js
dataprep-webapp/src/app/services/import/import-service.js
dataprep-webapp/src/app/services/import/import-service.spec.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-4496

fix(TDP-4496): remove modal enter key management

---

dataprep-backend/pom.xml

chore: update core version on master

---

dataprep-test-api/pom.xml

chore: test api as m2 module

---

dataprep-backend/pom.xml

chore(): update core version

---

dataprep-test-api/pom.xml

chore: test api as m2 module (#956)

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/delete/DeleteAllEmpty.java

https://jira.talendforge.org/browse/TDP-4828

fix(TDP-4828): localize params for delete mode

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java

https://jira.talendforge.org/browse/TDP-4779

fix(TDP-4779) : dynamic preparation with special char

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/_actions-list.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html

https://jira.talendforge.org/browse/TDP-4849

fix(TDP-4849): add loader on find and group modal

---

dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
dataprep-webapp/src/app/components/suggestions-stats/stats-details/stats-details.html

https://jira.talendforge.org/browse/TDP-4595

fix(TDP-4595): fix chart panel bad display

---

dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java

chore(): Fix async-store module build.

---

dataprep-webapp/src/app/components/lookup/lookup-controller.js
dataprep-webapp/src/app/components/lookup/lookup-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-directive.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-directive.spec.js
dataprep-webapp/src/app/services/early-preview/early-preview-service.js
dataprep-webapp/src/app/services/early-preview/early-preview-service.spec.js
dataprep-webapp/src/app/services/state/playground/playground-state-service.js
dataprep-webapp/src/app/services/state/state-service.js

https://jira.talendforge.org/browse/TDP-2110
this fixs the bug described in the comment since the original problem is not reproduced

fix(TDP-2110) preview stucked on the recipe

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

chore(): Review order of extract date token parameters.

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-controller.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-4846
The whole list (including headers in table display mode) will disappears to show the loader after 400ms. Another PR should be merged on the monorepo to fix this. 

fix(TDP-4846): add loader when sorting lists

---

dataprep-webapp/src/app/services/early-preview/early-preview-service.js

fix: useless stateservice injection

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Cut.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/CutTest.java

https://jira.talendforge.org/browse/TDP-3798

fix(TDP-3798): toggle sub tasks

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ModifyDate.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-4277

feat(TDP-4277) : add min and sec in compute time since

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/clear/RemoveNegativeValues.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/clear/RemoveNegativeValuesTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/clear/removeNegativeValuesAction.json

https://jira.talendforge.org/browse/TDP-4394

feat(TDP-4394): remove negative values

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/SemanticDomain.java
dataprep-backend-common/src/main/java/org/talend/dataprep/dataset/StatisticsAdapter.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

https://jira.talendforge.org/browse/TDP-4356

feat(TDP-4356): replace SemanticDomain.frequency by score

---

dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend-common/src/test/java/org/talend/dataprep/quality/AnalyzerServiceTest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Analyzers.java
dataprep-backend/pom.xml
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java

https://jira.talendforge.org/browse/TDP-3769
https://jira.talendforge.org/browse/TDQ-14361

feat(TDP-3769): Discovery and validation with multi-tenant index

---

dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-4846

fix(TDP-4846): add loader when sorting preparation list

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

chores: update versions in data-prep

---

dataprep-webapp/src/app/components/transformation/form/simple/_transformation-simple-param.scss

https://jira.talendforge.org/browse/TDP-4919

fix(TDP-4919): Hovering outside of an open drop-down list closes it

---

dataprep-webapp/src/app/components/recipe/knot/recipe-knot-component.js
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4620

fix(TDP-4620): Add tooltip when hovering recipe bullet

---

dataprep-webapp/src/assets/config/config.json

https://jira.talendforge.org/browse/TDP-4924

fix(TDP-4924): update copyright on about data preparation modal

---

dataprep-webapp/src/assets/config/config.json

https://jira.talendforge.org/browse/TDP-4924

fix(TDP-4924): update copyright on about data preparation modal (#995)

---

dataprep-webapp/src/app/components/widgets/auto-scroll/auto-scroll-directive.js
dataprep-webapp/src/app/components/widgets/auto-scroll/auto-scroll-directive.spec.js

fix: use angular service instead of setInterval

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4905

fix(TDP-4904): list actions are not well displayed with WIN7/IE11

---

dataprep-webapp/karma.conf.js
dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets/auto-scroll/auto-scroll-directive.spec.js
dataprep-webapp/yarn.lock

fix: define viewport size

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-4423
* Use exist(...) instead of get(...) != null for performance improvement.

fix(TDP-4423): Performance improvement

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalid.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalidTest.java

https://jira.talendforge.org/browse/TDP-3936

fix(TDP-3936) : change scope function standardize value

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ModifyDate.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/ChangeNumberFormat.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/ExtractStringTokens.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedChars.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ChangeDatePatternTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ModifyDateTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/ChangeNumberFormatTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/ExtractStringTokensTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedCharsTest.java

https://jira.talendforge.org/browse/TDP-4943

fix(TDP-4943/TDP-3798) : bug when action with toggle column option doesn't apply on cell

---

dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js
dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.spec.js

https://jira.talendforge.org/browse/TDP-4954

fix(TDP-4954): prevent xss from column name

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Step.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategyTest.java

https://jira.talendforge.org/browse/TDP-4121

fix(TDP-4121): Fix wrong preparation version retrieval

---

dataprep-actions/pom.xml
dataprep-api/pom.xml
dataprep-backend-common/pom.xml
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/PipelineConsoleDump.java
dataprep-backend-service-parent/pom.xml
dataprep-backend-service/pom.xml
dataprep-backend/pom.xml
dataprep-dataset/pom.xml
dataprep-maintenance/pom.xml
dataprep-preparation/pom.xml
dataprep-test-api/pom.xml
dataprep-transformation/pom.xml
dataprep-webapp/package.json
dataprep-webapp/pom.xml
dataprep-webapp/src/assets/config/config.json
pom.xml

https://jira.talendforge.org/browse/TDP-4916

chore(): release 2.3.0

---

dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-4958

fix(TDP-4958): typo on notif Dataset rename

---

dataprep-webapp/src/app/components/lookup/lookup-controller.js
dataprep-webapp/src/app/components/lookup/lookup-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
dataprep-webapp/src/app/services/early-preview/early-preview-service.js
dataprep-webapp/src/app/services/early-preview/early-preview-service.spec.js
dataprep-webapp/src/app/services/state/playground/playground-state-service.js
dataprep-webapp/src/app/services/state/state-service.js

https://jira.talendforge.org/browse/TDP-1881

fix(TDP-1881): fix preview cancel problem

---

dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4967

fix(TDP-4967): i18n management - list displaymode

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4934

fix(TDP-4934) Upgrade DQ lib to 4.0.2

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/HttpClient.java

cherry-pick of #1022 
```
#	dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/HttpClient.java
```
https://jira.talendforge.org/browse/TDP-4569

fix(TDP-4569): cookies are returned by REST services (#1022)

---

pom.xml

https://jira.talendforge.org/browse/TDP-4962
The configuration came from talend-jenkins-automation project (tdp templates)
https://github.com/Talend/talend-jenkins-automation/pull/425

TDP-4962 - add sonar properties in the dataprep parent pom

---

dataprep-webapp/src/app/services/column-types/column-types-service.js
dataprep-webapp/src/app/services/datagrid/datagrid-service.js
dataprep-webapp/src/app/services/dataset-workflow/dataset-workflow-module.js
dataprep-webapp/src/app/services/dataset-workflow/update-workflow-service.js
dataprep-webapp/src/app/services/dataset-workflow/upload-workflow-service.js
dataprep-webapp/src/app/services/dataset/dataset-module.js
dataprep-webapp/src/app/services/dataset/dataset-service.js
dataprep-webapp/src/app/services/dataset/list/dataset-list-service.js
dataprep-webapp/src/app/services/dataset/preview/dataset-sheet-preview-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
dataprep-webapp/src/app/services/early-preview/early-preview-module.js
dataprep-webapp/src/app/services/early-preview/early-preview-service.js
dataprep-webapp/src/app/services/easter-eggs/easter-eggs-module.js
dataprep-webapp/src/app/services/errors/notfound-interceptor.js
dataprep-webapp/src/app/services/export/export-module.js
dataprep-webapp/src/app/services/feedback/feedback-rest-service.js

Improve frontend code quality, step by step.

chores: frontend cc

---

dataprep-webapp/src/app/components/filter/item/filter-item.html
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js

https://jira.talendforge.org/browse/TDP-5000

fix(TDP-5000): all filter badges are blue

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomain.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java

waiting for https://jira.talendforge.org/browse/TDQ-14147

feat(TDP-1801/TDQ-14147): support datamasking generate from Dictionaries

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-3858

fix (TDP-3858): bump DQ version to 4.0.3

---

dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/dto/NamedItem.java

Here, there are only changes on Integration Tests (see EE for relevant changes).
🔗 https://github.com/Talend/data-prep-ee/pull/637
https://jira.talendforge.org/browse/TDP-4656

fix(TDP-4656): Impossible to import in 2.3 a preparation done in 2.2

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_fr.properties

https://jira.talendforge.org/browse/TDP-4905

feat(TDP-4905): Add Data Stewardship in the App Switcher

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-4743
needed for https://github.com/Talend/data-prep-ee/pull/631

feat(TDP-4743): update daikon version from 0.19 to 0.20

---

.gitignore

chore: don't track yarn log files

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/DistanceConverter.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/conversions/DurationConverter.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json

https://jira.talendforge.org/browse/TDP-4903

fix(TDP-4903): last items for i18n

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/README.md
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/resources/features/ExportFormat.feature
dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ExportUtils.java

https://jira.talendforge.org/browse/TDP-5043

fix(TDP-5043): fix integration tests

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-5001

feat(TDP-5001): be able to enable CSRF protection for DQ

---

dataprep-webapp/src/app/components/recipe/_recipe.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/_action-suggestions.scss
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
dataprep-webapp/src/app/css/layout/_container.scss
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4381

fix(TDP-4381): add message when no result in the action list

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/TypeUtils.java
dataprep-backend-common/src/main/java/org/talend/dataprep/dataset/StatisticsAdapter.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/StatisticsUtilsTest.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/type/TypeUtilsTest.java
dataprep-webapp/src/app/services/column-types/column-types-service.js
dataprep-webapp/src/app/services/column-types/column-types-service.spec.js

https://jira.talendforge.org/browse/TDP-4155

fix(TDP-4155): semantic types discovery order in submenu

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java

https://jira.talendforge.org/browse/TDP-4084

fix(TDP-4084): Exporting to S3 fails 

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java

https://jira.talendforge.org/browse/TDP-4084

fix(TDP-4084): Exporting to S3 fails

---

dataprep-maintenance/pom.xml
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/upgrade/UpgradeTask.java
dataprep-maintenance/src/main/resources/application.properties
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/upgrade/UpgradeTaskTest.java

https://jira.talendforge.org/browse/TDP-3948

feat(TDP-3948): Migrate upgrade version task in maintenance. PE

---

dataprep-webapp/src/app/components/preparation/creator/form/_preparation-creator-form.scss

https://jira.talendforge.org/browse/TDP-4381

fix(TDP-4381): fix add preparation modal buttons not clickable

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-controller.js
dataprep-webapp/yarn.lock

***What is the problem this PR is trying to solve?**<br><br>Framework/libs/tools are out of date, compared to Talend/ui [version.js](https://github.com/Talend/ui/blob/master/version.js).<br><br>This is an automatic PR, which goal is to align all Framework/libs/tools versions accross all apps.<br><br>**What is the chosen solution to this problem?**<br><br>Run version.js on the webapp.<br><br>Please check Talend/ui [breaking changes log](https://github.com/Talend/ui/blob/master/BREAKING_CHANGES_LOG.md)<br><br>**Please check if the PR fulfills these requirements**

chore: update versions in data-prep

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/resources/features/SmokeTest.feature

https://jira.talendforge.org/browse/TDP-4533

feat(TDP-4533): add TIs for preparation copy

---

dataprep-webapp/src/app/components/playground/playground-directive.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-directive.js
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-controller.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-directive.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-module.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item.html

https://jira.talendforge.org/browse/TDP-4978

feat(TDP-4978): allow to search functions in scope table (#1053)

---

dataprep-webapp/src/app/components/playground/playground-directive.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions-directive.js
dataprep-webapp/src/app/components/suggestions-stats/actions-suggestions/actions-suggestions.html
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-controller.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-directive.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item-module.js
dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item.html

https://jira.talendforge.org/browse/TDP-4978

feat(TDP-4978): allow to search functions in scope table

---

dataprep-webapp/src/app/css/base/_base.scss

https://jira.talendforge.org/browse/TDP-4918

fix(TDP-4918): firefox blurry icons

---

dataprep-webapp/src/app/components/datagrid/editor/talend-editor.js

https://jira.talendforge.org/browse/TDP-5063

fix(TDP-5063): split without separator in all cells create errors

---

dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html

https://jira.talendforge.org/browse/TDP-4837

fix(TDP-4837): semantic type match score should be rounded to 2 digits

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/Action.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java

https://jira.talendforge.org/browse/TDP-5049

fix(TDP-5049): fix modification of imported preparation (+ integration tests)

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/row/RowMetadataUtils.java

https://jira.talendforge.org/browse/TDP-3529

fix(TDP-3529): fix the get most used date pattern

---

dataprep-webapp/src/app/components/suggestions-stats/tab-item/tab-item.html

https://jira.talendforge.org/browse/TDP-4978

fix(TDP-4978): pass correct actions scope

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datablending/LookupTest.java

https://jira.talendforge.org/browse/TDP-3790

fix(TDP-3790): reverse columns in lookup action

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractMultiScopeAction.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java

https://jira.talendforge.org/browse/TDP-2193

fix(TDP-2193): fix format phone numbers for the whole dataset 

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

chores: update tui libs

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/resources/features/SmokeTest.feature

https://jira.talendforge.org/browse/TDP-4533

feat(TDP-4533): copy preparation - add missing tests

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java

https://jira.talendforge.org/browse/TDP-2193

fix(tdp-2193) fix format phone number

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-4532

fix(TDP-4532): allow double click on a row

---

dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/CORSConfiguration.java
dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js
dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.spec.js

fix(TDP-4132): unwanted notification with CORS issues

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractMultiScopeAction.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java
dataprep-test-api/src/test/resources/data/phoneNumberScopeDataset.csv
dataprep-test-api/src/test/resources/data/phoneNumberScopeDataset_formatUs.csv
dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature

https://jira.talendforge.org/browse/TDP-2193

fix(TDP-2193): fix format phone number for the scope dataset

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js
dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.spec.js

fix(TDP-4132): unwanted notification with CORS issues (#1060)

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-api/src/test/resources/org/talend/dataprep/api/service/suggestions/firstname_column_actions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_actions_string.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-2193

fix(TDP-2193): unit tests

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js
dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.spec.js

fix(winter2018/TDP-4132): unwanted notifications

---

dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/upgrade/UpgradeTask.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/upgrade/UpgradeTaskTest.java

https://jira.talendforge.org/browse/TDP-3948

fix(TDP-3948): Don't run migration task when task repository cannot be used.

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js

fix(TDP-4132): unwanted notifications

---

dataprep-webapp/src/app/services/rest/rest-error-message-interceptor-factory.js

fix(TDP-4132): unwanted notifications (#1102)

---

dataprep-webapp/src/app/components/upgrade-version/upgrade-version-service.js
dataprep-webapp/src/app/services/about/about-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js

fix(TDP-4132): unwanted notifications (#1109)

---

dataprep-backend/pom.xml

chore: update dataquality-libraries.version

---

dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParameters.java
dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java

- report fix
https://jira.talendforge.org/browse/TDP-5225

TDP-5225 Migration task about creation new column toggle failed

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsConfigurer.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarHelpConfigurerForNonTDPUsers.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/CommonActionsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/WindowActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViewsForNonTDPUsers.java

https://jira.talendforge.org/browse/TDP-5226

fix(TDP-5226): deal with non TDP users

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsConfigurer.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/HeaderbarHelpConfigurerForNonTDPUsers.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/CommonActionsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/WindowActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViewsForNonTDPUsers.java

fix(TDP-5226): deal with non TDP users (#1110)

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Cos.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Exponential.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Logarithm.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Max.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Min.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/NaturalLogarithm.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Negate.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Pow.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Sin.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/SquareRoot.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/math/Tan.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
dataprep-upgrade-common/src/test/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommonTest.java

https://jira.talendforge.org/browse/TDP-3798

fix: Handle cases when preparation action id changes during migration

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionParamEnum.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-5052

feat(TDP-5052): TI-create custom semantic type

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumberTest.java

* manage legacy types without upgrade task
https://jira.talendforge.org/browse/TDP-5256

fix(TDP-5256): Manage legacy Phone Format Number types

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5167

feat(TDP-5167): Update Data Quality libraries to 4.0.4-SNAPSHOT

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

https://jira.talendforge.org/browse/TDP-3703

fix(TDP-3703): persistent actions style

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

fix(TDP-3703): persistent actions style (#1100)

---

dataprep-webapp/src/app/components/suggestions-stats/column-profile/_column-profile.scss

https://jira.talendforge.org/browse/TDP-5264

fix(TDP-5264): fix charts btn display

---

dataprep-webapp/src/app/components/suggestions-stats/column-profile/_column-profile.scss

fix(TDP-5264): fix charts btn display (#1134)

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
dataprep-upgrade/src/test/java/org/talend/dataprep/upgrade/to_2_3_0_PE/MigrateActionsParametersTest.java

https://jira.talendforge.org/browse/TDP-5253

fix(TDP-5253): fix convert date not applied after column duplication (migration to winter affected)

---

dataprep-backend/pom.xml

(no jira).
* Bump version for DQ lib (5.0.0 -> 5.0.1)

chore: Update DQ lib version

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-5052

feat(TDP-5052): TI- Change cleanAfter order

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java

https://jira.talendforge.org/browse/TDP-5247

fix(TDP-5247): fix default name for new column

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionFormatPhoneNumber.java
dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_3_0_PE/FormatPhoneNumberAction.java

https://jira.talendforge.org/browse/TDP-5256

fix(TDP-5256): Migration task for FormatPhoneNumber action

---

dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json
dataprep-webapp/src/i18n/ja.json

https://jira.talendforge.org/browse/TDP-5273

fix(TDP-5273): add missing HEADERBAR_APPS label

---

dataprep-webapp/src/app/services/statistics/statistics-service.js
dataprep-webapp/src/app/services/statistics/statistics-service.spec.js

https://jira.talendforge.org/browse/TDP-5252

wi(TDP-5252): front ut cleanup

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Split.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionCreateNewColumn.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionFormatPhoneNumber.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ActionNewColumnToggleCommon.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/AddLanguageToActionExtractDatePartUpgrade.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/ParameterMigration.java
dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/common/SplitParametersUpgrade.java
dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_4_0_PE/MigrateStepActionsParameters.java

fix: Add Split parameter migration

---

dataprep-backend-service/src/main/java/org/talend/dataprep/api/service/info/VersionService.java
dataprep-backend-service/src/test/java/org/talend/dataprep/api/service/info/VersionServiceTest.java

(no jira)
* Fix version id order.
* Add Git ops commit id to on-premise bundle.

chore: version service fixes

---

dataprep-api/src/test/java/org/talend/dataprep/helper/api/Action.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/OSRunnerConfigurationTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
dataprep-test-api/src/test/resources/features/DatasetCache.feature
dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
dataprep-test-api/src/test/resources/features/SmokeTest.feature
dataprep-test-api/src/test/resources/features/SplitActionTest.feature
dataprep-test-api/src/test/resources/features/TrimActionTest.feature

https://jira.talendforge.org/browse/TDP-5214

feat(TDP-5214): update OS integration tests

---

dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_dataset_scope_actions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json
dataprep-webapp/src/app/components/transformation/form/choice/transformation-choice-param-controller.js

https://jira.talendforge.org/browse/TDP-3481

fix(TDP-3481): fix TUs

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/TransformerWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/JsonWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/ObjectBuffer.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/format/XlsWriter.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/DiffWriterNode.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/pipeline/model/WriterNode.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/JsonWriterTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/format/XlsWriterTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/format/expected_columns.json

- make XlsWriter accept metadata anytime 
- move JSON serialization from WriterNode to JsonWriter
- remove json style from WriterNode

chore: cleanup in transformer writers

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/SpringContextConfiguration.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/BackendProperties.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-4961

fix(TDP-4961) Integration test with DI jobs

---

dataprep-actions/pom.xml
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/SuggestLookupActions.java
dataprep-backend-common/pom.xml
dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/BaseContent.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/Converters.java
dataprep-backend/pom.xml
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/configuration/PreviewConfiguration.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
dataprep-upgrade/src/main/java/org/talend/dataprep/upgrade/to_2_1_0_PE/SplitReplaceOnValueAction.java

https://jira.talendforge.org/browse/TDP-4974
See https://jira.talendforge.org/browse/ARCH-55

chore(TDP-4974): Bump Jackson versions

---

dataprep-api/src/main/resources/application.properties
dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiPropertiesConfiguration.java

https://jira.talendforge.org/browse/TDP-4527

fix(TDP-4527): remove remote config

---

dataprep-api/src/main/resources/application.properties
dataprep-backend-service/src/main/java/org/talend/dataprep/ui/UiPropertiesConfiguration.java

fix(TDP-4527): remove remote config (#1168)

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
dataprep-test-api/src/main/resources/application.properties

https://jira.talendforge.org/browse/TDP-4961

chore: update RestAssured usage

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

https://jira.talendforge.org/browse/TDP-4284

fix(TDP-4284): TI-remove custom dico

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-5372

feat(TDP-5372): dataprep run custom semantic type

---

dataprep-webapp/src/app/index-route.js

https://jira.talendforge.org/browse/TDP-5376

feat(TDP-5376): wait for $translate service is ready

---

dataprep-webapp/src/app/index-route.js

feat(TDP-5376): wait for $translate service is ready (#1182)

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-4961

feat(TDP-4961): fix CustomSemanticType integration test

---

dataprep-webapp/config/webpack.config.js

https://jira.talendforge.org/browse/TDP-4527

chore(TDP-4527): avoid console error regarding theme

---

dataprep-webapp/config/webpack.config.js

chore(TDP-4527): avoid console error regarding theme (#1184)

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/step-progress/_step-progress.scss
dataprep-webapp/src/app/components/widgets-containers/breadcrumb/breadcrumb-container.spec.js
dataprep-webapp/src/app/components/widgets/modal/_modal.scss
dataprep-webapp/yarn.lock

fix(TDP-5389): app switcher bug

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-backend-service/src/test/java/org/talend/ServiceBaseTest.java
dataprep-test-api/src/main/resources/application.properties
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-4961

TDP-4961: cherry-pick

---

dataprep-webapp/src/app/index.themed.scss

https://jira.talendforge.org/browse/TDP-4527

fix(TDP-4527): breadcrumbs active item color

---

dataprep-webapp/src/app/index.themed.scss

cherry-pick 
#	dataprep-webapp/src/app/index.themed.scss

fix(TDP-4527): breadcrumbs active item color (#1196)

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/messages.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/messages_fr.properties
dataprep-webapp/src/app/settings/actions/external-actions-service.js
dataprep-webapp/src/app/settings/actions/external-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-4891

feat(TDP-4891): link to the user preferences in the user menu

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/export/ExportType.java

https://jira.talendforge.org/browse/TDP-5052

feat(TDP-5052): TI- check export fullrun S3 runtime

---

dataprep-async-api/pom.xml
dataprep-async-api/src/main/java/org/talend/dataprep/async/AsyncExecution.java
dataprep-async-api/src/test/java/org/talend/dataprep/async/AsyncExecutionTest.java

Use Comparable interface to implements natural ordering instead of supplying a static comparator.
Modified in the scope of Jira:
https://jira.talendforge.org/browse/TDP-5414

fix(TDP-5414): implements Comparable instead of custom Comparator

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datablending/Lookup.java
dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
dataprep-backend-service/src/test/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcherTest.java

https://jira.talendforge.org/browse/TDP-5378

fix(TDP-5378) Limit memory used in lookup cache

---

dataprep-backend-common/src/main/java/org/talend/dataprep/i18n/ActionsBundle.java

https://jira.talendforge.org/browse/TDP-5234

feat(TDP-5234): remove the stacktrace from the logs where missing resource

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/Action.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java

Chore : fix TI on 2.3

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-5436

feat(TDP-5436) : Add multi-tenant support for basic steps.

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java

https://jira.talendforge.org/browse/TDP-4284

feat(TDP-4284): removal a dictionary semantic type

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
dataprep-backend-service/src/main/java/org/talend/dataprep/api/user/UserData.java
dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/NoOpSecurity.java
dataprep-backend-service/src/main/java/org/talend/dataprep/security/Security.java
dataprep-backend-service/src/test/java/org/talend/dataprep/command/GenericCommandTest.java
dataprep-backend-service/src/test/java/org/talend/dataprep/i18n/DataprepLocaleContextResolverTest.java
dataprep-webapp/src/app/index-config.js
dataprep-webapp/src/app/index-module.js

feat(TDP-4712): user pref

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetDelete.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/folder/RemoveFolder.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/DataSetAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/FolderService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/FolderServiceTest.java

https://jira.talendforge.org/browse/TDP-5475

chore(TDP-5475): Change HTTP response statuses

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

feat(TDP-4712): upgrade monorepo

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-backend/pom.xml
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java
pom.xml

https://jira.talendforge.org/browse/TDP-5070

feat(TDP-5070) remove snapshots

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java

https://jira.talendforge.org/browse/TDP-5444

TDP-5444 close http on body map

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetMetadata.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AsyncBackgroundAnalysis.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/asynchronous/AnalysisEventProcessingTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/resources/features/PreparationContent.feature

https://jira.talendforge.org/browse/TDP-5444

fix(TDP-5444): pool connection full

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/command/transformation/SuggestColumnActions.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetMetadata.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DataSetMetadataBuilder.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/store/content/file/LocalFileContentStore.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/asynchronous/StatisticsAnalysisTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/ContentAnalysisTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/FormatAnalysisTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/QualityAnalysisTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java

* fix Path traversal issue on Upload Dataset raw API
* hardening against forged ID dataset raw update => only accept well-formed UUID
* remove dead code
* some refactoring in DataSetService
(cherry picked from commit 7123d998cd51cf6fcd47516422f91de6c87ca2de)
https://jira.talendforge.org/browse/TDP-3505

TDP-3505 [pentests 4.2] Directory Traversal in File Upload (Windows) => report fix

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActions.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/AppSettingsAPITest.java
dataprep-webapp/src/app/components/about/about.html
dataprep-webapp/src/app/css/components/_intro.scss

https://jira.talendforge.org/browse/TDP-5250

wi(TDP-5250): buttons colors

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java

There was a connection leak when using Defaults.convertResponse
closing the stream free the HTTP
(cherry picked from commit ccc9e50)
https://jira.talendforge.org/browse/TDP-5444

fix(TDP-5444): close stream when body is converted (#1231)

---

dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStepTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
dataprep-test-api/src/test/resources/features/ExportFormat.feature

https://jira.talendforge.org/browse/TDP-5439

fix(TDP-5439) : IT tests failures (maintenance/2.3)

---

dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFastHeaderAndTypeAnalyzer.java
dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVFastHeaderAndTypeAnalyzerTest.java

https://jira.talendforge.org/browse/TDP-5123

fix(TDP-5123): allow non pattern-neutral CSV separator

---

dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java

https://jira.talendforge.org/browse/TDP-4172

fix(TDP-4712): LocaleContextResolver for per-request local resolution

---

dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStepTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
dataprep-test-api/src/test/resources/features/ExportFormat.feature

https://jira.talendforge.org/browse/TDP-5439

fix(TDP-5439) : add fix from 2.3

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/AppSettingsAPI.java
dataprep-backend-service/src/main/java/org/talend/dataprep/i18n/DataprepLocaleContextResolver.java

fix(TDP-4712): Add context check for locale in settings API

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/AppSettingsAPI.java
dataprep-api/src/test/resources/application.properties

fix(TDP-4712): Fix unit test regression.

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/api/appheaderbar/AppHeaderBarSettings.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/api/breadcrumb/BreadcrumbSettings.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/api/list/ListSettings.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/api/sidepanel/SidePanelSettings.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/CommonViewsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViews.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/HomeViewsForNonTDPUsers.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/ListViews.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/PlaygroundViews.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/settings/views/provider/CommonViewsProviderTest.java

fix(TDP-4712): Remove use of singletons for view settings

---

dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStepTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/FolderUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
dataprep-test-api/src/test/resources/features/ExportFormat.feature

https://jira.talendforge.org/browse/TDP-5439

fix(TDP-5439) : report cleanup IT improvement from 2.3 to master

---

dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html

fix(TDP-5419): move data-feature to label

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html
dataprep-webapp/src/app/components/transformation/form/transformation-form-directive.js
dataprep-webapp/src/app/components/transformation/form/transformation-form.html

fix(TDP-5419): add category for functions

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html

fix(TDP-5419): fix data attributes

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionDefinition.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/action/ActionForm.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/action/ActionFormTest.java
dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html

fix(TDP-5419): improve business requirements

---

dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list-controller.spec.js
dataprep-webapp/src/app/components/suggestions-stats/actions-list/actions-list.html

fix(TDP-5419): fix tests

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationCreate.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/PreparationAPITest.java
dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParametersUtil.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/dataset/DataSetGetMetadata.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationDetailsGet.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/error/PreparationErrorCodes.java

https://jira.talendforge.org/browse/TDP-4959

fix(TDP-4959): unmanaged exceptions

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/GlobalStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/folder/OSFolderUtilTest.java
dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
dataprep-test-api/src/test/resources/features/ExportFormat.feature
dataprep-test-api/src/test/resources/features/SplitActionTest.feature

https://jira.talendforge.org/browse/TDP-5439

fix(TDP-5439) : add missing EE part cleaner

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

wi(TDP-5419): update dq and ui libs to meet pendo needs

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-5504

fix(TDP-5504): add app loader size bumping

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/type/Type.java

https://jira.talendforge.org/browse/TDP-5447

fix(TDP-5447): Remove semantic type does not work on "change semantic domain" step

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

https://jira.talendforge.org/browse/TDP-5359

chore(TDP-5359): update display version

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

fix(TDP-5516): missing tooltip on folder and preparations names
fix(TDP-5169): respect the folder name's case in the breadcrumb instead of forcing title case
https://jira.talendforge.org/browse/TDP-5516
https://jira.talendforge.org/browse/TDP-5169

chore: update frontend libs

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5359

TDP-5359: update dq lib to 5.0.3-SNAPSHOT

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/Step.java
dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentPreparationRepository.java
dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationCleaner.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarker.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationStepMarkerTest.java

* Move back to use String for marker (seems incompatible with TQL abstract layer).
* Missing marker filed in persistent storage.
* Fix wrong log query (incorrectly showing "0" steps to delete when there were some to delete).
* Count using filter wasn't done using persistent class name in PersistentPreparationRepository.
https://jira.talendforge.org/browse/TDP-4690

fix(TDP-4690) Fix delete of all steps

---

dataprep-backend/pom.xml

chore: update version of actions to 3.0.0-SNAPSHOT

---

dataprep-avro-message/pom.xml
dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5502

chore(TDP-5502): Update Dataprep Dependencies for Spring'18

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/date/StreamDateHistogramAnalyzer.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramAnalyzer.java
dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/transformer/json/NullAnalyzer.java
dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5359

chore(TDP-5359): Update DQ lib

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Trim.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/ActionMetadataTestUtils.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ChangeDatePatternTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSinceTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/ExtractNumberTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/TrimTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/ColumnMetadata.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Quantiles.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Statistics.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformer.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/StatisticsNodesBuilder.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/StepNode.java
dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/UpdatedStepVisitor.java

https://jira.talendforge.org/browse/TDP-4629
https://jira.talendforge.org/browse/TDP-5530

TDP-4926 : revert the revert

---

dataprep-test-api/src/test/resources/features/ExportFormat.feature
dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
dataprep-test-api/src/test/resources/features/SmokeTest.feature
dataprep-test-api/src/test/resources/features/SplitActionTest.feature
dataprep-test-api/src/test/resources/features/TrimActionTest.feature

chore : change features's title

---

dataprep-webapp/config/webpack.config.js
dataprep-webapp/src/app/index-module.js
dataprep-webapp/src/i18n/index.js
dataprep-webapp/src/i18n/ja.json

https://jira.talendforge.org/browse/TDP-5567

fix(TDP-5567): embed translations

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java

https://jira.talendforge.org/browse/TDP-5529

feat(TDP-5529): Export fullrun for preparation with no step

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/ColumnMetadata.java

https://jira.talendforge.org/browse/TDP-3514

fix(TDP-3514): Removal of an entry from a dictionary-based semantic type

---

dataprep-upgrade-common/src/main/java/org/talend/dataprep/upgrade/UpgradeService.java

https://jira.talendforge.org/browse/TDP-5530

skermabon/fix/TDP-5530 Add logs on needUpgrade

---

dataprep-webapp/src/app/index-module.js

https://jira.talendforge.org/browse/TDP-5567

fix(TDP-5567): Missing components tranlsations

---

dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-5576

fix(TDP-5576): typo

---

dataprep-backend-service/pom.xml
dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

https://jira.talendforge.org/browse/TDP-5534
https://jira.talendforge.org/browse/TDP-3514
https://jira.talendforge.org/browse/TDP-5447
https://jira.talendforge.org/browse/TDP-4284 

feat(TDP-5534) : add ITs for DQ

---

dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java

fix: ci dq fix

---

dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysisTest.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/TransformationServiceTest.java

Revert "fix: ci dq fix"

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/ActionsUtils.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ChangeDatePattern.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSince.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverter.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokens.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Trim.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/ActionMetadataTestUtils.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ChangeDatePatternTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ComputeTimeSinceTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/ExtractDateTokensTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/math/ExtractNumberTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/TrimTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/ColumnMetadata.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Quantiles.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/Statistics.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/TextLengthSummary.java
dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformer.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/builder/StatisticsNodesBuilder.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/node/StepNode.java
dataprep-backend-service/src/main/java/org/talend/dataprep/preparation/store/PersistentStep.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/UpdatedStepVisitor.java

This reverts commit fd02726cde4433f1536cc83722aa3a7e31250933.
https://jira.talendforge.org/browse/TDP-4926

fix(TDP-4926): revert the revert (#1095)"

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceImportTest.java

https://jira.talendforge.org/browse/TDP-5590
See https://jira.talendforge.org/browse/TDP-5590?focusedCommentId=549239&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-549239 for more details about issue.

fix(TDP-5590): Remove automatic deletion of analyzed dataset

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformation.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/FormatPhoneNumber.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/net/ExtractUrlTokensTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformationTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/phonenumber/extractphoneinformation.json
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/api/action/context/TransformationContext.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java

https://jira.talendforge.org/browse/TDP-1700

feat(TDQ-11891): Add an action to extract phone number informations

---

dataprep-backend-service/pom.xml
dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

https://jira.talendforge.org/browse/TDP-5534

feat(TDP-5534) : add ITs for DQ (#1309) 

---

dataprep-webapp/src/app/components/widgets-containers/app-header-bar/app-header-bar-container.scss
dataprep-webapp/src/app/components/widgets-containers/side-panel/side-panel.scss
dataprep-webapp/src/app/css/components/_intro.scss
dataprep-webapp/src/app/index.scss
dataprep-webapp/src/app/services/onboarding/onboarding-playground-constants.js
dataprep-webapp/src/app/services/onboarding/onboarding-service.spec.js
dataprep-webapp/src/app/services/playground/playground-service.js
dataprep-webapp/src/app/services/playground/playground-service.spec.js

fix(TDP-5608): onboarding

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/BackendProperties.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/User.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/resources/application.properties

(cherry picked from commit 416398d)
https://jira.talendforge.org/browse/TDP-5575

Yacarof/feat/tdp 5575 make multitenant users for it configurable (#1320)

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

* Small IT steps syntax fixes in order to ease future work.
https://jira.talendforge.org/browse/TDP-5494

fix(TDP-5494) : investigate coverage of IT and GUI-AUTO smoke tests

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/text/Trim.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/TrimTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/actions/date/DateParser.java

https://jira.talendforge.org/browse/TDQ-14001
- [] Docs have been added / updated (for bug fixes / features)

jbrun(chore) : fix TU test from DQ changes TDQ-14001 and remove wrong TRIM behaviour

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformation.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/phonenumber/ExtractPhoneInformationTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/phonenumber/extractphoneinformation.json
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/BasicRules.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java

https://jira.talendforge.org/browse/TDQ-14221
https://jira.talendforge.org/browse/TDP-1700

feat(TDQ-14221): extract information for an international phone number

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/TransformAPI.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGetContent.java

https://jira.talendforge.org/browse/TDP-4926

fix(TDP-4926) wrong transform strategy

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/suggestion/rules/TypeDomainRules.java

https://jira.talendforge.org/browse/TDP-5661

chore(TDP-5661): Improve rank of phone number actions

---

dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/all_dataset_scope_actions.json

https://jira.talendforge.org/browse/TDP-1700

fix(TDP-1700): Missing unit test update following latest fixes.

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
dataprep-test-api/src/test/resources/features/Aggregation.feature
dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
dataprep-test-api/src/test/resources/features/DatasetCache.feature

* IT inconsistency (discovered during TDP-5650) fixes.
https://jira.talendforge.org/browse/TDP-5650

fix(TDP-5650) : Setup toolset allowing dynamic IT documentation.

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

chore: update dataprep display version to 7.1.M0

---

dataprep-backend/pom.xml

chore: dataprep core version update

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

chore: upgrade node-sass for all distrib

---

dataprep-async-api/src/main/java/org/talend/dataprep/async/AsyncExecution.java
dataprep-async-runtime/src/main/java/org/talend/dataprep/async/SimpleManagedTaskExecutor.java

https://jira.talendforge.org/browse/TDP-5687

fix(TDP-5687): Preparation suddenly inaccessible and dataset row count back to 0

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

https://jira.talendforge.org/browse/TDP-5590

fix(TDP-5590): Fix regression in sample update.

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/datamasking/hashdata.json

https://jira.talendforge.org/browse/TDP-5726

feat(TDP-5726): Hash data

---

dataprep-webapp/src/app/components/filter/bar/filter-bar-directive.js
dataprep-webapp/src/app/components/filter/bar/filter-bar.html
dataprep-webapp/src/app/components/filter/monitor/_filter-monitor.scss
dataprep-webapp/src/app/components/filter/monitor/filter-monitor-directive.js
dataprep-webapp/src/app/components/filter/monitor/filter-monitor-directive.spec.js
dataprep-webapp/src/app/components/filter/monitor/filter-monitor.html

https://jira.talendforge.org/browse/TDP-5639

fix(TDP-5639): Hide filter count when previewing

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/datamasking/HashData.java

https://jira.talendforge.org/browse/TDP-5726

fix(TDP-5726): fix section

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/HashDataTest.java

https://jira.talendforge.org/browse/TDP-5726

fix(TDP-5726): correct HashData action TU

---

dataprep-webapp/src/app/next/sagas/effects/__tests__/bootstrap.effects.test.js
dataprep-webapp/src/app/next/sagas/effects/__tests__/preparation.effects.test.js
dataprep-webapp/src/app/next/sagas/effects/__tests__/redirect.effects.test.js
dataprep-webapp/src/app/next/sagas/effects/__tests__/search.effects.test.js
dataprep-webapp/src/app/next/sagas/watchers/__tests__/bootstrap.saga.test.js
dataprep-webapp/src/app/next/sagas/watchers/__tests__/help.saga.test.js
dataprep-webapp/src/app/next/sagas/watchers/__tests__/preparation.saga.test.js
dataprep-webapp/src/app/next/sagas/watchers/__tests__/search.saga.test.js

chore: assert that effects ends and watchers loops

---

dataprep-avro-message/pom.xml

fix(): Update message-model version to follow daikon property

---

dataprep-webapp/package.json
dataprep-webapp/yarn.lock

chore: fix CI build and notifications

---

dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.js
dataprep-webapp/src/app/services/dataset/rest/dataset-rest-service.spec.js

https://jira.talendforge.org/browse/TDP-5769

fix(TDP-5769): unable to overwrite an existing dataset

---

dataprep-webapp/src/app/components/step-progress/step-progress.html

https://jira.talendforge.org/browse/TDP-5773

fix(TDP-5773): no more circular spinner on the step progress modal

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java

* Correction for tDataprepRun component using custom Dictionary.
https://jira.talendforge.org/browse/TDP-5743

fix(TDP-5743) : Fix priority 1 unstable Integration Test features

---

dataprep-webapp/.eslintrc
dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js

https://jira.talendforge.org/browse/TDP-5776

wi(TDP-5776): handle http 202's status FAILED

---

dataprep-api/src/test/resources/application.properties
dataprep-async-runtime/src/test/resources/application.properties
dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-backend-service/src/test/resources/application.properties
dataprep-backend/pom.xml
dataprep-dataset/src/test/resources/application.properties
dataprep-preparation/src/test/resources/application.properties
dataprep-transformation/src/test/resources/application.properties
dataprep-upgrade/src/test/resources/application.properties

https://jira.talendforge.org/browse/TDP-5779

fix(TDP-5779): enable zipkin and update daikon to 0.25.0-SNAPSHOT

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

https://jira.talendforge.org/browse/TDP-4668

feat(TDP-4668) provide default zipkin configuration

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

https://jira.talendforge.org/browse/TDP-4668

feat(TDP-4668): configure and enable zipkin on tdp cloud

---

dataprep-webapp/src/app/services/playground/playground-service.js

fix(TDP-5790/TDP-5795): content and details are loaded twice when loading a preparation

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java

when using a Callable<Stream> as return value, there was a tenancy
context error as the context was cleaned after callable and was not
set when the stream map() is actually executed

chore: change list dataset return type to Stream

---

dataprep-webapp/.eslintrc
dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js

Revert "wi(TDP-5776): handle http 202's status FAILED (#1387)"

---

dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/StepNodeTransformation.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/configuration/StandardExportStrategiesIntegrationTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/configuration/preparation_details.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/service/configuration/two_steps_preparation_details.json

https://jira.talendforge.org/browse/TDP-5733
See PR https://github.com/Talend/data-prep-ee/pull/973

fix(TDP-5733): fix empty column on fetch more

---

dataprep-webapp/src/app/components/widgets/list-item-handler/_list-item-handler.scss

https://jira.talendforge.org/browse/TDP-5836

fix(TDP-5836): recipe arrows style

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-backend-service/src/main/java/org/talend/dataprep/util/InjectorUtil.java

https://jira.talendforge.org/browse/TDP-5696

fix(TDP-5696): fix export/import function + versioning

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java

https://jira.talendforge.org/browse/TDQ-14216

feat(TDQ-14216): Modify junit MaskDataByDomainTest to make it work well

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/common/AbstractGenerateSequenceAction.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/column/CreateNewColumnTest.java

* Makes start and step parameter mandatory when selected (can not be blank).
* Add unit test for mandatory start and step parameters.
https://jira.talendforge.org/browse/TDP-4592

fix(TDP-4592): Add code to handle edge cases.

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5814

feat(TDP-5814): fix version for Summer release

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5814

feat(TDP-5814): Upgrade version on master

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

https://jira.talendforge.org/browse/TDP-5814

feat(TDP-5814): Update display version for master

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSetMetadata.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java
dataprep-backend-service/src/main/java/org/talend/dataprep/user/store/UserDataRepository.java
dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversionTest.java

https://jira.talendforge.org/browse/TDP-5822

fix(TDP-5822): list DataSetMetada will not fetch the dataset content

---

dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js

https://jira.talendforge.org/browse/TDP-5837

fix(TDP-5837): missing datagrid headers

---

dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/conversions/DatasetBeanConversion.java

https://jira.talendforge.org/browse/TDP-5867

feat(TDP-5867): code review

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/delete/DeleteAllEmptyColumns.java
dataprep-test-api/src/test/resources/features/DeleteAllEmptyColumnsAction.feature

chore disable action: delete all empty columns

---

dataprep-backend/pom.xml

https://jira.talendforge.org/browse/TDP-5814

feat(TDP-5814): update dq version for Summer release

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java

* create a APIClient test method for list preparation details per version
https://jira.talendforge.org/browse/TDP-5870

feat(TDP-5870): create TU for preparation details with version

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/ActionFilterEnum.java
dataprep-api/src/test/java/org/talend/dataprep/helper/api/Filter.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/row/DataSetRow.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtil.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/DataSetExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/PreparationExportStrategy.java
dataprep-webapp/.eslintrc
dataprep-webapp/src/app/services/filter/manager/filter-manager-service.js
dataprep-webapp/src/app/services/rest/rest-queued-message-interceptor-factory.js

https://jira.talendforge.org/browse/TDP-5776

fix(TDP-5776) : fix fetchmore and invalid pb  backport fix from master on summer 18

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

https://jira.talendforge.org/browse/TDP-5873
https://jira.talendforge.org/browse/TDP-5875

fix(TDP-5873/TDP-5875): Update dataset content and clean cache

---

dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

cherry-pick of a33e997 in summer
https://jira.talendforge.org/browse/TDP-5873
https://jira.talendforge.org/browse/TDP-5875

fix(TDP-5873/TDP-5875): Update dataset content and clean cache (#1463)

---

dataprep-backend-service/src/test/java/org/talend/dataprep/command/DefaultsTest.java

The empty json response is not a use case handled by Defaults#convertResponse

chore: remove Defaults unit test about empty json response

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/Defaults.java
dataprep-backend-service/src/test/java/org/talend/dataprep/command/DefaultsTest.java

chore: revert default convert response

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java

Chore : refacto on async part

---

dataprep-backend-common/src/main/java/org/talend/dataprep/util/avro/AvroUtils.java
dataprep-backend-common/src/test/java/org/talend/dataprep/util/avro/AvroUtilsTest.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java

https://jira.talendforge.org/browse/TDP-5890

TDP 5890 avro col names

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java

https://jira.talendforge.org/browse/TDP-5884

fix(TDP-5884): Undo on a preparation make impossible to reopen

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/preparation/PreparationDetailsDTO.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java

https://jira.talendforge.org/browse/TDP-5888

fix(TDP-5888): Add missing metadata in preparation details (#1474)

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java

https://jira.talendforge.org/browse/TDP-5884

fix(TDP-5884): Undo on a preparation make impossible to reopen (#1473)

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

https://jira.talendforge.org/browse/TDP-5801

TDP-5801: fix S3 TIs

---

dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java

shared preparations could not access not shared dataset
See TDP-2676 fixing this for /sample endpoint
https://jira.talendforge.org/browse/TDP-5897

fix(TDP-5897): fix shared preparation access

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/User.java

The mecanism to switch between Integration Tests users and real users was broken and is fixed by this PR. See also this PR https://github.com/Talend/data-prep-ee/pull/1051
No JIRA issue linked

fix(Integ tests): fix users switch mecanism

---

dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js

https://jira.talendforge.org/browse/TDP-5837

fix(TDP-5837): missing datagrid headers (#1440)

---

dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java

https://jira.talendforge.org/browse/TDP-5895

fix(TDP-5895): fetch owner in author field

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java

Chore: add logs to control which URLs are really called

---

dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFormatUtils.java
dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVSchemaParser.java
dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVSchemaParserTest.java

This reverts commit d20ff90327bdf5a6334444894af35d4e982626bd.
https://jira.talendforge.org/browse/TDP-5925

Revert "fix(TDP-5925): CSV header not disappear when not detected

---

dataprep-backend-service/src/main/java/org/talend/dataprep/cache/CacheKeyGenerator.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/DataSetSampleCacheKey.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventListener.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysis.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListener.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationEventUtilTest.java

https://jira.talendforge.org/browse/TDP-5906

fix(TDP-5906): Unable to load content after editing a TCOMP dataset

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-5932

fix(TDP-5932): Fix default url parameters when unspecified in services.

---

dataprep-test-api/src/test/resources/application.properties

https://jira.talendforge.org/browse/TDP-5801

TDP-5801: S3 integration tests - update appplication.properties

---

dataprep-backend-service/src/main/java/org/talend/dataprep/cache/CacheKeyGenerator.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/DataSetSampleCacheKey.java
dataprep-backend-service/src/test/java/org/talend/dataprep/dataset/service/UserDataSetMetadataConversionTest.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventListener.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/analysis/synchronous/SchemaAnalysis.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListener.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/event/PreparationEventUtilTest.java
dataprep-test-api/README.md
dataprep-test-api/src/test/resources/application.properties

https://jira.talendforge.org/browse/TDP-5906

fix(TDP-5906) unable to load content after editing a tcomp

---

dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DefaultOwnerInjection.java
dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/OwnerInjection.java

This reverts commit d61eab5
https://jira.talendforge.org/browse/TDP-5895

Revert "Revert "fix(TDP-5895): fetch owner in author field" (#1499)"

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/datagrid/services/datagrid-column-service.js

chore: fix lint and organize deps

---

dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVFormatUtils.java
dataprep-backend-service/src/main/java/org/talend/dataprep/schema/csv/CSVSchemaParser.java
dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVFormatUtilsTest.java
dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVSchemaParserTest.java

https://jira.talendforge.org/browse/TDP-5925

fix(TDP-5925): revert the revert to make TU pass

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DistanceConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/DurationConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/conversions/TemperaturesConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/dataquality/StandardizeInvalidTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/FillEmptyFromAboveTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateSequenceTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/net/ExtractUrlTokensTest.java
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/text/RemoveRepeatedCharsTest.java

https://jira.talendforge.org/browse/TDQ-15120

add junit to ckeck those action work well for surrogate pair

---

dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DatasetConfiguration.java

chore: add isLegacy method for DatasetConfiguration

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

https://jira.talendforge.org/browse/TDP-5970

feat(TDP-5970): dropdown for expanded list

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/fill/GenerateUUID.java
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages_fr.properties
dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/fill/GenerateUUIDTest.java
dataprep-actions/src/test/resources/org/talend/dataprep/transformation/actions/fill/generateUUIDAction.json

https://jira.talendforge.org/browse/TDP-5035

feat(TDP-5035): add generate uuid action

---

dataprep-test-api/src/test/resources/features/Aggregation.feature
dataprep-test-api/src/test/resources/features/ChangeDatePatternActionTest.feature
dataprep-test-api/src/test/resources/features/CreateNewColumnActionTest.feature
dataprep-test-api/src/test/resources/features/DatasetCache.feature
dataprep-test-api/src/test/resources/features/DeleteAllEmptyColumnsAction.feature
dataprep-test-api/src/test/resources/features/ExportFormat.feature
dataprep-test-api/src/test/resources/features/ExportFormatXLSXResult.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromCSV.feature
dataprep-test-api/src/test/resources/features/ExportPreparationFromXLSX.feature
dataprep-test-api/src/test/resources/features/PreparationContent.feature
dataprep-test-api/src/test/resources/features/SearchAndReplaceActionTest.feature
dataprep-test-api/src/test/resources/features/SmokeTest.feature
dataprep-test-api/src/test/resources/features/SplitActionTest.feature
dataprep-test-api/src/test/resources/features/TrimActionTest.feature

chore : add wait on metadatas when upload

---

dataprep-webapp/src/app/components/widgets-containers/inventory-list/inventory-list-container.scss

feat(TDP-5970): dropdown in expanded mode

---

dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/cache/ScheduledCacheJanitor.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/executor/MaintenanceScheduler.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/executor/MaintenanceTaskProcess.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/executor/ScheduleFrequency.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/preparation/PreparationCleaner.java
dataprep-maintenance/src/main/java/org/talend/dataprep/maintenance/upgrade/UpgradeTask.java
dataprep-maintenance/src/main/resources/application.properties
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/BaseMaintenanceTest.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/cache/ScheduledCacheJanitorTest.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MaintenanceSchedulerTest.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MockScheduledNightlyTask.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MockScheduledOnceTask.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/executor/MockScheduledRepeatTask.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/preparation/PreparationCleanerTest.java
dataprep-maintenance/src/test/java/org/talend/dataprep/maintenance/upgrade/UpgradeTaskTest.java

https://jira.talendforge.org/browse/TDP-5734

fix(TDP-5734): cloud summer 2018

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
dataprep-api/src/test/resources/org/talend/dataprep/api/service/transformation/expected_cluster_params_soundex.json
dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/api/action/dynamic/cluster/ClusterParameters.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/ParametersTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/parameters/expected_cluster_params_soundex.json

Revert "fix(TDP-5860) : add comment in order to precise algorith behavior (#1…"

---

dataprep-test-api/src/test/resources/application.properties

fix defaut rest assured configuration

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateParserTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java

https://jira.talendforge.org/browse/TDP-5588

fix(TDQ-15371): recognized patterns more precise

---

dataprep-backend-common/src/main/java/org/talend/dataprep/quality/AnalyzerService.java

feat(TDQ-14160): add asian patterns

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatistics.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramStatisticsTest.java
dataprep-webapp/src/app/services/statistics/statistics-service.js
dataprep-webapp/yarn.lock

https://jira.talendforge.org/browse/TDP-5987

feat(TDP-5987): Manage infinity values in dataSet cells

---

dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/resources/application.properties

https://jira.talendforge.org/browse/TDP-5871

fix(TDP-5871) : Rework on how IT set execution context

---

dataprep-actions/src/main/java/org/talend/dataprep/transformation/actions/column/CreateNewColumn.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/DataSet.java
dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/row/DataSetRow.java
dataprep-backend-common/src/main/java/org/talend/dataprep/transformation/pipeline/Pipeline.java
dataprep-backend-service/src/main/java/org/talend/dataprep/api/export/ExportParametersUtil.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ExportPreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/ExportSampleStep.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/api/transformer/json/PipelineTransformer.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/TransformationService.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/OptimizedExportStrategy.java

https://jira.talendforge.org/browse/TDP-5898

fix(TDP-5898) : backport summer 18

---

dataprep-backend-service/src/main/java/org/talend/dataprep/folder/store/file/FileSystemFolderRepository.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationServiceTest.java

chore(files streams): fix failing unit tests on windows

---

dataprep-webapp/src/app/components/widgets-containers/widgets-containers-module.js

https://jira.talendforge.org/browse/TDP-6011

fix(TDP-6011): button forms

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

chore: update display version for master

---

dataprep-webapp/src/app/components/filter/monitor/filter-monitor.html
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list.html
dataprep-webapp/src/app/components/lookup/grid/header/_lookup-datagrid-header.scss
dataprep-webapp/src/app/components/suggestions-stats/stats-details/_stats-details.scss
dataprep-webapp/src/app/components/widgets/modal/_modal.scss
dataprep-webapp/src/app/components/widgets/modal/modal.html

https://jira.talendforge.org/browse/TDP-6016

fix(TDP-6016): fix styles in playground

---

dataprep-webapp/src/app/components/widgets/modal/_modal.scss

https://jira.talendforge.org/browse/TDP-6016

fix(TDP-6016): styles in playground

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/datamasking/MaskDataByDomainTest.java

https://jira.talendforge.org/browse/TDQ-14216

chore(TDQ-14216) : fix pb after DQ merge

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/export/ApplyPreparationExportStrategy.java

* clean code: fix missing "try-with-resource"
https://jira.talendforge.org/browse/TDP-4346

fix(TDP-4346): second fetch more not working

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/TransformAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/common/AsyncGet.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/DiffMetadata.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetMetadata.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreviewAbstract.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/TransformAPITest.java
dataprep-api/src/test/java/org/talend/dataprep/api/service/test/APIClientTest.java
dataprep-api/src/test/resources/org/talend/dataprep/api/service/transformation/expected_cluster_params_double_metaphone.json
dataprep-async-runtime/src/main/java/org/talend/dataprep/async/AsyncAspect.java
dataprep-async-runtime/src/main/java/org/talend/dataprep/async/AsyncController.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/api/action/dynamic/cluster/ClusterParameters.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/DataSetService.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/service/ParametersTest.java
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/parameters/expected_cluster_params_double_metaphone.json

https://jira.talendforge.org/browse/TDP-5860

fix(TDP-5860) : backport on maintenance summer 18

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java

https://jira.talendforge.org/browse/TDP-5860

chore(TDP-5860) : fix wrong previous merge

---

dataprep-actions/src/main/resources/org/talend/dataprep/i18n/actions_messages.properties
dataprep-actions/src/main/resources/org/talend/dataprep/transformation/actions/conversions/country-codes.csv

https://jira.talendforge.org/browse/TDP-5966

fix: fix country converter

---

dataprep-dataset/src/main/resources/application.properties
dataprep-transformation/src/main/resources/application.properties

chore(): active journalized content by default

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/AppSettingsAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/VersionServiceAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/AppSettingsService.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/configurer/ImportTypesConfigurer.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/DatasetActionsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/context/provider/ContextProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/views/provider/DatasetViewsProvider.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/version/DatasetVersionSupplier.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/DatasetConfiguration.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseTransformationService.java

Revert "feat(TDP-5791): add spring property source bind on config service"

---

dataprep-webapp/src/i18n/fr.json

https://jira.talendforge.org/browse/TDP-4969

feat(TDP-4969): Fix wordings

---

dataprep-webapp/src/app/css/components/_tooltips.scss

https://jira.talendforge.org/browse/TDP-3597

fix(TDP-3597): add tooltip to action label

---

dataprep-webapp/src/app/components/playground/header/_playground-header.scss
dataprep-webapp/src/app/components/playground/header/playground-header-component.js
dataprep-webapp/src/app/components/playground/header/playground-header-component.spec.js
dataprep-webapp/src/app/components/playground/header/playground-header.html
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/services/preview/preview-service.js
dataprep-webapp/src/app/services/preview/preview-service.spec.js
dataprep-webapp/src/app/services/state/playground/playground-state-service.js
dataprep-webapp/src/app/services/state/playground/playground-state-service.spec.js
dataprep-webapp/src/app/services/state/state-service.js

https://jira.talendforge.org/browse/TDP-1430

fix(TDP-1430): add loader to preview

---

dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
dataprep-webapp/src/app/components/loader/_loader.scss
dataprep-webapp/src/app/components/loader/loader.component.js
dataprep-webapp/src/app/components/loader/loader.component.spec.js
dataprep-webapp/src/app/components/loader/loader.html
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json
dataprep-webapp/src/i18n/ja.json

https://jira.talendforge.org/browse/TDP-5518

fix(TDP-5518): add loader when retrieving semantic types

---

dataprep-webapp/src/i18n/en.json

https://jira.talendforge.org/browse/TDP-4404

chore(TDP-4404): add labels

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramAnalyzer.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/statistics/number/StreamNumberHistogramAnalyzerTest.java

https://jira.talendforge.org/browse/TDP-4235

fix(TDP-4235) : catch parse number error and add TU

---

dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.spec.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header-directive.spec.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html
dataprep-webapp/src/app/components/transformation/menu/transformation-menu-directive.js
dataprep-webapp/src/app/components/transformation/menu/transformation-menu-directive.spec.js
dataprep-webapp/src/app/components/transformation/menu/transformation-menu.html
dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu-component.js
dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu-component.spec.js
dataprep-webapp/src/app/components/transformation/menu/type/type-transformation-menu.html

https://jira.talendforge.org/browse/TDP-5518

fix(TDP-5518): loading while retrieving semantic types

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

chore: Update display version for 7.1.1.M4 delivery

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/BaseExportStrategy.java

* fix TU
* take account review comment
https://jira.talendforge.org/browse/TDP-6050

fix(TDP-6050): stream export create empty files

---

dataprep-backend-common/src/main/java/org/talend/dataprep/api/filter/FilterTranslator.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/filter/FilterTranslatorTest.java

* fix translation of JSON filter 'matches' to TQL 'complies'
https://jira.talendforge.org/browse/TDP-6097

fix(TDP-6097): fix TQL translation to 'complies pattern'

---

dataprep-backend/pom.xml
dataprep-webapp/pom.xml
pom.xml

https://jira.talendforge.org/browse/TDP-4956

feat(TDP-4956): repair master with correct pom strucutre

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

https://jira.talendforge.org/browse/TDP-5849

feat(TDP-5849): Remove zipkin params from default on-prem config file

---

pom.xml

https://jira.talendforge.org/browse/TDP-4404

feat(TDP-4404): update to next core dev version

---

dataprep-backend-service/src/main/java/org/talend/dataprep/conversions/inject/DataSetNameInjection.java

chore(cloud): Fix formatter issue in previous change.

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

chore(): remove debug log

---

dataprep-backend-service/src/main/java/org/talend/dataprep/cache/ZippedContentCache.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/ContentCacheConfiguration.java
dataprep-backend-service/src/test/java/org/talend/dataprep/cache/ZippedContentCacheTest.java

chore(TDP-6139) Zip cached content for faster cache I/O

---

dataprep-webapp/src/app/components/datagrid/_datagrid.scss

https://jira.talendforge.org/browse/TDP-6127

fix(TDP-6127): fix the hidden "Apply to all cells" problem

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/settings/actions/provider/PreparationActions.java
dataprep-webapp/src/app/components/dataset/import/_dataset-import.scss
dataprep-webapp/src/app/components/dataset/import/dataset-import.controller.js
dataprep-webapp/src/app/components/dataset/preview/dataset-xls-preview.html
dataprep-webapp/src/app/components/export/export.html
dataprep-webapp/src/app/components/feedback/feedback.html
dataprep-webapp/src/app/components/folder/creator/folder-creator.html
dataprep-webapp/src/app/components/folder/creator/form/folder-creator-form.html
dataprep-webapp/src/app/components/home/confirm-modal/confirm-modal.html
dataprep-webapp/src/app/components/home/name-modal/name-modal.html
dataprep-webapp/src/app/components/inventory/copy-move/inventory-copy-move.html
dataprep-webapp/src/app/components/lookup/lookup.html
dataprep-webapp/src/app/components/playground/playground.html
dataprep-webapp/src/app/components/preparation/copy-move/preparation-copy-move.html
dataprep-webapp/src/app/components/preparation/creator/form/preparation-creator-form.html
dataprep-webapp/src/app/components/preparation/creator/preparation-creator.html
dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/_column-profile-options.scss
dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/column-profile-options-controller.js
dataprep-webapp/src/app/components/suggestions-stats/column-profile-options/column-profile-options.html
dataprep-webapp/src/app/next/components/PreparationCopyMoveModal/PreparationCopyMoveModal.component.js
dataprep-webapp/src/app/next/settings/settings.json
dataprep-webapp/src/app/services/confirm/confirm-service.js
dataprep-webapp/src/app/services/state/confirm/confirm-state-service.js
dataprep-webapp/src/app/settings/actions/dataset-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.js
dataprep-webapp/src/app/settings/actions/preparation-actions-service.spec.js

https://jira.talendforge.org/browse/TDP-5907

feat(TDP-5907): buttons colors

---

dataprep-avro-message/pom.xml
pom.xml

feat(TDP-5878): Update dataprep-core version to 1.0.2-SNAPSHOT

---

dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.spec.js

https://jira.talendforge.org/browse/TDP-3513

fix(TDP-3513): fix js error when bar chart value is negative

---

dataprep-webapp/src/app/components/datagrid/_datagrid.scss

https://jira.talendforge.org/browse/TDP-6170

fix(TDP-6170): checkbox apply to all cells with this value broken

---

dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-controller.js
dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-controller.spec.js
dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-directive.js
dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-directive.spec.js
dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status-module.js
dataprep-webapp/src/app/components/dataset/upload-status/dataset-upload-status.html
dataprep-webapp/src/app/services/dataset-workflow/update-workflow-service.js
dataprep-webapp/src/app/services/state/home/home-state-service.js
dataprep-webapp/src/app/services/state/home/home-state-service.spec.js
dataprep-webapp/src/app/services/state/state-service.js

https://jira.talendforge.org/browse/TDP-4363

fix(TDP-4363): import and fetch more progressbar animation

---

dataprep-backend-service/src/test/java/org/talend/dataprep/schema/csv/CSVSerializerTest.java
dataprep-backend-service/src/test/resources/org/talend/dataprep/api/dataset/json/test2.json
dataprep-preparation/src/test/java/org/talend/dataprep/preparation/service/PreparationControllerTest.java

needed before TDQ version bump
https://github.com/Talend/data-prep-core/pull/16

chore: generalize exception in CSV serializer test

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

feat(TDP-5878): change documentation URL for 2.8.0 release

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties

feat(TDP-5878): update version to 7.1.1

---

dataprep-webapp/package.json
dataprep-webapp/src/app/components/widgets-containers/collapsible-panel/collapsible-panel-container.spec.js
dataprep-webapp/yarn.lock

chore: upgrade Talend/ui

---

pom.xml

Chore
- [] Tests for the changes have been added (for bug fixes / features)
- [s] The new code does not introduce new technical issues (sonar / eslint)

Chore : change chore version to 1.0.5-SNAPSHOT

---

pom.xml

Chore(TDP-5878): change chore version to 1.0.6-SNAPSHOT

---

pom.xml

chore(TDP-5878): use data-prep-core 1.0.5

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java

https://jira.talendforge.org/browse/TDP-4135

feat(TDP-4135): dynamic app switcher

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java

https://jira.talendforge.org/browse/TDP-6093

fix(TDP-6093): Remove folder returns no content

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java

https://jira.talendforge.org/browse/TDP-4135

fix(TDP-4135): dynamic app switcher

---

dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java

https://jira.talendforge.org/browse/TDP-4135
cherry-pick

feat(TDP-4135): dynamic app switcher (#1697)

---

dataprep-transformation/src/main/java/org/talend/dataprep/transformation/service/ReactiveStepMetadataRepository.java
dataprep-transformation/src/test/java/org/talend/dataprep/transformation/ReactiveStepMetadataRepositoryTest.java

https://jira.talendforge.org/browse/TDP-6233

fix(TDP-6233): Add TenancyContext information

---

dataprep-api/src/test/java/org/talend/dataprep/api/service/FolderAPITest.java
dataprep-avro-message/pom.xml

https://jira.talendforge.org/browse/TDP-6228

feat(TDP-6228) update maven properties

---

dataprep-webapp/src/app/services/datagrid/datagrid-service.js

https://jira.talendforge.org/browse/TDP-5883

fix(TDP-5883): searching for an alphanumeric value in an integer one

---

dataprep-webapp/src/app/components/access-error/access-error-component.spec.js
dataprep-webapp/src/app/components/access-error/access-error-controller.js
dataprep-webapp/src/app/components/access-error/access-error-controller.spec.js
dataprep-webapp/src/app/components/access-error/access-error.html
dataprep-webapp/src/app/components/widgets/quality-bar/widget-quality-bar-controller.js
dataprep-webapp/src/app/index-module.js

https://jira.talendforge.org/browse/TDP-6237

fix(TDP-6237): 403 is a blank page

---

dataprep-webapp/src/app/services/state/grid/grid-state-service.js
dataprep-webapp/src/app/services/state/grid/grid-state-service.spec.js

https://jira.talendforge.org/browse/TDP-632

fix(TDP-632): select the 1st left column of the delete one

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java

Chore : Fix 204 status on folder deletion on TI

---

dataprep-api/pom.xml
dataprep-api/src/test/java/org/talend/dataprep/helper/OSDataPrepAPIHelper.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContextTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FilterStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/export/AbstractExportSampleStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java

Revert "fix (TDP-5956/TDP-5534) : improve wait process in integration tests"

---

dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.component.js
dataprep-webapp/src/app/next/components/FolderCreatorModal/FolderCreatorModal.connect.js
dataprep-webapp/src/app/next/components/FolderCreatorModal/actions.js
dataprep-webapp/src/app/next/sagas/effects/folder.effects.js

chore: remove not used variables

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

chore: Manage 202 on getPreparationContent

---

dataprep-backend-service/src/main/java/org/talend/dataprep/api/preparation/PreparationUtils.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/DataSetSampleCacheKey.java
dataprep-backend-service/src/main/java/org/talend/dataprep/cache/loader/ResourceLoaderContentCache.java
dataprep-backend-service/src/main/java/org/talend/dataprep/event/CacheEventProcessingUtil.java
dataprep-backend-service/src/test/java/org/talend/dataprep/cache/ResourceLoaderContentCacheTest.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationEventUtil.java

https://jira.talendforge.org/browse/TDP-6210
https://jira.talendforge.org/browse/TDP-6121
https://jira.talendforge.org/browse/TDP-6046

fix(TDP-6046/TDP-6121/TDP-6261): preparation service doesnt handle kafka event correctly

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java
dataprep-test-api/src/test/resources/features/DeleteInvalidActionTest.feature
dataprep-test-api/src/test/resources/features/NegateBooleanActionTest.feature

Chore : fix Excel export TI

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetDelete.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/DiffMetadata.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGet.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/preparation/PreparationGetActions.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java

Chore : fix format pb

---

dataprep-webapp/src/app/configure.cmf.js

https://jira.talendforge.org/browse/TDP-6271

feat(TDP-6271): forward header

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java

Revert "feat(TDP-5808): use Map instead of DataTable in IT"

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FolderStep.java

https://jira.talendforge.org/browse/TDP-5808

feat(TDP-5808): use Map instead of DataTable in IT

---

dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html

https://jira.talendforge.org/browse/TDP-6255

fix(TDP-6255): semantic types menu

---

dataprep-webapp/src/app/components/datagrid/header/datagrid-header-controller.js
dataprep-webapp/src/app/components/datagrid/header/datagrid-header.html

Revert "fix(TDP-6255): semantic types menu"

---

pom.xml

chore(): Update chore version

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java

Chore : fix DatasetOutput

---

dataprep-test-api/src/test/resources/features/ModuloMathAction.feature

chore: fix feature title

---

dataprep-backend-service/src/main/resources/org/talend/dataprep/configuration/default.properties
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_string_type_suggestions.json
dataprep-transformation/src/test/resources/org/talend/dataprep/transformation/suggestions/date_column_suggestions.json

https://jira.talendforge.org/browse/TDP-6335

fix(TDP-6335): fix links to doc

---

dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/DataPrepEvents.java
dataprep-backend-service/src/main/java/org/talend/dataprep/configuration/TaskExecution.java
dataprep-backend-service/src/main/java/org/talend/dataprep/event/AsyncApplicationListener.java
dataprep-backend-service/src/main/java/org/talend/dataprep/event/DataPrepEventsCaster.java

Revert "fix(TDP-6208): Enable async event on OnPrem bundle"

---

dataprep-dataset/src/test/resources/org/talend/dataprep/dataset/date_time_pattern_expected.json

https://jira.talendforge.org/browse/TDP-6263

fix (TDP-6263): Fix date patterns

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/DatasetStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

https://jira.talendforge.org/browse/TDP-6375

TDP-6375 : improve logs info on ITs

---

dataprep-webapp/src/app/components/recipe/_recipe.scss

https://jira.talendforge.org/browse/TDP-5102

fix(TDP-5102): recipe

---

dataprep-webapp/src/app/components/transformation/form/transformation-form-controller.js
dataprep-webapp/src/app/components/widgets/charts/horizontal-barchart/horizontal-barchart-directive.js
dataprep-webapp/src/app/services/datagrid/datagrid-service.js
dataprep-webapp/src/app/services/parameters/parameters-service.js
dataprep-webapp/src/app/services/recipe/recipe-service.js
dataprep-webapp/src/app/services/state/recipe/recipe-state-service.js
dataprep-webapp/src/app/services/statistics/date-occurence.worker.js
dataprep-webapp/src/app/services/statistics/pattern-occurence.worker.js
dataprep-webapp/src/app/services/statistics/statistics-service.js
dataprep-webapp/src/app/services/utils/date/date-service.js
dataprep-webapp/src/app/services/utils/text-format/text-format-service.js

chore: lodash imports

---

dataprep-webapp/src/app/components/inventory/item/inventory-item-component.spec.js
dataprep-webapp/src/app/components/lookup/dataset/list/lookup-dataset-list.html
dataprep-webapp/src/i18n/en.json
dataprep-webapp/src/i18n/fr.json
dataprep-webapp/src/i18n/ja.json
dataprep-webapp/src/i18n/zh.json

https://jira.talendforge.org/browse/TDP-6376

feat(TDP-6376): remove dataset rows number info from lookup

---

dataprep-webapp/src/app/components/lookup/lookup-controller.js
dataprep-webapp/src/app/components/lookup/lookup-controller.spec.js

https://jira.talendforge.org/browse/TDP-6366

fix(TDP-6366): Lookup redundant requests

---

pom.xml

https://jira.talendforge.org/browse/TDP-6277

fix (TDP-6277): Fix the first saved of StepRowMetadata on an imported

---

pom.xml

https://jira.talendforge.org/browse/TICO-1399

chore(TICO-1399): update core version to 1.0.7

---

dataprep-webapp/src/app/configure.cmf.js
dataprep-webapp/src/app/index.cmf.js

https://jira.talendforge.org/browse/TDP-6356
This PR need https://github.com/Talend/ui/pull/1846 so please do not merge before this one has been merged and released

chore(TDP-6356): remove redux-storage

---

dataprep-webapp/src/i18n/en.json

chore: consistent wording

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FileStep.java

https://jira.talendforge.org/browse/TDP-6375

wi(TDP-6375) : add missing logs on file comparator step

---

dataprep-test-api/src/test/resources/features/ConcatColumnsActionTest.feature

https://jira.talendforge.org/browse/TDP-1680

feat(TDP-1680): Unable ConcatColumns TI

---

pom.xml

Update to data-prep-core 1.0.10

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/dataset/DataSetDelete.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/command/preparation/PreparationGetContent.java
dataprep-backend-service/src/main/java/org/talend/dataprep/command/GenericCommand.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/ExceptionsConfiguration.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/TDPExceptionController.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/TDPExceptionFlowControl.java
dataprep-backend-service/src/main/java/org/talend/dataprep/exception/TdpExceptionDto.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/adapter/DataSetController.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/service/BaseDataSetService.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-2976

wi(TDP-2976): clean logs of tdp exception backport fall 18

---

dataprep-api/src/main/java/org/talend/dataprep/api/service/DataSetAPI.java
dataprep-api/src/main/java/org/talend/dataprep/api/service/PreparationAPI.java
dataprep-backend-service/src/main/java/org/talend/dataprep/dataset/adapter/DatasetClient.java
dataprep-backend-service/src/main/java/org/talend/dataprep/metrics/LogTimed.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventListener.java
dataprep-dataset/src/main/java/org/talend/dataprep/dataset/event/DatasetEventUtil.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/event/PreparationUpdateListener.java
dataprep-preparation/src/main/java/org/talend/dataprep/preparation/service/PreparationService.java

https://jira.talendforge.org/browse/TDP-6218

wi(TDP-6218): improve logs info fall 18 backport

---

dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/FilterStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java

https://jira.talendforge.org/browse/TDP-6609

fix(TDP-6609): backport fall18

---

pom.xml

https://jira.talendforge.org/browse/TICO-1437

feature(TICO-1437): dataprep core release 1.0.11

---

dataprep-backend-service/src/main/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcher.java
dataprep-backend-service/src/test/java/org/talend/dataprep/transformation/actions/datablending/DataSetLookupRowMatcherTest.java
dataprep-backend-service/src/test/java/org/talend/dataprep/util/UnitTestsUtil.java
dataprep-test-api/pom.xml
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/DataPrepStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContext.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/config/FeatureContextTest.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/ActionStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/step/PreparationStep.java
dataprep-test-api/src/test/java/org/talend/dataprep/qa/util/OSIntegrationTestUtilTest.java
pom.xml

https://jira.talendforge.org/browse/TDP-6642

bug(TDP-6642): Backport Fall 18 for TICO

---

pom.xml

https://jira.talendforge.org/browse/TICO-1609

wi(TICO-1609): backport fall 18 update core for TICO-1609

---

pom.xml

https://jira.talendforge.org/browse/TICO-1609
https://jira.talendforge.org/browse/TDP-6468

wi(TICO-1426): update tdp core version on fall18 to 1.0.13

---

dataprep-test-api/src/test/resources/features/Aggregation.feature

https://jira.talendforge.org/browse/TDP-7086

feat(TDP-7086): fix Aggregation integration test

---

dataprep-preparation/src/main/java/org/talend/dataprep/preparation/configuration/PreparationConversions.java
pom.xml

https://jira.talendforge.org/browse/TDP-7302

fix(TDP-7302): filter on column to update another column not working 7 1 1

---

dataprep-dataset/src/test/java/org/talend/dataprep/dataset/service/DataSetServiceTest.java

https://jira.talendforge.org/browse/TDP-7695

fix(TDP-7695): fix tests to complete clean up

---

dataprep-actions/src/test/java/org/talend/dataprep/transformation/actions/date/DateCalendarConverterTest.java
dataprep-backend-common/src/test/java/org/talend/dataprep/api/dataset/row/RowMetadataUtilsTest.java

https://jira.talendforge.org/browse/TDP-7705

fix(TDP-7705): Fix Unit Tests in all maintenance branches maintenance/2.1
